// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-MGATHER-MASK-STATIC-001","source":"asl/tile/memory-and-data-movement/irregular/MGATHER_MASK.asl","requirements":["PTO-INST-TILE-MGATHER-MASK"],"kind":"static-invariant","summary":"canonical MGATHER_MASK catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory-and-data-movement/irregular
    // block: BSTART.MGATHER.MASK DataType | B.DATR PadValue, Layout (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT IndexTile, MaskTile, mask=PE_MASK, <last>, ->DstTile<TSize> | B.IOR BaseGPR, zero, zero, ->zero | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000000110') == 93;
    assert TileOperationOfIndex(93) == TileOperation_MGATHER_MASK;
    assert TileHandlerOfIndex(93) == TileHandler_MGATHER_MASK;
    assert TileClassOfIndex(93) == TileClass_MemoryAndDataMovement;
    assert TileEngineOfIndex(93) == TileEngine_TLSU;
    assert InstructionContractOperation_MGATHER_MASK() == TileOperation_MGATHER_MASK;
    assert InstructionContractHandler_MGATHER_MASK() == TileHandler_MGATHER_MASK;
    return 0;
end;
