// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TQUANT-STATIC-INVARIANT-001","source":"asl/tile/complex-layout/format-conversion/TQUANT.asl","requirements":["PTO-INST-TILE-TQUANT"],"kind":"static-invariant","summary":"canonical TQUANT catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: complex-layout/format-conversion
    // block: BSTART.TEPL TQUANT, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001101010') == 76;
    assert TileOperationOfIndex(76) == TileOperation_TQUANT;
    assert TileHandlerOfIndex(76) == TileHandler_TQUANT;
    assert InstructionContractOperation_TQUANT() == TileOperation_TQUANT;
    assert InstructionContractHandler_TQUANT() == TileHandler_TQUANT;
    return 0;
end;
