// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-LBU-PCR-DECODE-001","source":"asl/scalar/agu/HL.LBU.PCR.asl","requirements":["PTO-INST-SCALAR-HL-LBU-PCR"],"kind":"decode-positive","summary":"canonical HL.LBU.PCR catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000001000000001110010000000000001110', 48) == 157;
    assert ScalarOperationOfForm(157) == ScalarOperation_HL_LBU_PCR;
    assert ScalarHandlerOfForm(157) == ScalarHandler_ExecuteScalarLoad;
    assert InstructionContractOperation_HL_LBU_PCR() == ScalarOperation_HL_LBU_PCR;
    assert InstructionContractHandler_HL_LBU_PCR() == ScalarHandler_ExecuteScalarLoad;
    assert InstructionContractAGUAction_HL_LBU_PCR() == ScalarAGU_Load;
    assert InstructionContractAGUAddressKind_HL_LBU_PCR() == ScalarAGU_PCRelative;
    assert InstructionContractAGUSizeBytes_HL_LBU_PCR() == 1;
    assert InstructionContractAGUOffsetScale_HL_LBU_PCR() == 2;
    assert InstructionContractAGUUpdateMode_HL_LBU_PCR() == AddressUpdate_None;
    assert InstructionContractAGUSignedLoad_HL_LBU_PCR() == FALSE;
    assert InstructionContractAGUPrefetchReturnsAddress_HL_LBU_PCR() == FALSE;
    assert DecodeScalarOperandRaw('000000000000000001000000001110010000000000001110', 157, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001000000001110010000000000001110', 157, ScalarField_simm) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
