// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LBU-PCR-ALIAS-001","source":"asl/scalar/agu/HL.LBU.PCR.asl","requirements":["PTO-INST-SCALAR-HL-LBU-PCR"],"kind":"execution","summary":"HL.LBU.PCR covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_HL_LBU_PCR();
    return 0;
end;
