// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-STATE-DEFINEDNESS-STATIC-001","source":"asl/arch/state/definedness.asl","requirements":[],"kind":"static-invariant","summary":"PTO-ARCH-STATE-DEFINEDNESS compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
