// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-LHIP-DECODE-001","source":"asl/scalar/agu/HL.LHIP.asl","requirements":["PTO-INST-SCALAR-HL-LHIP"],"kind":"decode-positive","summary":"canonical HL.LHIP catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000010000000110010000000000011110', 48) == 178;
    assert ScalarOperationOfForm(178) == ScalarOperation_HL_LHIP;
    assert ScalarHandlerOfForm(178) == ScalarHandler_ExecuteScalarLoadPair;
    assert InstructionContractOperation_HL_LHIP() == ScalarOperation_HL_LHIP;
    assert InstructionContractHandler_HL_LHIP() == ScalarHandler_ExecuteScalarLoadPair;
    assert InstructionContractAGUAction_HL_LHIP() == ScalarAGU_LoadPair;
    assert InstructionContractAGUAddressKind_HL_LHIP() == ScalarAGU_Immediate;
    assert InstructionContractAGUSizeBytes_HL_LHIP() == 2;
    assert InstructionContractAGUOffsetScale_HL_LHIP() == 1;
    assert InstructionContractAGUUpdateMode_HL_LHIP() == AddressUpdate_None;
    assert InstructionContractAGUSignedLoad_HL_LHIP() == TRUE;
    assert InstructionContractAGUPrefetchReturnsAddress_HL_LHIP() == FALSE;
    assert DecodeScalarOperandRaw('000000000000000000010000000110010000000000011110', 178, ScalarField_RegDst0) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000110010000000000011110', 178, ScalarField_RegDst1) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000110010000000000011110', 178, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000110010000000000011110', 178, ScalarField_simm17) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
