// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LHUI-PO-BOUND-001","source":"asl/scalar/agu/HL.LHUI.PO.asl","requirements":["PTO-INST-SCALAR-HL-LHUI-PO"],"kind":"boundary","summary":"HL.LHUI.PO covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_LHUI_PO();
    return 0;
end;
