// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FEQ-SRC-001","source":"asl/scalar/fsu/FEQ.asl","requirements":["PTO-INST-SCALAR-FEQ"],"kind":"execution","summary":"FEQ covers absolute and temporary-queue source selectors and aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUAliasSources_FEQ();
    return 0;
end;
