// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-RED-ADD-STATIC-001","source":"asl/tile/memory-and-data-movement/irregular/RED_ADD.asl","requirements":["PTO-INST-TILE-RED-ADD"],"kind":"static-invariant","summary":"canonical RED_ADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory-and-data-movement/irregular
    // block: BSTART.RED.ADD DataType | B.IOT IndexTile, ValueTile, mask=PE_MASK, <last> | B.IOR BaseGPR, zero, zero, ->zero | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000010101') == 118;
    assert TileOperationOfIndex(118) == TileOperation_RED_ADD;
    assert TileHandlerOfIndex(118) == TileHandler_GM_RED_VALUE;
    assert TileClassOfIndex(118) == TileClass_MemoryAndDataMovement;
    assert TileEngineOfIndex(118) == TileEngine_TLSU;
    assert InstructionContractOperation_RED_ADD() == TileOperation_RED_ADD;
    assert InstructionContractHandler_RED_ADD() == TileHandler_GM_RED_VALUE;
    return 0;
end;
