import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * ASL-backed units use one canonical workbench route. This sidebar retains
 * only project records that do not duplicate a generated unit workbench.
 */
const sidebars: SidebarsConfig = {
  reference: [
    {
      type: 'category',
      label: 'Decisions and architecture records',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'governance'},
        {type: 'autogenerated', dirName: 'status/decisions'},
        {type: 'autogenerated', dirName: 'status/open'},
      ],
    },
    {
      type: 'category',
      label: 'Development and releases',
      items: [
        {type: 'autogenerated', dirName: 'development'},
        {type: 'autogenerated', dirName: 'releases'},
      ],
    },
  ],
};

export default sidebars;
