// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-SHIP-DECODE-001","source":"asl/scalar/agu/HL.SHIP.asl","requirements":["PTO-INST-SCALAR-HL-SHIP"],"kind":"decode-positive","summary":"canonical HL.SHIP catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000010000010110010000000000011110', 48) == 287;
    assert ScalarOperationOfForm(287) == ScalarOperation_HL_SHIP;
    assert ScalarHandlerOfForm(287) == ScalarHandler_ExecuteScalarStorePair;
    assert InstructionContractOperation_HL_SHIP() == ScalarOperation_HL_SHIP;
    assert InstructionContractHandler_HL_SHIP() == ScalarHandler_ExecuteScalarStorePair;
    assert InstructionContractAGUAction_HL_SHIP() == ScalarAGU_StorePair;
    assert InstructionContractAGUAddressKind_HL_SHIP() == ScalarAGU_Immediate;
    assert InstructionContractAGUSizeBytes_HL_SHIP() == 2;
    assert InstructionContractAGUOffsetScale_HL_SHIP() == 1;
    assert InstructionContractAGUUpdateMode_HL_SHIP() == AddressUpdate_None;
    assert InstructionContractAGUSignedLoad_HL_SHIP() == FALSE;
    assert InstructionContractAGUPrefetchReturnsAddress_HL_SHIP() == FALSE;
    assert DecodeScalarOperandRaw('000000000000000000010000010110010000000000011110', 287, ScalarField_SrcD) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000010110010000000000011110', 287, ScalarField_SrcD1) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000010110010000000000011110', 287, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000010110010000000000011110', 287, ScalarField_simm17) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
