// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-SBIP-DECODE-001","source":"asl/scalar/agu/HL.SBIP.asl","requirements":["PTO-INST-SCALAR-HL-SBIP"],"kind":"decode-positive","summary":"canonical HL.SBIP catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000010110010000000000011110', 48) == 250;
    assert ScalarOperationOfForm(250) == ScalarOperation_HL_SBIP;
    assert ScalarHandlerOfForm(250) == ScalarHandler_ExecuteScalarStorePair;
    assert InstructionContractOperation_HL_SBIP() == ScalarOperation_HL_SBIP;
    assert InstructionContractHandler_HL_SBIP() == ScalarHandler_ExecuteScalarStorePair;
    assert DecodeScalarOperandRaw('000000000000000000000000010110010000000000011110', 250, ScalarField_SrcD) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000010110010000000000011110', 250, ScalarField_SrcD1) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000010110010000000000011110', 250, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000010110010000000000011110', 250, ScalarField_simm17) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
