// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FGE-FLAGS-001","source":"asl/scalar/fsu/FGE.asl","requirements":["PTO-INST-SCALAR-FGE"],"kind":"state-transition","summary":"FGE covers sticky floating-point exception-flag accumulation","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUFlags_FGE();
    return 0;
end;
