// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LDI-UPO-EXEC-001","source":"asl/scalar/agu/HL.LDI.UPO.asl","requirements":["PTO-INST-SCALAR-HL-LDI-UPO"],"kind":"execution","summary":"HL.LDI.UPO executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_LDI_UPO();
    return 0;
end;
