// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-MATRIX-POSTPROCESS-STATIC-001","source":"asl/tile/model/execution/matrix-postprocess.asl","requirements":["PTO-MATRIX-POSTPROCESS-BITEXACT-001"],"kind":"static-invariant","summary":"PTO-TILE-MODEL-EXECUTION-MATRIX-POSTPROCESS compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
