// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-SETC-EQI-BOUND-001","source":"asl/scalar/bru/SETC.EQI.asl","requirements":["PTO-INST-SCALAR-SETC-EQI"],"kind":"boundary","summary":"SETC.EQI covers operand selectors, immediates, conditions, targets, and faults","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUBounds_SETC_EQI();
    return 0;
end;
