// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SHI-BOUND-001","source":"asl/scalar/agu/HL.SHI.asl","requirements":["PTO-INST-SCALAR-HL-SHI"],"kind":"boundary","summary":"HL.SHI covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_SHI();
    return 0;
end;
