// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-MEMORY-MODEL-ADDRESS-SPACE-STATIC-001","source":"asl/arch/memory-model/address-space.asl","requirements":["PTO-REQ-FUNCTIONAL-MEMORY-001"],"kind":"static-invariant","summary":"PTO-ARCH-MEMORY-MODEL-ADDRESS-SPACE compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
