// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SYS-SSRSET-TSRC-001","source":"asl/scalar/sys/SSRSET.asl","requirements":["PTO-INST-SCALAR-SSRSET"],"kind":"execution","summary":"SSRSET proves its tsrc SYS contract","pass_condition":"the mnemonic-owned decoded assertions hold","related_sources":[]}
func main() => integer
begin
    ResetProfileState();
    SetCurrentACR(0);
    WriteTPC(Zeros{PTO_XLEN} + 0x100);
    BeginBundle(BundleKind_System, BundleTransfer_Fallthrough,
        Zeros{PTO_XLEN}, Zeros{PTO_XLEN} + 0x180,
        Zeros{PTO_XLEN}, FALSE);
    EnterBundleBody();
    _TQueue[[0]] = Zeros{PTO_XLEN} + 0x222;
    _TQueueValid[[0]] = TRUE;
    let status = ExecuteScalarInstruction('000000000000000000000000000011000001000000111011', 32);
    assert status == ScalarExecution_Executed;
    assert _LastFault == Fault_None;
    assert _SystemRegisters.thread_ptr == Zeros{PTO_XLEN} + 0x222;
    assert ReadTemporaryQueue(TRUE, 0) == Zeros{PTO_XLEN} + 0x222;
    assert ReadTPC() == Zeros{PTO_XLEN} + 0x184;
    assert InstructionContractOperation_SSRSET() == ScalarOperation_SSRSET;
    return 0;
end;
