// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SYS-SSRSWAP-DISCARD-001","source":"asl/scalar/sys/SSRSWAP.asl","requirements":["PTO-INST-SCALAR-SSRSWAP"],"kind":"execution","summary":"SSRSWAP proves its discard SYS contract","pass_condition":"the mnemonic-owned decoded assertions hold","related_sources":[]}
func main() => integer
begin
    ResetProfileState();
    SetCurrentACR(0);
    WriteTPC(Zeros{PTO_XLEN} + 0x100);
    BeginBundle(BundleKind_System, BundleTransfer_Fallthrough,
        Zeros{PTO_XLEN}, Zeros{PTO_XLEN} + 0x180,
        Zeros{PTO_XLEN}, FALSE);
    EnterBundleBody();
    WriteGPR(5, Zeros{PTO_XLEN} + 0x222);
    _SystemRegisters.thread_ptr = Zeros{PTO_XLEN} + 0x111;
    let status = ExecuteScalarInstruction('000000000000000000000000000000101010110000111011', 32);
    assert status == ScalarExecution_Executed;
    assert _LastFault == Fault_None;
    assert !_TQueueValid[[0]];
    assert !_UQueueValid[[0]];
    assert _SystemRegisters.thread_ptr == Zeros{PTO_XLEN} + 0x222;
    assert ReadTPC() == Zeros{PTO_XLEN} + 0x184;
    assert InstructionContractOperation_SSRSWAP() == ScalarOperation_SSRSWAP;
    return 0;
end;
