// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FMUL-BOUND-001","source":"asl/scalar/fsu/FMUL.asl","requirements":["PTO-INST-SCALAR-FMUL"],"kind":"boundary","summary":"FMUL covers zeros, infinities, NaNs, extrema, and signed carriers","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUBounds_FMUL();
    return 0;
end;
