// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FMUL-EXEC-001","source":"asl/scalar/fsu/FMUL.asl","requirements":["PTO-INST-SCALAR-FMUL"],"kind":"execution","summary":"FMUL executes the canonical floating-point or conversion effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUExecute_FMUL();
    return 0;
end;
