// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LH-PR-ALIAS-001","source":"asl/scalar/agu/HL.LH.PR.asl","requirements":["PTO-INST-SCALAR-HL-LH-PR"],"kind":"execution","summary":"HL.LH.PR covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_HL_LH_PR();
    return 0;
end;
