// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-SCVTF-BOUND-001","source":"asl/scalar/fsu/SCVTF.asl","requirements":["PTO-INST-SCALAR-SCVTF"],"kind":"boundary","summary":"SCVTF covers zeros, infinities, NaNs, extrema, and signed carriers","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUBounds_SCVTF();
    return 0;
end;
