// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-SCVTF-EXEC-001","source":"asl/scalar/fsu/SCVTF.asl","requirements":["PTO-INST-SCALAR-SCVTF"],"kind":"execution","summary":"SCVTF executes the canonical floating-point or conversion effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUExecute_SCVTF();
    return 0;
end;
