// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-SCVTF-SRC-001","source":"asl/scalar/fsu/SCVTF.asl","requirements":["PTO-INST-SCALAR-SCVTF"],"kind":"execution","summary":"SCVTF covers absolute and temporary-queue source selectors and aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUAliasSources_SCVTF();
    return 0;
end;
