// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-MULW-DECODE-001","source":"asl/scalar/alu/MULW.asl","requirements":["PTO-INST-SCALAR-MULW"],"kind":"decode-positive","summary":"canonical MULW catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000010000001000111', 32) == 365;
    assert ScalarOperationOfForm(365) == ScalarOperation_MULW;
    assert ScalarHandlerOfForm(365) == ScalarHandler_ScalarMultiplyW;
    assert InstructionContractOperation_MULW() == ScalarOperation_MULW;
    assert InstructionContractHandler_MULW() == ScalarHandler_ScalarMultiplyW;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000010000001000111', 365, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000010000001000111', 365, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000010000001000111', 365, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
