// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-B-EQ-DECODE-001","source":"asl/scalar/bru/B.EQ.asl","requirements":["PTO-INST-SCALAR-B-EQ"],"kind":"decode-positive","summary":"canonical B.EQ catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000000000000100111', 32) == 12;
    assert ScalarOperationOfForm(12) == ScalarOperation_B_EQ;
    assert ScalarHandlerOfForm(12) == ScalarHandler_BranchRelative;
    assert InstructionContractOperation_B_EQ() == ScalarOperation_B_EQ;
    assert InstructionContractHandler_B_EQ() == ScalarHandler_BranchRelative;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000100111', 12, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000100111', 12, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000100111', 12, ScalarField_simm12) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
