// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-B-EQ-BOUND-001","source":"asl/scalar/bru/B.EQ.asl","requirements":["PTO-INST-SCALAR-B-EQ"],"kind":"boundary","summary":"B.EQ covers operand selectors, immediates, conditions, targets, and faults","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUBounds_B_EQ();
    return 0;
end;
