// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-OVERVIEW-ENCODING-OWNERSHIP-STATIC-001","source":"asl/arch/overview/encoding-ownership.asl","requirements":["PTO-ARCH-ENCODING-OWNERSHIP-001","PTO-ARCH-CONDITIONAL-BRANCH-RESERVATION-001"],"kind":"static-invariant","summary":"PTO-ARCH-OVERVIEW-ENCODING-OWNERSHIP compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
