// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FNES-SNAP-001","source":"asl/scalar/fsu/FNES.asl","requirements":["PTO-INST-SCALAR-FNES"],"kind":"execution","summary":"FNES covers source snapshotting before overlapping destination publication","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUAliasSnapshot_FNES();
    return 0;
end;
