// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FNES-RSVD-001","source":"asl/scalar/fsu/FNES.asl","requirements":["PTO-INST-SCALAR-FNES"],"kind":"fault","summary":"FNES rejects reserved data-type encodings before architectural effects","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUTypesReserved_FNES();
    return 0;
end;
