// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-MGATHER-MAX-SEMANTIC-001","source":"asl/tile/memory-and-data-movement/irregular/MGATHER_MAX.asl","requirements":["PTO-INST-TILE-MGATHER-MAX"],"kind":"execution","summary":"MGATHER_MAX exercises its GM semantic primitive at the owner boundary","pass_condition":"the decoded owner mapping and representative GM effect assertions hold","related_sources":["asl/tile/model/memory/gm-atom-red.asl","asl/tile/model/memory/gm-atom-red-execution.asl"]}
func main() => integer
begin
    assert GMAtomicOperationFromFunction(10) == GMAtomic_MAX;
    assert GMAtomicOperationDataTypeLegal(GMAtomic_MAX, TileDataType_U32);
    let (result, performed) = GMAtomicResult(GMAtomic_MAX, TileDataType_U32,
        Zeros{PTO_XLEN} + 3, Zeros{PTO_XLEN} + 5,
        Zeros{PTO_XLEN} + 0, Zeros{PTO_XLEN} + 0);
    assert result == Zeros{PTO_XLEN} + 5;
    assert performed;
    return 0;
end;
