// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SYS-TLB-IAV-TSRC-001","source":"asl/scalar/sys/TLB.IAV.asl","requirements":["PTO-INST-SCALAR-TLB-IAV"],"kind":"execution","summary":"TLB.IAV proves its tsrc SYS contract","pass_condition":"the mnemonic-owned decoded assertions hold","related_sources":[]}
func main() => integer
begin
    ResetProfileState();
    SetCurrentACR(0);
    WriteTPC(Zeros{PTO_XLEN} + 0x100);
    BeginBundle(BundleKind_System, BundleTransfer_Fallthrough,
        Zeros{PTO_XLEN}, Zeros{PTO_XLEN} + 0x180,
        Zeros{PTO_XLEN}, FALSE);
    EnterBundleBody();
    _TQueue[[0]] = Zeros{PTO_XLEN} + 0x1000;
    _TQueueValid[[0]] = TRUE;
    let status = ExecuteScalarInstruction('000000000000000000000000001011000111000000101011', 32);
    assert status == ScalarExecution_Executed;
    assert _LastFault == Fault_None;
    assert _TLBEpoch == 1;
    assert ReadTemporaryQueue(TRUE, 0) == Zeros{PTO_XLEN} + 0x1000;
    assert _LastMaintenanceOperation == Maintenance_TLB_IAV;
    assert _LastMaintenanceOperand == Zeros{PTO_XLEN} + 0x1000;
    assert ReadTPC() == Zeros{PTO_XLEN} + 0x184;
    assert InstructionContractOperation_TLB_IAV() == ScalarOperation_TLB_IAV;
    return 0;
end;
