// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SW-PR-FAULT-001","source":"asl/scalar/agu/HL.SW.PR.asl","requirements":["PTO-INST-SCALAR-HL-SW-PR"],"kind":"fault","summary":"HL.SW.PR rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_HL_SW_PR();
    return 0;
end;
