// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-SWI-UPO-DECODE-001","source":"asl/scalar/agu/HL.SWI.UPO.asl","requirements":["PTO-INST-SCALAR-HL-SWI-UPO"],"kind":"decode-positive","summary":"canonical HL.SWI.UPO catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000001100000010110010000000000111110', 48) == 304;
    assert ScalarOperationOfForm(304) == ScalarOperation_HL_SWI_UPO;
    assert ScalarHandlerOfForm(304) == ScalarHandler_ExecuteScalarStore;
    assert InstructionContractOperation_HL_SWI_UPO() == ScalarOperation_HL_SWI_UPO;
    assert InstructionContractHandler_HL_SWI_UPO() == ScalarHandler_ExecuteScalarStore;
    assert InstructionContractAGUAction_HL_SWI_UPO() == ScalarAGU_Store;
    assert InstructionContractAGUAddressKind_HL_SWI_UPO() == ScalarAGU_Immediate;
    assert InstructionContractAGUSizeBytes_HL_SWI_UPO() == 4;
    assert InstructionContractAGUOffsetScale_HL_SWI_UPO() == 0;
    assert InstructionContractAGUUpdateMode_HL_SWI_UPO() == AddressUpdate_PostIndex;
    assert InstructionContractAGUSignedLoad_HL_SWI_UPO() == FALSE;
    assert InstructionContractAGUPrefetchReturnsAddress_HL_SWI_UPO() == FALSE;
    assert DecodeScalarOperandRaw('000000000000000001100000010110010000000000111110', 304, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001100000010110010000000000111110', 304, ScalarField_SrcD) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001100000010110010000000000111110', 304, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001100000010110010000000000111110', 304, ScalarField_simm17) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
