// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SWI-UPO-FAULT-001","source":"asl/scalar/agu/HL.SWI.UPO.asl","requirements":["PTO-INST-SCALAR-HL-SWI-UPO"],"kind":"fault","summary":"HL.SWI.UPO rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_HL_SWI_UPO();
    return 0;
end;
