// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-RED-POPC-DECODE-001","source":"asl/block/execution/BSTART.RED.POPC.asl","requirements":["PTO-INST-BLOCK-BSTART-RED-POPC"],"kind":"decode-positive","summary":"canonical BSTART.RED.POPC catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000001101100010001000110000001', 32) == 93;
    assert CommandOperationOfForm(93) == CommandOperation_bstart_red_popc_32_gm27;
    assert CommandHandlerOfForm(93) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_BSTART_RED_POPC(CommandOperationOfForm(93));
    assert InstructionContractHandler_BSTART_RED_POPC() == CommandHandler_ExecuteBundleStart;
    return 0;
end;
