// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SWI-EXEC-001","source":"asl/scalar/agu/SWI.asl","requirements":["PTO-INST-SCALAR-SWI"],"kind":"execution","summary":"SWI executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_SWI();
    return 0;
end;
