// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SWI-BOUND-001","source":"asl/scalar/agu/SWI.asl","requirements":["PTO-INST-SCALAR-SWI"],"kind":"boundary","summary":"SWI covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_SWI();
    return 0;
end;
