// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SWI-FAULT-001","source":"asl/scalar/agu/SWI.asl","requirements":["PTO-INST-SCALAR-SWI"],"kind":"fault","summary":"SWI rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_SWI();
    return 0;
end;
