// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TCVT-STATIC-001","source":"asl/tile/elementwise-tile-tile/format-conversion/TCVT.asl","requirements":["PTO-INST-TILE-TCVT"],"kind":"static-invariant","summary":"canonical TCVT catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: elementwise-tile-tile/format-conversion
    // block: BSTART.VEC TCVT, SrcDataType | B.DATR DstDataType, RMode, Sat, Canonicalize, Layout, PadValue (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT SrcTile, mask=PE_MASK, <last>, ->DstTile<TSize> | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000011011') == 23;
    assert TileOperationOfIndex(23) == TileOperation_TCVT;
    assert TileHandlerOfIndex(23) == TileHandler_TCVT;
    assert TileClassOfIndex(23) == TileClass_ElementwiseTileTile;
    assert TileEngineOfIndex(23) == TileEngine_VEC;
    assert InstructionContractOperation_TCVT() == TileOperation_TCVT;
    assert InstructionContractHandler_TCVT() == TileHandler_TCVT;
    return 0;
end;
