// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-SUB-DECODE-001","source":"asl/scalar/alu/SUB.asl","requirements":["PTO-INST-SCALAR-SUB"],"kind":"decode-positive","summary":"canonical SUB catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000001000000000101', 32) == 436;
    assert ScalarOperationOfForm(436) == ScalarOperation_SUB;
    assert ScalarHandlerOfForm(436) == ScalarHandler_ScalarBinary;
    assert InstructionContractOperation_SUB() == ScalarOperation_SUB;
    assert InstructionContractHandler_SUB() == ScalarHandler_ScalarBinary;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000001000000000101', 436, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000001000000000101', 436, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000001000000000101', 436, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000001000000000101', 436, ScalarField_SrcRType) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000001000000000101', 436, ScalarField_shamt) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
