// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LBUI-EXEC-001","source":"asl/scalar/agu/HL.LBUI.asl","requirements":["PTO-INST-SCALAR-HL-LBUI"],"kind":"execution","summary":"HL.LBUI executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_LBUI();
    return 0;
end;
