// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-LW-SMIN-DECODE-001","source":"asl/scalar/amo/LW.SMIN.asl","requirements":["PTO-INST-SCALAR-LW-SMIN"],"kind":"decode-positive","summary":"canonical LW.SMIN catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000001010000000000000010000000001011', 32) == 354;
    assert ScalarOperationOfForm(354) == ScalarOperation_LW_SMIN;
    assert ScalarHandlerOfForm(354) == ScalarHandler_AtomicReadModifyWrite;
    assert InstructionContractOperation_LW_SMIN() == ScalarOperation_LW_SMIN;
    assert InstructionContractHandler_LW_SMIN() == ScalarHandler_AtomicReadModifyWrite;
    assert DecodeScalarOperandRaw('000000000000000001010000000000000010000000001011', 354, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001010000000000000010000000001011', 354, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001010000000000000010000000001011', 354, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001010000000000000010000000001011', 354, ScalarField_aq) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001010000000000000010000000001011', 354, ScalarField_far) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001010000000000000010000000001011', 354, ScalarField_rl) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
