// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-HL-CMP-LTUI-EXEC-001","source":"asl/scalar/bru/HL.CMP.LTUI.asl","requirements":["PTO-INST-SCALAR-HL-CMP-LTUI"],"kind":"execution","summary":"HL.CMP.LTUI executes the canonical comparison, branch, jump, or control effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUExecute_HL_CMP_LTUI();
    return 0;
end;
