// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-B-NZ-ALIAS-001","source":"asl/scalar/bru/B.NZ.asl","requirements":["PTO-INST-SCALAR-B-NZ"],"kind":"execution","summary":"B.NZ covers special register aliases, queue selectors, or precise control faults","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUAlias_B_NZ();
    return 0;
end;
