// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-SHIP-U-DECODE-001","source":"asl/scalar/agu/HL.SHIP.U.asl","requirements":["PTO-INST-SCALAR-HL-SHIP-U"],"kind":"decode-positive","summary":"canonical HL.SHIP.U catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000001010000010110010000000000011110', 48) == 280;
    assert ScalarOperationOfForm(280) == ScalarOperation_HL_SHIP_U;
    assert ScalarHandlerOfForm(280) == ScalarHandler_ExecuteScalarStorePair;
    assert InstructionContractOperation_HL_SHIP_U() == ScalarOperation_HL_SHIP_U;
    assert InstructionContractHandler_HL_SHIP_U() == ScalarHandler_ExecuteScalarStorePair;
    assert InstructionContractAGUAction_HL_SHIP_U() == ScalarAGU_StorePair;
    assert InstructionContractAGUAddressKind_HL_SHIP_U() == ScalarAGU_Immediate;
    assert InstructionContractAGUSizeBytes_HL_SHIP_U() == 2;
    assert InstructionContractAGUOffsetScale_HL_SHIP_U() == 0;
    assert InstructionContractAGUUpdateMode_HL_SHIP_U() == AddressUpdate_None;
    assert InstructionContractAGUSignedLoad_HL_SHIP_U() == FALSE;
    assert InstructionContractAGUPrefetchReturnsAddress_HL_SHIP_U() == FALSE;
    assert DecodeScalarOperandRaw('000000000000000001010000010110010000000000011110', 280, ScalarField_SrcD) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001010000010110010000000000011110', 280, ScalarField_SrcD1) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001010000010110010000000000011110', 280, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001010000010110010000000000011110', 280, ScalarField_simm17) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
