// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TROWSUM-STATIC-INVARIANT-001","source":"asl/tile/reduction/row-reduction/TROWSUM.asl","requirements":["PTO-INST-TILE-TROWSUM"],"kind":"static-invariant","summary":"canonical TROWSUM catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: reduction/row-reduction
    // block: BSTART.TEPL TROWSUM, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001000000') == 40;
    assert TileOperationOfIndex(40) == TileOperation_TROWSUM;
    assert TileHandlerOfIndex(40) == TileHandler_ExecuteTileReduction;
    assert InstructionContractOperation_TROWSUM() == TileOperation_TROWSUM;
    assert InstructionContractHandler_TROWSUM() == TileHandler_ExecuteTileReduction;
    return 0;
end;
