// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SB-PCR-ALIAS-001","source":"asl/scalar/agu/HL.SB.PCR.asl","requirements":["PTO-INST-SCALAR-HL-SB-PCR"],"kind":"execution","summary":"HL.SB.PCR covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_HL_SB_PCR();
    return 0;
end;
