// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SB-PCR-BOUND-001","source":"asl/scalar/agu/HL.SB.PCR.asl","requirements":["PTO-INST-SCALAR-HL-SB-PCR"],"kind":"boundary","summary":"HL.SB.PCR covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_SB_PCR();
    return 0;
end;
