// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-SETC-OR-BOUND-001","source":"asl/scalar/bru/SETC.OR.asl","requirements":["PTO-INST-SCALAR-SETC-OR"],"kind":"boundary","summary":"SETC.OR covers operand selectors, immediates, conditions, targets, and faults","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUBounds_SETC_OR();
    return 0;
end;
