// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TXORS-STATIC-INVARIANT-001","source":"asl/tile/tile-scalar-elementwise/logical/TXORS.asl","requirements":["PTO-INST-TILE-TXORS"],"kind":"static-invariant","summary":"canonical TXORS catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: tile-scalar-elementwise/logical
    // block: BSTART.TEPL TXORS, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | B.IOR | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000101000') == 32;
    assert TileOperationOfIndex(32) == TileOperation_TXORS;
    assert TileHandlerOfIndex(32) == TileHandler_ExecuteTileScalar;
    assert InstructionContractOperation_TXORS() == TileOperation_TXORS;
    assert InstructionContractHandler_TXORS() == TileHandler_ExecuteTileScalar;
    return 0;
end;
