// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TAND-STATIC-INVARIANT-001","source":"asl/tile/tile-tile-elementwise/logical/TAND.asl","requirements":["PTO-INST-TILE-TAND"],"kind":"static-invariant","summary":"canonical TAND catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: tile-tile-elementwise/logical
    // block: BSTART.TEPL TAND, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000000110') == 5;
    assert TileOperationOfIndex(5) == TileOperation_TAND;
    assert TileHandlerOfIndex(5) == TileHandler_ExecuteTileBinary;
    assert InstructionContractOperation_TAND() == TileOperation_TAND;
    assert InstructionContractHandler_TAND() == TileHandler_ExecuteTileBinary;
    return 0;
end;
