// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FLTS-DST-001","source":"asl/scalar/fsu/FLTS.asl","requirements":["PTO-INST-SCALAR-FLTS"],"kind":"execution","summary":"FLTS covers discard, reserved-discard, GPR, and temporary-queue destinations","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUAliasDestination_FLTS();
    return 0;
end;
