// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FLTS-FLAGS-001","source":"asl/scalar/fsu/FLTS.asl","requirements":["PTO-INST-SCALAR-FLTS"],"kind":"state-transition","summary":"FLTS covers sticky floating-point exception-flag accumulation","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUFlags_FLTS();
    return 0;
end;
