// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FDIV-FLAGS-001","source":"asl/scalar/fsu/FDIV.asl","requirements":["PTO-INST-SCALAR-FDIV"],"kind":"state-transition","summary":"FDIV covers sticky floating-point exception-flag accumulation","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUFlags_FDIV();
    return 0;
end;
