// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FDIV-SRC-001","source":"asl/scalar/fsu/FDIV.asl","requirements":["PTO-INST-SCALAR-FDIV"],"kind":"execution","summary":"FDIV covers absolute and temporary-queue source selectors and aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUAliasSources_FDIV();
    return 0;
end;
