// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FCVTM-BOUND-001","source":"asl/scalar/fsu/FCVTM.asl","requirements":["PTO-INST-SCALAR-FCVTM"],"kind":"boundary","summary":"FCVTM covers finite zeros, signed values, and extrema","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUBounds_FCVTM();
    return 0;
end;
