// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FCVTM-RSVD-001","source":"asl/scalar/fsu/FCVTM.asl","requirements":["PTO-INST-SCALAR-FCVTM"],"kind":"fault","summary":"FCVTM rejects reserved data-type encodings before architectural effects","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUTypesReserved_FCVTM();
    return 0;
end;
