// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-PROFILE-FUNCTIONAL-MODEL-STATIC-001","source":"asl/arch/profile/functional-model.asl","requirements":["PTO-REQ-FUNCTIONAL-PROFILE-IDENTITY-001"],"kind":"static-invariant","summary":"PTO-ARCH-PROFILE-FUNCTIONAL-MODEL compiles as a non-architectural model harness unit","pass_condition":"the complete PTO model and this model-harness static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
