// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TLOAD-STATIC-INVARIANT-001","source":"asl/tile/memory/regular/TLOAD.asl","requirements":["PTO-INST-TILE-TLOAD"],"kind":"static-invariant","summary":"canonical TLOAD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory/regular
    // block: # Local form | BSTART.TLSU TLOAD | B.DATR/B.DIM | B.IOT | B.IOR | BSTOP | # Shared form | BSTART.TLSU TLOAD | B.DATR/B.DIM | B.IOS | B.IOR | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000000000') == 87;
    assert TileOperationOfIndex(87) == TileOperation_TLOAD;
    assert TileHandlerOfIndex(87) == TileHandler_TLOAD;
    assert InstructionContractOperation_TLOAD() == TileOperation_TLOAD;
    assert InstructionContractHandler_TLOAD() == TileHandler_TLOAD;
    return 0;
end;
