// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-ICALL-DECODE-001","source":"asl/block/execution/BSTART.ICALL.asl","requirements":["PTO-INST-BLOCK-BSTART-ICALL"],"kind":"decode-positive","summary":"canonical BSTART.ICALL catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000001010000000101100110000000000001', 32) == 16;
    assert CommandOperationOfForm(16) == CommandOperation_bstart_icall_32_50166001;
    assert CommandHandlerOfForm(16) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_BSTART_ICALL(CommandOperationOfForm(16));
    assert InstructionContractHandler_BSTART_ICALL() == CommandHandler_ExecuteBundleStart;
    return 0;
end;
