// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-TMATMUL-BIAS-DECODE-001","source":"asl/block/execution/BSTART.TMATMUL.BIAS.asl","requirements":["PTO-INST-BLOCK-BSTART-TMATMUL-BIAS"],"kind":"decode-positive","summary":"canonical BSTART.TMATMUL.BIAS catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000000000100110001000110000001', 32) == 49;
    assert CommandOperationOfForm(49) == CommandOperation_bstart_tmatmul_bias_32_4d5a498d12f3;
    assert CommandHandlerOfForm(49) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_BSTART_TMATMUL_BIAS(CommandOperationOfForm(49));
    assert InstructionContractHandler_BSTART_TMATMUL_BIAS() == CommandHandler_ExecuteBundleStart;
    return 0;
end;
