// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TROWEXPANDADD-STATIC-INVARIANT-001","source":"asl/tile/vector-tile-expansion/row-expansion/TROWEXPANDADD.asl","requirements":["PTO-INST-TILE-TROWEXPANDADD"],"kind":"static-invariant","summary":"canonical TROWEXPANDADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: vector-tile-expansion/row-expansion
    // block: BSTART.TEPL TROWEXPANDADD, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001000101') == 45;
    assert TileOperationOfIndex(45) == TileOperation_TROWEXPANDADD;
    assert TileHandlerOfIndex(45) == TileHandler_ExecuteTileExpand;
    assert InstructionContractOperation_TROWEXPANDADD() == TileOperation_TROWEXPANDADD;
    assert InstructionContractHandler_TROWEXPANDADD() == TileHandler_ExecuteTileExpand;
    return 0;
end;
