// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LHU-PO-BOUND-001","source":"asl/scalar/agu/HL.LHU.PO.asl","requirements":["PTO-INST-SCALAR-HL-LHU-PO"],"kind":"boundary","summary":"HL.LHU.PO covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_LHU_PO();
    return 0;
end;
