// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SB-ALIAS-001","source":"asl/scalar/agu/SB.asl","requirements":["PTO-INST-SCALAR-SB"],"kind":"execution","summary":"SB covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_SB();
    return 0;
end;
