// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SD-U-EXEC-001","source":"asl/scalar/agu/SD.U.asl","requirements":["PTO-INST-SCALAR-SD-U"],"kind":"execution","summary":"SD.U executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_SD_U();
    return 0;
end;
