// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SD-U-ALIAS-001","source":"asl/scalar/agu/SD.U.asl","requirements":["PTO-INST-SCALAR-SD-U"],"kind":"execution","summary":"SD.U covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_SD_U();
    return 0;
end;
