// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TSHR-STATIC-INVARIANT-001","source":"asl/tile/elementwise-tile-tile/logical/TSHR.asl","requirements":["PTO-INST-TILE-TSHR"],"kind":"static-invariant","summary":"canonical TSHR catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: elementwise-tile-tile/logical
    // block: BSTART.VEC TSHR, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000001010') == 9;
    assert TileOperationOfIndex(9) == TileOperation_TSHR;
    assert TileHandlerOfIndex(9) == TileHandler_ExecuteTileBinary;
    assert TileClassOfIndex(9) == TileClass_ElementwiseTileTile;
    assert TileEngineOfIndex(9) == TileEngine_VEC;
    assert InstructionContractOperation_TSHR() == TileOperation_TSHR;
    assert InstructionContractHandler_TSHR() == TileHandler_ExecuteTileBinary;
    return 0;
end;
