// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-SRLW-DECODE-001","source":"asl/scalar/alu/SRLW.asl","requirements":["PTO-INST-SCALAR-SRLW"],"kind":"decode-positive","summary":"canonical SRLW catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000101000000100101', 32) == 432;
    assert ScalarOperationOfForm(432) == ScalarOperation_SRLW;
    assert ScalarHandlerOfForm(432) == ScalarHandler_ScalarBinaryW;
    assert InstructionContractOperation_SRLW() == ScalarOperation_SRLW;
    assert InstructionContractHandler_SRLW() == ScalarHandler_ScalarBinaryW;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000000100101', 432, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000000100101', 432, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000000100101', 432, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
