// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SD-UPR-EXEC-001","source":"asl/scalar/agu/HL.SD.UPR.asl","requirements":["PTO-INST-SCALAR-HL-SD-UPR"],"kind":"execution","summary":"HL.SD.UPR executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_SD_UPR();
    return 0;
end;
