// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TNEG-STATIC-001","source":"asl/tile/elementwise-tile-tile/logical/TNEG.asl","requirements":["PTO-INST-TILE-TNEG"],"kind":"static-invariant","summary":"canonical TNEG catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: elementwise-tile-tile/logical
    // block: BSTART.VEC TNEG, DataType | B.DATR PadValue (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT Src, mask=PE_MASK, <last>, ->DstTile<TSize> | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000010001') == 15;
    assert TileOperationOfIndex(15) == TileOperation_TNEG;
    assert TileHandlerOfIndex(15) == TileHandler_ExecuteTileUnary;
    assert TileClassOfIndex(15) == TileClass_ElementwiseTileTile;
    assert TileEngineOfIndex(15) == TileEngine_VEC;
    assert InstructionContractOperation_TNEG() == TileOperation_TNEG;
    assert InstructionContractHandler_TNEG() == TileHandler_ExecuteTileUnary;
    return 0;
end;
