// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-PROFILE-MATRIX-QUANTIZATION-STATIC-001","source":"asl/arch/profile/matrix-quantization.asl","requirements":["PTO-MATRIX-QUANT-BITEXACT-001"],"kind":"static-invariant","summary":"PTO-ARCH-PROFILE-MATRIX-QUANTIZATION compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
