// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-LHP-DECODE-001","source":"asl/scalar/agu/HL.LHP.asl","requirements":["PTO-INST-SCALAR-HL-LHP"],"kind":"decode-positive","summary":"canonical HL.LHP catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000010000000010010000000000011110', 48) == 180;
    assert ScalarOperationOfForm(180) == ScalarOperation_HL_LHP;
    assert ScalarHandlerOfForm(180) == ScalarHandler_ExecuteScalarLoadPair;
    assert InstructionContractOperation_HL_LHP() == ScalarOperation_HL_LHP;
    assert InstructionContractHandler_HL_LHP() == ScalarHandler_ExecuteScalarLoadPair;
    assert InstructionContractAGUAction_HL_LHP() == ScalarAGU_LoadPair;
    assert InstructionContractAGUAddressKind_HL_LHP() == ScalarAGU_Register;
    assert InstructionContractAGUSizeBytes_HL_LHP() == 2;
    assert InstructionContractAGUOffsetScale_HL_LHP() == 0;
    assert InstructionContractAGUUpdateMode_HL_LHP() == AddressUpdate_None;
    assert InstructionContractAGUSignedLoad_HL_LHP() == TRUE;
    assert InstructionContractAGUPrefetchReturnsAddress_HL_LHP() == FALSE;
    assert DecodeScalarOperandRaw('000000000000000000010000000010010000000000011110', 180, ScalarField_RegDst0) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000010010000000000011110', 180, ScalarField_RegDst1) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000010010000000000011110', 180, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000010010000000000011110', 180, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000010010000000000011110', 180, ScalarField_SrcRType) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000010010000000000011110', 180, ScalarField_shamt) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
