// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-MODEL-MEMORY-WEIGHT-TO-SHARED-GM-STATIC-001","source":"asl/block/model/memory/weight-to-shared-gm.asl","requirements":["PTO-BSTART-TLOAD-WEIGHT-KORDER-001","PTO-BSTART-TLOAD-WEIGHT-DEFINEDNESS-001"],"kind":"static-invariant","summary":"PTO-BLOCK-MODEL-MEMORY-WEIGHT-TO-SHARED-GM compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
