// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LBI-ALIAS-001","source":"asl/scalar/agu/LBI.asl","requirements":["PTO-INST-SCALAR-LBI"],"kind":"execution","summary":"LBI covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_LBI();
    return 0;
end;
