// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-B-IOS-DECODE-001","source":"asl/block/operands/B.IOS.asl","requirements":["PTO-INST-BLOCK-B-IOS"],"kind":"decode-positive","summary":"canonical B.IOS catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000000000000000001000000010011', 32) == 58;
    assert CommandOperationOfForm(58) == CommandOperation_b_ios_32_4ba5ef98fdaa;
    assert CommandHandlerOfForm(58) == CommandHandler_BindBundleSharedIO;
    assert InstructionContractMatches_B_IOS(CommandOperationOfForm(58));
    assert InstructionContractHandler_B_IOS() == CommandHandler_BindBundleSharedIO;
    return 0;
end;
