// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TREM-STATIC-001","source":"asl/tile/elementwise-tile-tile/transcendental/TREM.asl","requirements":["PTO-INST-TILE-TREM"],"kind":"static-invariant","summary":"canonical TREM catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: elementwise-tile-tile/transcendental
    // block: BSTART.SFU TREM, DataType | B.DATR PadValue (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT Dividend, Divisor, mask=PE_MASK, <last>, ->DstTile<TSize> | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000000100') == 4;
    assert TileOperationOfIndex(4) == TileOperation_TREM;
    assert TileHandlerOfIndex(4) == TileHandler_ExecuteTileBinary;
    assert TileClassOfIndex(4) == TileClass_ElementwiseTileTile;
    assert TileEngineOfIndex(4) == TileEngine_SFU;
    assert InstructionContractOperation_TREM() == TileOperation_TREM;
    assert InstructionContractHandler_TREM() == TileHandler_ExecuteTileBinary;
    return 0;
end;
