// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TOR-STATIC-INVARIANT-001","source":"asl/tile/elementwise-tile-tile/logical/TOR.asl","requirements":["PTO-INST-TILE-TOR"],"kind":"static-invariant","summary":"canonical TOR catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: elementwise-tile-tile/logical
    // block: BSTART.VEC TOR, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000000111') == 6;
    assert TileOperationOfIndex(6) == TileOperation_TOR;
    assert TileHandlerOfIndex(6) == TileHandler_ExecuteTileBinary;
    assert TileClassOfIndex(6) == TileClass_ElementwiseTileTile;
    assert TileEngineOfIndex(6) == TileEngine_VEC;
    assert InstructionContractOperation_TOR() == TileOperation_TOR;
    assert InstructionContractHandler_TOR() == TileHandler_ExecuteTileBinary;
    return 0;
end;
