// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LWI-U-EXEC-001","source":"asl/scalar/agu/LWI.U.asl","requirements":["PTO-INST-SCALAR-LWI-U"],"kind":"execution","summary":"LWI.U executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_LWI_U();
    return 0;
end;
