// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-FCVT-DECODE-001","source":"asl/scalar/fsu/FCVT.asl","requirements":["PTO-INST-SCALAR-FCVT"],"kind":"decode-positive","summary":"canonical FCVT catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000000000001101011', 32) == 89;
    assert ScalarOperationOfForm(89) == ScalarOperation_FCVT;
    assert ScalarHandlerOfForm(89) == ScalarHandler_ConvertFloatingEncoding;
    assert InstructionContractOperation_FCVT() == ScalarOperation_FCVT;
    assert InstructionContractHandler_FCVT() == ScalarHandler_ConvertFloatingEncoding;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000001101011', 89, ScalarField_DstType) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000001101011', 89, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000001101011', 89, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000001101011', 89, ScalarField_SrcType) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
