// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-FABS-DECODE-001","source":"asl/scalar/fsu/FABS.asl","requirements":["PTO-INST-SCALAR-FABS"],"kind":"decode-positive","summary":"canonical FABS catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000000000001111011', 32) == 87;
    assert ScalarOperationOfForm(87) == ScalarOperation_FABS;
    assert ScalarHandlerOfForm(87) == ScalarHandler_FloatingUnary;
    assert InstructionContractOperation_FABS() == ScalarOperation_FABS;
    assert InstructionContractHandler_FABS() == ScalarHandler_FloatingUnary;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000001111011', 87, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000001111011', 87, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000001111011', 87, ScalarField_SrcType) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
