// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TGEMV-MX-ACC-STATIC-INVARIANT-001","source":"asl/tile/matrix-and-matrix-vector/matrix-vector/TGEMV_MX_ACC.asl","requirements":["PTO-INST-TILE-TGEMV-MX-ACC"],"kind":"static-invariant","summary":"canonical TGEMV_MX_ACC catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: matrix-and-matrix-vector/matrix-vector
    // block: BSTART.CUBE TGEMVMX.ACC AType | B.DATR BType RMode Sat | B.FPATR | B.DIM LB0 N | B.DIM LB1 M | B.DIM LB2 Col | B.IOT Local sources and Local outputs | B.IOR scalar PostProcess parameter (optional) | BSTOP
    assert DecodeTileOperation(TileDecode_CUBE, '000000010110') == 108;
    assert TileOperationOfIndex(108) == TileOperation_TGEMV_MX_ACC;
    assert TileHandlerOfIndex(108) == TileHandler_TGEMV_MX_ACC;
    assert TileClassOfIndex(108) == TileClass_MatrixAndMatrixVector;
    assert TileEngineOfIndex(108) == TileEngine_CUBE;
    assert InstructionContractOperation_TGEMV_MX_ACC() == TileOperation_TGEMV_MX_ACC;
    assert InstructionContractHandler_TGEMV_MX_ACC() == TileHandler_TGEMV_MX_ACC;
    return 0;
end;
