// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TDIV-STATIC-001","source":"asl/tile/elementwise-tile-tile/transcendental/TDIV.asl","requirements":["PTO-INST-TILE-TDIV"],"kind":"static-invariant","summary":"canonical TDIV catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: elementwise-tile-tile/transcendental
    // block: BSTART.SFU TDIV, DataType | B.DATR PadValue (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT Numerator, Denominator, mask=PE_MASK, <last>, ->DstTile<TSize> | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000000011') == 3;
    assert TileOperationOfIndex(3) == TileOperation_TDIV;
    assert TileHandlerOfIndex(3) == TileHandler_ExecuteTileBinary;
    assert TileClassOfIndex(3) == TileClass_ElementwiseTileTile;
    assert TileEngineOfIndex(3) == TileEngine_SFU;
    assert InstructionContractOperation_TDIV() == TileOperation_TDIV;
    assert InstructionContractHandler_TDIV() == TileHandler_ExecuteTileBinary;
    return 0;
end;
