// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-ATOM-OR-STATIC-001","source":"asl/tile/memory-and-data-movement/irregular/ATOM_OR.asl","requirements":["PTO-INST-TILE-ATOM-OR"],"kind":"static-invariant","summary":"canonical ATOM_OR catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory-and-data-movement/irregular
    // block: BSTART.ATOM.OR DataType | B.IOT IndexTile, ValueTile, mask=PE_MASK, <last>, ->DstTile<TSize> | B.IOR BaseGPR, zero, zero, ->zero | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000010001') == 114;
    assert TileOperationOfIndex(114) == TileOperation_ATOM_OR;
    assert TileHandlerOfIndex(114) == TileHandler_GM_ATOM_VALUE;
    assert TileClassOfIndex(114) == TileClass_MemoryAndDataMovement;
    assert TileEngineOfIndex(114) == TileEngine_TLSU;
    assert InstructionContractOperation_ATOM_OR() == TileOperation_ATOM_OR;
    assert InstructionContractHandler_ATOM_OR() == TileHandler_GM_ATOM_VALUE;
    return 0;
end;
