// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TSORT-STATIC-INVARIANT-001","source":"asl/tile/complex-layout/sorting/TSORT.asl","requirements":["PTO-INST-TILE-TSORT"],"kind":"static-invariant","summary":"canonical TSORT catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: complex-layout/sorting
    // block: BSTART.TEPL TSORT, DataType | B.DIM sort_width -> LB0 | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001101100') == 78;
    assert TileOperationOfIndex(78) == TileOperation_TSORT;
    assert TileHandlerOfIndex(78) == TileHandler_TSORT;
    assert InstructionContractOperation_TSORT() == TileOperation_TSORT;
    assert InstructionContractHandler_TSORT() == TileHandler_TSORT;
    return 0;
end;
