// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-TMATMULMX-ACC-DECODE-001","source":"asl/block/execution/BSTART.TMATMULMX.ACC.asl","requirements":["PTO-INST-BLOCK-BSTART-TMATMULMX-ACC"],"kind":"decode-positive","summary":"canonical BSTART.TMATMULMX.ACC catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000000011000110001000110000001', 32) == 51;
    assert CommandOperationOfForm(51) == CommandOperation_bstart_tmatmulmx_acc_32_70fa59b0ab4c;
    assert CommandHandlerOfForm(51) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_BSTART_TMATMULMX_ACC(CommandOperationOfForm(51));
    assert InstructionContractHandler_BSTART_TMATMULMX_ACC() == CommandHandler_ExecuteBundleStart;
    return 0;
end;
