// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FNMADD-BOUND-001","source":"asl/scalar/fsu/FNMADD.asl","requirements":["PTO-INST-SCALAR-FNMADD"],"kind":"boundary","summary":"FNMADD covers zeros, infinities, NaNs, extrema, and signed carriers","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUBounds_FNMADD();
    return 0;
end;
