// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FNMADD-FLAGS-001","source":"asl/scalar/fsu/FNMADD.asl","requirements":["PTO-INST-SCALAR-FNMADD"],"kind":"state-transition","summary":"FNMADD covers sticky floating-point exception-flag accumulation","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUFlags_FNMADD();
    return 0;
end;
