// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-B-LTU-BOUND-001","source":"asl/scalar/bru/B.LTU.asl","requirements":["PTO-INST-SCALAR-B-LTU"],"kind":"boundary","summary":"B.LTU covers operand selectors, immediates, conditions, targets, and faults","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUBounds_B_LTU();
    return 0;
end;
