// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FSUB-FLAGS-001","source":"asl/scalar/fsu/FSUB.asl","requirements":["PTO-INST-SCALAR-FSUB"],"kind":"state-transition","summary":"FSUB covers sticky floating-point exception-flag accumulation","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUFlags_FSUB();
    return 0;
end;
