// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-ANDI-DECODE-001","source":"asl/scalar/alu/HL.ANDI.asl","requirements":["PTO-INST-SCALAR-HL-ANDI"],"kind":"decode-positive","summary":"canonical HL.ANDI catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000100000000101010000000000001110', 48) == 128;
    assert ScalarOperationOfForm(128) == ScalarOperation_HL_ANDI;
    assert ScalarHandlerOfForm(128) == ScalarHandler_ScalarBinary;
    assert InstructionContractOperation_HL_ANDI() == ScalarOperation_HL_ANDI;
    assert InstructionContractHandler_HL_ANDI() == ScalarHandler_ScalarBinary;
    assert DecodeScalarOperandRaw('000000000000000000100000000101010000000000001110', 128, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000100000000101010000000000001110', 128, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000100000000101010000000000001110', 128, ScalarField_simm24) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
