// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SWIP-U-FAULT-001","source":"asl/scalar/agu/HL.SWIP.U.asl","requirements":["PTO-INST-SCALAR-HL-SWIP-U"],"kind":"fault","summary":"HL.SWIP.U rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_HL_SWIP_U();
    return 0;
end;
