// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-SWI-PO-DECODE-001","source":"asl/scalar/agu/HL.SWI.PO.asl","requirements":["PTO-INST-SCALAR-HL-SWI-PO"],"kind":"decode-positive","summary":"canonical HL.SWI.PO catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000100000010110010000000000111110', 48) == 301;
    assert ScalarOperationOfForm(301) == ScalarOperation_HL_SWI_PO;
    assert ScalarHandlerOfForm(301) == ScalarHandler_ExecuteScalarStore;
    assert InstructionContractOperation_HL_SWI_PO() == ScalarOperation_HL_SWI_PO;
    assert InstructionContractHandler_HL_SWI_PO() == ScalarHandler_ExecuteScalarStore;
    assert InstructionContractAGUAction_HL_SWI_PO() == ScalarAGU_Store;
    assert InstructionContractAGUAddressKind_HL_SWI_PO() == ScalarAGU_Immediate;
    assert InstructionContractAGUSizeBytes_HL_SWI_PO() == 4;
    assert InstructionContractAGUOffsetScale_HL_SWI_PO() == 2;
    assert InstructionContractAGUUpdateMode_HL_SWI_PO() == AddressUpdate_PostIndex;
    assert InstructionContractAGUSignedLoad_HL_SWI_PO() == FALSE;
    assert InstructionContractAGUPrefetchReturnsAddress_HL_SWI_PO() == FALSE;
    assert DecodeScalarOperandRaw('000000000000000000100000010110010000000000111110', 301, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000100000010110010000000000111110', 301, ScalarField_SrcD) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000100000010110010000000000111110', 301, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000100000010110010000000000111110', 301, ScalarField_simm17) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
