// PTO-UNIT: {"id":"PTO-ARCH-DATA-TYPES-TRAP-CONTEXT","surface":"arch","classification":["data-types","trap-context"],"depends_on":["PTO-TILE-MODEL-STATE-TYPES"]}
type TrapContext of record {
    valid: boolean,
    source_acr: AccessControlRing,
    tpc: Word,
    bpc: Word,
    core_state: Word,
    bundle_argument: Word,
    commit_argument: Word,
    bundle_active: boolean,
    bundle_body_active: boolean,
    bundle_kind: BundleKind,
    bundle_transfer: BundleTransfer,
    bundle_condition: boolean,
    bundle_target: Word,
    bundle_fallthrough: Word,
    bundle_return_target: Word,
    return_address: Word,
    bundle_argument_kind: bits(3),
    bundle_body_address: Word,
    bundle_operation: BundleOperationDescriptor,
    bundle_dimensions: BundleDimensionSnapshot,
    bundle_scalar_bindings: BundleScalarBindingSnapshot,
    bundle_tile_bindings: BundleTileBindingSnapshot,
    bundle_shared_bindings: BundleSharedBindingSnapshot,
    bundle_control_attributes: BundleControlAttributes,
    bundle_data_attributes: BundleDataAttributes,
    t_queue: TemporaryQueueSnapshot,
    u_queue: TemporaryQueueSnapshot,
    execution_mask: Word,
    predicates: PredicateSnapshot
};
