// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SH-PCR-EXEC-001","source":"asl/scalar/agu/SH.PCR.asl","requirements":["PTO-INST-SCALAR-SH-PCR"],"kind":"execution","summary":"SH.PCR executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_SH_PCR();
    return 0;
end;
