// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-HL-QMT-DECODE-001","source":"asl/block/lifecycle/HL.QMT.asl","requirements":["PTO-INST-BLOCK-HL-QMT"],"kind":"decode-positive","summary":"canonical HL.QMT catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000000011111010000000000001110', 48) == 84;
    assert CommandOperationOfForm(84) == CommandOperation_hl_qmt_48_eb9e41958045;
    assert CommandHandlerOfForm(84) == CommandHandler_ExecuteQueueMove;
    assert InstructionContractMatches_HL_QMT(CommandOperationOfForm(84));
    assert InstructionContractHandler_HL_QMT() == CommandHandler_ExecuteQueueMove;
    return 0;
end;
