// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-ATOM-AND-DECODE-001","source":"asl/block/execution/BSTART.ATOM.AND.asl","requirements":["PTO-INST-BLOCK-BSTART-ATOM-AND"],"kind":"decode-positive","summary":"canonical BSTART.ATOM.AND catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000001000000010001000110000001', 32) == 82;
    assert CommandOperationOfForm(82) == CommandOperation_bstart_atom_and_32_gm16;
    assert CommandHandlerOfForm(82) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_BSTART_ATOM_AND(CommandOperationOfForm(82));
    assert InstructionContractHandler_BSTART_ATOM_AND() == CommandHandler_ExecuteBundleStart;
    return 0;
end;
