// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SDI-U-BOUND-001","source":"asl/scalar/agu/SDI.U.asl","requirements":["PTO-INST-SCALAR-SDI-U"],"kind":"boundary","summary":"SDI.U covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_SDI_U();
    return 0;
end;
