// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SDI-U-FAULT-001","source":"asl/scalar/agu/SDI.U.asl","requirements":["PTO-INST-SCALAR-SDI-U"],"kind":"fault","summary":"SDI.U rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_SDI_U();
    return 0;
end;
