// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SDI-U-EXEC-001","source":"asl/scalar/agu/SDI.U.asl","requirements":["PTO-INST-SCALAR-SDI-U"],"kind":"execution","summary":"SDI.U executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_SDI_U();
    return 0;
end;
