// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LWUIP-U-BOUND-001","source":"asl/scalar/agu/HL.LWUIP.U.asl","requirements":["PTO-INST-SCALAR-HL-LWUIP-U"],"kind":"boundary","summary":"HL.LWUIP.U covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_LWUIP_U();
    return 0;
end;
