// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-MSCATTER-OR-SEMANTIC-001","source":"asl/block/execution/BSTART.MSCATTER.OR.asl","requirements":["PTO-INST-BLOCK-BSTART-MSCATTER-OR"],"kind":"execution","summary":"BSTART.MSCATTER.OR exercises its GM semantic primitive at the owner boundary","pass_condition":"the decoded owner mapping and representative GM effect assertions hold","related_sources":["asl/tile/model/memory/gm-atom-red.asl","asl/tile/model/memory/gm-atom-red-execution.asl"]}
func main() => integer
begin
    assert GMReductionOperationFromFunction(25) == GMReduction_OR;
    assert GMReductionOperationDataTypeLegal(GMReduction_OR, TileDataType_U32);
    assert GMReductionResult(GMReduction_OR, TileDataType_U32,
        Zeros{PTO_XLEN} + 3, Zeros{PTO_XLEN} + 5) ==
        Zeros{PTO_XLEN} + 0xFF;
    return 0;
end;
