// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LDI-U-FAULT-001","source":"asl/scalar/agu/LDI.U.asl","requirements":["PTO-INST-SCALAR-LDI-U"],"kind":"fault","summary":"LDI.U rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_LDI_U();
    return 0;
end;
