// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-SW-PCR-DECODE-001","source":"asl/scalar/agu/HL.SW.PCR.asl","requirements":["PTO-INST-SCALAR-HL-SW-PCR"],"kind":"decode-positive","summary":"canonical HL.SW.PCR catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000100000011010010000000000001110', 48) == 295;
    assert ScalarOperationOfForm(295) == ScalarOperation_HL_SW_PCR;
    assert ScalarHandlerOfForm(295) == ScalarHandler_ExecuteScalarStore;
    assert InstructionContractOperation_HL_SW_PCR() == ScalarOperation_HL_SW_PCR;
    assert InstructionContractHandler_HL_SW_PCR() == ScalarHandler_ExecuteScalarStore;
    assert InstructionContractAGUAction_HL_SW_PCR() == ScalarAGU_Store;
    assert InstructionContractAGUAddressKind_HL_SW_PCR() == ScalarAGU_PCRelative;
    assert InstructionContractAGUSizeBytes_HL_SW_PCR() == 4;
    assert InstructionContractAGUOffsetScale_HL_SW_PCR() == 2;
    assert InstructionContractAGUUpdateMode_HL_SW_PCR() == AddressUpdate_None;
    assert InstructionContractAGUSignedLoad_HL_SW_PCR() == FALSE;
    assert InstructionContractAGUPrefetchReturnsAddress_HL_SW_PCR() == FALSE;
    assert DecodeScalarOperandRaw('000000000000000000100000011010010000000000001110', 295, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000100000011010010000000000001110', 295, ScalarField_simm) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
