// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TMIN-STATIC-001","source":"asl/tile/elementwise-tile-tile/arithmetic/TMIN.asl","requirements":["PTO-INST-TILE-TMIN"],"kind":"static-invariant","summary":"canonical TMIN catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: elementwise-tile-tile/arithmetic
    // block: BSTART.VEC TMIN, DataType | B.DATR PadValue (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT SrcLeft, SrcRight, mask=PE_MASK, <last>, ->DstTile<TSize> | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000001100') == 11;
    assert TileOperationOfIndex(11) == TileOperation_TMIN;
    assert TileHandlerOfIndex(11) == TileHandler_ExecuteTileBinary;
    assert TileClassOfIndex(11) == TileClass_ElementwiseTileTile;
    assert TileEngineOfIndex(11) == TileEngine_VEC;
    assert InstructionContractOperation_TMIN() == TileOperation_TMIN;
    assert InstructionContractHandler_TMIN() == TileHandler_ExecuteTileBinary;
    return 0;
end;
