// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SBI-FAULT-001","source":"asl/scalar/agu/SBI.asl","requirements":["PTO-INST-SCALAR-SBI"],"kind":"fault","summary":"SBI rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_SBI();
    return 0;
end;
