// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SYS-HL-SSRSET-PLACE-001","source":"asl/scalar/sys/HL.SSRSET.asl","requirements":["PTO-INST-SCALAR-HL-SSRSET"],"kind":"fault","summary":"HL.SSRSET proves its place SYS contract","pass_condition":"the mnemonic-owned decoded assertions hold","related_sources":[]}
func main() => integer
begin
    ResetProfileState();
    WriteTPC(Zeros{PTO_XLEN} + 0x100);
    WriteGPR(3, Zeros{PTO_XLEN} + 0x333);
    WriteGPR(5, Zeros{PTO_XLEN} + 0x555);
    _DataCacheEpoch = 7;
    _ArchitectureRequestEpoch = 9;
    let status = ExecuteScalarInstruction('000000000000001010010000001110110000000000001110', 48);
    assert status == ScalarExecution_Rejected;
    assert _LastFault == Fault_BundleControl;
    assert ReadGPR(3) == Zeros{PTO_XLEN} + 0x333;
    assert ReadGPR(5) == Zeros{PTO_XLEN} + 0x555;
    assert _DataCacheEpoch == 7;
    assert _ArchitectureRequestEpoch == 9;
    return 0;
end;
