// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-MSCATTER-ADD-DECODE-001","source":"asl/block/execution/BSTART.MSCATTER.ADD.asl","requirements":["PTO-INST-BLOCK-BSTART-MSCATTER-ADD"],"kind":"decode-positive","summary":"canonical BSTART.MSCATTER.ADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000001010100010001000110000001', 32) == 87;
    assert CommandOperationOfForm(87) == CommandOperation_bstart_mscatter_add_32_gm21;
    assert CommandHandlerOfForm(87) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_BSTART_MSCATTER_ADD(CommandOperationOfForm(87));
    assert InstructionContractHandler_BSTART_MSCATTER_ADD() == CommandHandler_ExecuteBundleStart;
    return 0;
end;
