// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-TLOAD-DECODE-001","source":"asl/block/execution/BSTART.TLOAD.asl","requirements":["PTO-INST-BLOCK-BSTART-TLOAD"],"kind":"decode-positive","summary":"canonical BSTART.TLOAD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000000000000010001000110000001', 32) == 46;
    assert CommandOperationOfForm(46) == CommandOperation_bstart_tload_32_d0c18bb0ab15;
    assert CommandHandlerOfForm(46) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_BSTART_TLOAD(CommandOperationOfForm(46));
    assert InstructionContractHandler_BSTART_TLOAD() == CommandHandler_ExecuteBundleStart;
    return 0;
end;
