// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-C-SDI-FAULT-001","source":"asl/scalar/agu/C.SDI.asl","requirements":["PTO-INST-SCALAR-C-SDI"],"kind":"fault","summary":"C.SDI rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_C_SDI();
    return 0;
end;
