// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-LD-SMAX-DECODE-001","source":"asl/scalar/amo/LD.SMAX.asl","requirements":["PTO-INST-SCALAR-LD-SMAX"],"kind":"decode-positive","summary":"canonical LD.SMAX catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000001000000000000000100000000001011', 32) == 327;
    assert ScalarOperationOfForm(327) == ScalarOperation_LD_SMAX;
    assert ScalarHandlerOfForm(327) == ScalarHandler_AtomicReadModifyWrite;
    assert InstructionContractOperation_LD_SMAX() == ScalarOperation_LD_SMAX;
    assert InstructionContractHandler_LD_SMAX() == ScalarHandler_AtomicReadModifyWrite;
    assert DecodeScalarOperandRaw('000000000000000001000000000000000100000000001011', 327, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001000000000000000100000000001011', 327, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001000000000000000100000000001011', 327, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001000000000000000100000000001011', 327, ScalarField_aq) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001000000000000000100000000001011', 327, ScalarField_far) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001000000000000000100000000001011', 327, ScalarField_rl) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
