// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FEQS-BOUND-001","source":"asl/scalar/fsu/FEQS.asl","requirements":["PTO-INST-SCALAR-FEQS"],"kind":"boundary","summary":"FEQS covers zeros, infinities, NaNs, extrema, and signed carriers","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUBounds_FEQS();
    return 0;
end;
