// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FEQS-TYPE-001","source":"asl/scalar/fsu/FEQS.asl","requirements":["PTO-INST-SCALAR-FEQS"],"kind":"boundary","summary":"FEQS covers every assigned source and destination data-type encoding","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUTypesLegal_FEQS();
    return 0;
end;
