// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-RED-POPC-STATIC-001","source":"asl/tile/memory-and-data-movement/irregular/RED_POPC.asl","requirements":["PTO-INST-TILE-RED-POPC"],"kind":"static-invariant","summary":"canonical RED_POPC catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory-and-data-movement/irregular
    // block: BSTART.RED.POPC DataType | B.IOT IndexTile, ValueTile, mask=PE_MASK, <last>, ->DstTile<TSize> | B.IOR BaseGPR, zero, zero, ->zero | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000011011') == 124;
    assert TileOperationOfIndex(124) == TileOperation_RED_POPC;
    assert TileHandlerOfIndex(124) == TileHandler_GM_RED_POPC;
    assert TileClassOfIndex(124) == TileClass_MemoryAndDataMovement;
    assert TileEngineOfIndex(124) == TileEngine_TLSU;
    assert InstructionContractOperation_RED_POPC() == TileOperation_RED_POPC;
    assert InstructionContractHandler_RED_POPC() == TileHandler_GM_RED_POPC;
    return 0;
end;
