// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TFMA-STATIC-INVARIANT-001","source":"asl/tile/tile-tile-elementwise/arithmetic/TFMA.asl","requirements":["PTO-INST-TILE-TFMA"],"kind":"static-invariant","summary":"canonical TFMA catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: tile-tile-elementwise/arithmetic
    // block: BSTART.TEPL TFMA, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000011100') == 24;
    assert TileOperationOfIndex(24) == TileOperation_TFMA;
    assert TileHandlerOfIndex(24) == TileHandler_TFMA;
    assert InstructionContractOperation_TFMA() == TileOperation_TFMA;
    assert InstructionContractHandler_TFMA() == TileHandler_TFMA;
    return 0;
end;
