// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-DC-IVA-DECODE-001","source":"asl/scalar/sys/DC.IVA.asl","requirements":["PTO-INST-SCALAR-DC-IVA"],"kind":"decode-positive","summary":"canonical DC.IVA catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000110000000101011', 32) == 79;
    assert ScalarOperationOfForm(79) == ScalarOperation_DC_IVA;
    assert ScalarHandlerOfForm(79) == ScalarHandler_ExecuteMaintenance;
    assert InstructionContractOperation_DC_IVA() == ScalarOperation_DC_IVA;
    assert InstructionContractHandler_DC_IVA() == ScalarHandler_ExecuteMaintenance;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000110000000101011', 79, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
