// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SYS-ASSERT-USRC-001","source":"asl/scalar/sys/ASSERT.asl","requirements":["PTO-INST-SCALAR-ASSERT"],"kind":"execution","summary":"ASSERT proves its usrc SYS contract","pass_condition":"the mnemonic-owned decoded assertions hold","related_sources":[]}
func main() => integer
begin
    ResetProfileState();
    SetCurrentACR(0);
    WriteTPC(Zeros{PTO_XLEN} + 0x100);
    BeginBundle(BundleKind_System, BundleTransfer_Fallthrough,
        Zeros{PTO_XLEN}, Zeros{PTO_XLEN} + 0x180,
        Zeros{PTO_XLEN}, FALSE);
    EnterBundleBody();
    _UQueue[[0]] = Zeros{PTO_XLEN} + 0x1000;
    _UQueueValid[[0]] = TRUE;
    let status = ExecuteScalarInstruction('000000000000000000000000000011100001000000101011', 32);
    assert status == ScalarExecution_Executed;
    assert _LastFault == Fault_None;
    assert ReadTemporaryQueue(FALSE, 0) == Zeros{PTO_XLEN} + 0x1000;
    assert ReadTemporaryQueue(FALSE, 0) == Zeros{PTO_XLEN} + 0x1000;
    assert ReadTPC() == Zeros{PTO_XLEN} + 0x184;
    assert InstructionContractOperation_ASSERT() == ScalarOperation_ASSERT;
    return 0;
end;
