// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-ORIW-DECODE-001","source":"asl/scalar/alu/HL.ORIW.asl","requirements":["PTO-INST-SCALAR-HL-ORIW"],"kind":"decode-positive","summary":"canonical HL.ORIW catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000110000001101010000000000001110', 48) == 235;
    assert ScalarOperationOfForm(235) == ScalarOperation_HL_ORIW;
    assert ScalarHandlerOfForm(235) == ScalarHandler_ScalarBinaryW;
    assert InstructionContractOperation_HL_ORIW() == ScalarOperation_HL_ORIW;
    assert InstructionContractHandler_HL_ORIW() == ScalarHandler_ScalarBinaryW;
    assert DecodeScalarOperandRaw('000000000000000000110000001101010000000000001110', 235, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000110000001101010000000000001110', 235, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000110000001101010000000000001110', 235, ScalarField_simm24) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
