// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-RED-INC-STATIC-001","source":"asl/tile/memory-and-data-movement/irregular/RED_INC.asl","requirements":["PTO-INST-TILE-RED-INC"],"kind":"static-invariant","summary":"canonical RED_INC catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory-and-data-movement/irregular
    // block: BSTART.RED.INC DataType | B.IOT IndexTile, ValueTile, mask=PE_MASK, <last> | B.IOR BaseGPR, zero, zero, ->zero | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000010110') == 119;
    assert TileOperationOfIndex(119) == TileOperation_RED_INC;
    assert TileHandlerOfIndex(119) == TileHandler_GM_RED_VALUE;
    assert TileClassOfIndex(119) == TileClass_MemoryAndDataMovement;
    assert TileEngineOfIndex(119) == TileEngine_TLSU;
    assert InstructionContractOperation_RED_INC() == TileOperation_RED_INC;
    assert InstructionContractHandler_RED_INC() == TileHandler_GM_RED_VALUE;
    return 0;
end;
