// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LWI-U-EXEC-001","source":"asl/scalar/agu/HL.LWI.U.asl","requirements":["PTO-INST-SCALAR-HL-LWI-U"],"kind":"execution","summary":"HL.LWI.U executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_LWI_U();
    return 0;
end;
