// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-LHUI-U-DECODE-001","source":"asl/scalar/agu/LHUI.U.asl","requirements":["PTO-INST-SCALAR-LHUI-U"],"kind":"decode-positive","summary":"canonical LHUI.U catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000101000000101001', 32) == 341;
    assert ScalarOperationOfForm(341) == ScalarOperation_LHUI_U;
    assert ScalarHandlerOfForm(341) == ScalarHandler_ExecuteScalarLoad;
    assert InstructionContractOperation_LHUI_U() == ScalarOperation_LHUI_U;
    assert InstructionContractHandler_LHUI_U() == ScalarHandler_ExecuteScalarLoad;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000000101001', 341, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000000101001', 341, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000000101001', 341, ScalarField_simm12) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
