// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LHUI-U-ALIAS-001","source":"asl/scalar/agu/LHUI.U.asl","requirements":["PTO-INST-SCALAR-LHUI-U"],"kind":"execution","summary":"LHUI.U covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_LHUI_U();
    return 0;
end;
