// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LWI-UPR-BOUND-001","source":"asl/scalar/agu/HL.LWI.UPR.asl","requirements":["PTO-INST-SCALAR-HL-LWI-UPR"],"kind":"boundary","summary":"HL.LWI.UPR covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_LWI_UPR();
    return 0;
end;
