// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-CMP-GEU-EXEC-001","source":"asl/scalar/bru/CMP.GEU.asl","requirements":["PTO-INST-SCALAR-CMP-GEU"],"kind":"execution","summary":"CMP.GEU executes the canonical comparison, branch, jump, or control effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUExecute_CMP_GEU();
    return 0;
end;
