// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LWUI-BOUND-001","source":"asl/scalar/agu/HL.LWUI.asl","requirements":["PTO-INST-SCALAR-HL-LWUI"],"kind":"boundary","summary":"HL.LWUI covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_LWUI();
    return 0;
end;
