// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LWUI-EXEC-001","source":"asl/scalar/agu/HL.LWUI.asl","requirements":["PTO-INST-SCALAR-HL-LWUI"],"kind":"execution","summary":"HL.LWUI executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_LWUI();
    return 0;
end;
