// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LHUIP-EXEC-001","source":"asl/scalar/agu/HL.LHUIP.asl","requirements":["PTO-INST-SCALAR-HL-LHUIP"],"kind":"execution","summary":"HL.LHUIP executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_LHUIP();
    return 0;
end;
