// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-SH-PCR-DECODE-001","source":"asl/scalar/agu/HL.SH.PCR.asl","requirements":["PTO-INST-SCALAR-HL-SH-PCR"],"kind":"decode-positive","summary":"canonical HL.SH.PCR catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000010000011010010000000000001110', 48) == 276;
    assert ScalarOperationOfForm(276) == ScalarOperation_HL_SH_PCR;
    assert ScalarHandlerOfForm(276) == ScalarHandler_ExecuteScalarStore;
    assert InstructionContractOperation_HL_SH_PCR() == ScalarOperation_HL_SH_PCR;
    assert InstructionContractHandler_HL_SH_PCR() == ScalarHandler_ExecuteScalarStore;
    assert DecodeScalarOperandRaw('000000000000000000010000011010010000000000001110', 276, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000011010010000000000001110', 276, ScalarField_simm) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
