// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LWUI-PR-FAULT-001","source":"asl/scalar/agu/HL.LWUI.PR.asl","requirements":["PTO-INST-SCALAR-HL-LWUI-PR"],"kind":"fault","summary":"HL.LWUI.PR rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_HL_LWUI_PR();
    return 0;
end;
