// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TROWEXPANDEXPDIF-STATIC-INVARIANT-001","source":"asl/tile/reduce-and-expand/row-expansion/TROWEXPANDEXPDIF.asl","requirements":["PTO-INST-TILE-TROWEXPANDEXPDIF"],"kind":"static-invariant","summary":"canonical TROWEXPANDEXPDIF catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: reduce-and-expand/row-expansion
    // block: BSTART.SFU TROWEXPANDEXPDIF, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001001011') == 51;
    assert TileOperationOfIndex(51) == TileOperation_TROWEXPANDEXPDIF;
    assert TileHandlerOfIndex(51) == TileHandler_ExecuteTileExpand;
    assert TileClassOfIndex(51) == TileClass_ReduceAndExpand;
    assert TileEngineOfIndex(51) == TileEngine_SFU;
    assert InstructionContractOperation_TROWEXPANDEXPDIF() == TileOperation_TROWEXPANDEXPDIF;
    assert InstructionContractHandler_TROWEXPANDEXPDIF() == TileHandler_ExecuteTileExpand;
    return 0;
end;
