// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-PRF-FAULT-001","source":"asl/scalar/agu/PRF.asl","requirements":["PTO-INST-SCALAR-PRF"],"kind":"fault","summary":"PRF rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_PRF();
    return 0;
end;
