// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TMRGSORT-STATIC-INVARIANT-001","source":"asl/tile/complex-layout/sorting/TMRGSORT.asl","requirements":["PTO-INST-TILE-TMRGSORT"],"kind":"static-invariant","summary":"canonical TMRGSORT catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: complex-layout/sorting
    // block: BSTART.TEPL TMRGSORT, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | B.IOR | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001101101') == 79;
    assert TileOperationOfIndex(79) == TileOperation_TMRGSORT;
    assert TileHandlerOfIndex(79) == TileHandler_TMRGSORT;
    assert InstructionContractOperation_TMRGSORT() == TileOperation_TMRGSORT;
    assert InstructionContractHandler_TMRGSORT() == TileHandler_TMRGSORT;
    return 0;
end;
