// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-MODEL-DISPATCH-PARTIAL-SCHEMA-STATIC-001","source":"asl/block/model/dispatch/partial-schema.asl","requirements":[],"kind":"static-invariant","summary":"PTO-BLOCK-MODEL-DISPATCH-PARTIAL-SCHEMA compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
