// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-MIN-DECODE-001","source":"asl/scalar/alu/MIN.asl","requirements":["PTO-INST-SCALAR-MIN"],"kind":"decode-positive","summary":"canonical MIN catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000101000001011011', 32) == 360;
    assert ScalarOperationOfForm(360) == ScalarOperation_MIN;
    assert ScalarHandlerOfForm(360) == ScalarHandler_ScalarBinary;
    assert InstructionContractOperation_MIN() == ScalarOperation_MIN;
    assert InstructionContractHandler_MIN() == ScalarHandler_ScalarBinary;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000001011011', 360, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000001011011', 360, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000001011011', 360, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
