// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-FENTRY-DECODE-001","source":"asl/block/lifecycle/FENTRY.asl","requirements":["PTO-INST-BLOCK-FENTRY"],"kind":"decode-positive","summary":"canonical FENTRY catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000000000000000000000001000001', 32) == 70;
    assert CommandOperationOfForm(70) == CommandOperation_fentry_32_a47584ec13b6;
    assert CommandHandlerOfForm(70) == CommandHandler_ExecuteFrameEntry;
    assert InstructionContractMatches_FENTRY(CommandOperationOfForm(70));
    assert InstructionContractHandler_FENTRY() == CommandHandler_ExecuteFrameEntry;
    return 0;
end;
