// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SD-UPO-EXEC-001","source":"asl/scalar/agu/HL.SD.UPO.asl","requirements":["PTO-INST-SCALAR-HL-SD-UPO"],"kind":"execution","summary":"HL.SD.UPO executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_SD_UPO();
    return 0;
end;
