// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-SETC-NEI-BOUND-001","source":"asl/scalar/bru/SETC.NEI.asl","requirements":["PTO-INST-SCALAR-SETC-NEI"],"kind":"boundary","summary":"SETC.NEI covers operand selectors, immediates, conditions, targets, and faults","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUBounds_SETC_NEI();
    return 0;
end;
