// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-MODEL-FSU-PROFILE-STATIC-INVARIANT-001","source":"asl/scalar/model/fsu/profile.asl","requirements":[],"kind":"static-invariant","summary":"PTO-SCALAR-MODEL-FSU-PROFILE compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
