// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TMATMUL-MX-BIAS-STATIC-001","source":"asl/tile/matrix-and-matrix-vector/matrix-matrix/TMATMUL_MX_BIAS.asl","requirements":["PTO-INST-TILE-TMATMUL-MX-BIAS"],"kind":"static-invariant","summary":"canonical TMATMUL_MX_BIAS catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: matrix-and-matrix-vector/matrix-matrix
    // block: BSTART.TMATMULMX.BIAS AType | B.DATR BType, RMode, Sat (optional; BType defaults to AType) | B.FPATR PreQuantMode, ReluMode, GroupNCode, RowMaxEn, GroupMaxEn, RowMaxInit, MaxAbsEn, TransA, TransB (exactly one) | B.DIM LB0 M (optional, default 1) | B.DIM LB1 N (optional, default 1) | B.DIM LB2 K (optional, default 1) | B.IOS complete right or both matrix operand groups (optional; common nonzero mask) | B.IOT ordered Local mathematical sources: A CUBE_M16/M32 primary, optional A scale, B CUBE_N8 primary, optional B scale, 1xN Bias | B.IOT D matching A's CUBE_M16/M32 layout, optional RowMaxOut, optional GroupMaxOut destinations | B.IOT/B.IOR postprocess operands selected by B.FPATR | BSTOP or the next BSTART completion boundary
    assert DecodeTileOperation(TileDecode_CUBE, '000000000101') == 101;
    assert TileOperationOfIndex(101) == TileOperation_TMATMUL_MX_BIAS;
    assert TileHandlerOfIndex(101) == TileHandler_TMATMUL_MX_BIAS;
    assert TileClassOfIndex(101) == TileClass_MatrixAndMatrixVector;
    assert TileEngineOfIndex(101) == TileEngine_CUBE;
    assert InstructionContractOperation_TMATMUL_MX_BIAS() == TileOperation_TMATMUL_MX_BIAS;
    assert InstructionContractHandler_TMATMUL_MX_BIAS() == TileHandler_TMATMUL_MX_BIAS;
    assert InstructionContractCubeFunction_TMATMUL_MX_BIAS() == 5;
    assert InstructionContractSharedOperandsAllowed_TMATMUL_MX_BIAS() == TRUE;
    return 0;
end;
