// PTO-TEST: {"id":"PTO-AVS-BLOCK-B-FPATR-MODE-TABLE-BOUNDARY-001","source":"asl/block/attributes/B.FPATR.asl","requirements":["PTO-INST-BLOCK-B-FPATR"],"kind":"boundary","summary":"B.FPATR mode, GroupN and enable legality boundaries","pass_condition":"accepted modes and fail-closed reserved/invalid combinations are proved","related_sources":[]}
func main() => integer
begin
    assert BundleFPATRPreQuantModeLegal(Zeros{6});
    assert BundleFPATRPreQuantModeLegal('100111');
    assert !BundleFPATRPreQuantModeLegal('001110');
    assert BundleFPATRReluModeLegal('011');
    assert !BundleFPATRReluModeLegal('100');
    assert BundleFPATRGroupN('0000') == 0;
    assert BundleFPATRGroupN('0001') == 8;
    assert BundleFPATRGroupN('0010') == 16;
    assert BundleFPATRGroupN('0011') == 32;
    assert BundleFPATRGroupN('0100') == 48;
    assert BundleFPATRGroupN('0101') == 64;
    assert BundleFPATRGroupN('0110') == 80;
    assert BundleFPATRGroupN('0111') == 96;
    assert BundleFPATRGroupN('1000') == 112;
    assert BundleFPATRGroupN('1001') == 128;
    assert !BundleFPATRFieldsLegal(Zeros{6}, Zeros{3}, '0001', FALSE, FALSE, FALSE, FALSE);
    assert !BundleFPATRFieldsLegal(Zeros{6}, Zeros{3}, Zeros{4}, FALSE, FALSE, TRUE, FALSE);
    assert !BundleFPATRFieldsLegal(Zeros{6}, Zeros{3}, Zeros{4}, FALSE, FALSE, FALSE, TRUE);
    assert BundleFPATRFieldsLegal(Zeros{6}, Zeros{3}, Zeros{4}, TRUE, FALSE, FALSE, TRUE);
    assert BundleFPATRFieldsLegal(Zeros{6}, Zeros{3}, Zeros{4}, FALSE, FALSE, FALSE, FALSE);
    assert BundleFPATRFieldsLegal(Zeros{6}, Zeros{3}, Zeros{4}, TRUE, FALSE, FALSE, TRUE);
    assert BundleFPATRFieldsLegal(Zeros{6}, Zeros{3}, '0001', FALSE, TRUE, FALSE, TRUE);
    assert BundleFPATRFieldsLegal(Zeros{6}, Zeros{3}, '0001', TRUE, TRUE, FALSE, TRUE);
    assert !BundleFPATRFieldsLegal(Zeros{6}, Zeros{3}, Zeros{4}, FALSE, TRUE, FALSE, FALSE);
    assert !BundleFPATRFieldsLegal(Zeros{6}, Zeros{3}, '0001', FALSE, FALSE, TRUE, FALSE);
    assert BundleFPATRDATRFieldsLegal(Zeros{6}, Zeros{3}, FALSE);
    assert !BundleFPATRDATRFieldsLegal(Zeros{6}, '001', FALSE);
    assert !BundleFPATRDATRFieldsLegal('000001', '110', TRUE);
    // Fixed floating modes require RMode=NONE. Shift modes additionally use
    // fixed S16 saturation and therefore reject an encoded Sat request.
    assert BundleFPATRDATRFieldsLegal('001100', Zeros{3}, FALSE);
    assert !BundleFPATRDATRFieldsLegal('001100', Zeros{3}, TRUE);
    assert !BundleFPATRDATRFieldsLegal('001100', '001', FALSE);
    assert !BundleFPATRDATRFieldsLegal('001101', '010', TRUE);
    assert BundleFPATRDATRFieldsLegal('000001', Zeros{3}, FALSE);
    assert !BundleFPATRDATRFieldsLegal('000001', '111', TRUE);
    assert BundleFPATRDATRFieldsLegal('000011', '111', TRUE);
    assert BundleFPATROutputType('010001') == TileDataType_S4X2;
    assert BundleFPATROutputType('011010') == TileDataType_E4M3;
    // Complete accepted PreQuant table, parameter routing, and destination
    // type witness (reserved codes remain fail-closed above).
    assert BundleFPATRPreQuantModeLegal('000000');
    assert BundleFPATRPreQuantModeLegal('000001');
    assert BundleFPATRPreQuantModeLegal('000010');
    assert BundleFPATRPreQuantModeLegal('000011');
    assert BundleFPATRPreQuantModeLegal('000100');
    assert BundleFPATRPreQuantModeLegal('000101');
    assert BundleFPATRPreQuantModeLegal('001100');
    assert BundleFPATRPreQuantModeLegal('001101');
    assert BundleFPATRPreQuantModeLegal('010000');
    assert BundleFPATRPreQuantModeLegal('010001');
    assert BundleFPATRPreQuantModeLegal('010010');
    assert BundleFPATRPreQuantModeLegal('010011');
    assert BundleFPATRPreQuantModeLegal('010100');
    assert BundleFPATRPreQuantModeLegal('010111');
    assert BundleFPATRPreQuantModeLegal('011000');
    assert BundleFPATRPreQuantModeLegal('011001');
    assert BundleFPATRPreQuantModeLegal('011010');
    assert BundleFPATRPreQuantModeLegal('011011');
    assert BundleFPATRPreQuantModeLegal('011100');
    assert BundleFPATRPreQuantModeLegal('100000');
    assert BundleFPATRPreQuantModeLegal('100001');
    assert BundleFPATRPreQuantModeLegal('100010');
    assert BundleFPATRPreQuantModeLegal('100011');
    assert BundleFPATRPreQuantModeLegal('100100');
    assert BundleFPATRPreQuantModeLegal('100101');
    assert BundleFPATRPreQuantModeLegal('100110');
    assert BundleFPATRPreQuantModeLegal('100111');
    assert !BundleFPATRModeUsesVectorParameter('000000');
    assert !BundleFPATRModeUsesScalarParameter('000000');
    assert !BundleFPATRModeUsesScalarParameter('000001');
    assert BundleFPATRModeUsesVectorParameter('000010');
    assert BundleFPATRModeUsesScalarParameter('000011');
    assert BundleFPATRModeUsesVectorParameter('000100');
    assert BundleFPATRModeUsesScalarParameter('000101');
    assert BundleFPATRModeUsesVectorParameter('001100');
    assert BundleFPATRModeUsesScalarParameter('001101');
    assert !BundleFPATRModeUsesVectorParameter('010000');
    assert !BundleFPATRModeUsesScalarParameter('010000');
    assert BundleFPATRModeUsesScalarParameter('010001');
    assert BundleFPATRModeUsesVectorParameter('010010');
    assert BundleFPATRModeUsesScalarParameter('010011');
    assert BundleFPATRModeUsesVectorParameter('010100');
    assert BundleFPATRModeUsesVectorParameter('010111');
    assert BundleFPATRModeUsesScalarParameter('011000');
    assert BundleFPATRModeUsesScalarParameter('011001');
    assert BundleFPATRModeUsesScalarParameter('011010');
    assert BundleFPATRModeUsesScalarParameter('011011');
    assert BundleFPATRModeUsesVectorParameter('011100');
    assert BundleFPATRModeUsesScalarParameter('100000');
    assert BundleFPATRModeUsesVectorParameter('100001');
    assert BundleFPATRModeUsesScalarParameter('100010');
    assert BundleFPATRModeUsesScalarParameter('100011');
    assert BundleFPATRModeUsesVectorParameter('100100');
    assert BundleFPATRModeUsesVectorParameter('100101');
    assert BundleFPATRModeUsesVectorParameter('100110');
    assert BundleFPATRModeUsesVectorParameter('100111');
    assert BundleFPATRReluModeUsesScalarParameter('010');
    assert BundleFPATRReluModeUsesVectorParameter('011');
    assert !BundleFPATRReluModeUsesScalarParameter('000');
    assert !BundleFPATRReluModeUsesVectorParameter('001');
    assert BundleFPATROutputType('000000') == TileDataType_FP32;
    assert BundleFPATROutputType('000001') == TileDataType_FP16;
    assert BundleFPATROutputType('000010') == TileDataType_S8;
    assert BundleFPATROutputType('000011') == TileDataType_S8;
    assert BundleFPATROutputType('000100') == TileDataType_FP16;
    assert BundleFPATROutputType('000101') == TileDataType_FP16;
    assert BundleFPATROutputType('001100') == TileDataType_S16;
    assert BundleFPATROutputType('001101') == TileDataType_S16;
    assert BundleFPATROutputType('010000') == TileDataType_BF16;
    assert BundleFPATROutputType('010001') == TileDataType_S4X2;
    assert BundleFPATROutputType('010010') == TileDataType_S4X2;
    assert BundleFPATROutputType('010011') == TileDataType_S16;
    assert BundleFPATROutputType('010100') == TileDataType_S16;
    assert BundleFPATROutputType('010111') == TileDataType_S8;
    assert BundleFPATROutputType('011000') == TileDataType_S8;
    assert BundleFPATROutputType('011001') == TileDataType_HiF8;
    assert BundleFPATROutputType('011010') == TileDataType_E4M3;
    assert BundleFPATROutputType('011011') == TileDataType_FP32;
    assert BundleFPATROutputType('011100') == TileDataType_HiF8;
    assert BundleFPATROutputType('100000') == TileDataType_FP16;
    assert BundleFPATROutputType('100001') == TileDataType_FP16;
    assert BundleFPATROutputType('100010') == TileDataType_BF16;
    assert BundleFPATROutputType('100011') == TileDataType_BF16;
    assert BundleFPATROutputType('100100') == TileDataType_BF16;
    assert BundleFPATROutputType('100101') == TileDataType_E4M3;
    assert BundleFPATROutputType('100110') == TileDataType_FP32;
    assert BundleFPATROutputType('100111') == TileDataType_BF16;
    // Partial final groups and GroupN>N both round up to one group; a
    // non-multiple column count creates the expected final partial group.
    _BundleFixedPointAttributes.group_max_en = TRUE;
    _BundleFixedPointAttributes.group_n_code = '0001';
    assert BundleGroupMaxColumns(3) == 1;
    assert BundleGroupMaxColumns(8) == 1;
    assert BundleGroupMaxColumns(9) == 2;
    assert BundleGroupMaxColumns(127) == 16;
    assert BundleGroupMaxColumns(128) == 16;
    _BundleFixedPointAttributes.group_n_code = '1001';
    assert BundleGroupMaxColumns(127) == 1;
    assert BundleGroupMaxColumns(128) == 1;
    assert BundleGroupMaxColumns(129) == 2;
    return 0;
end;
