// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-ERCOV-DECODE-001","source":"asl/block/lifecycle/ERCOV.asl","requirements":["PTO-INST-BLOCK-ERCOV"],"kind":"decode-positive","summary":"canonical ERCOV catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000000000000000011000000110001', 32) == 60;
    assert CommandOperationOfForm(60) == CommandOperation_ercov_32_dc0be14a2d8b;
    assert CommandHandlerOfForm(60) == CommandHandler_RecoverExecutionContext;
    assert InstructionContractMatches_ERCOV(CommandOperationOfForm(60));
    assert InstructionContractHandler_ERCOV() == CommandHandler_RecoverExecutionContext;
    return 0;
end;
