// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-FMADD-DECODE-001","source":"asl/scalar/fsu/FMADD.asl","requirements":["PTO-INST-SCALAR-FMADD"],"kind":"decode-positive","summary":"canonical FMADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000100000001001011', 32) == 113;
    assert ScalarOperationOfForm(113) == ScalarOperation_FMADD;
    assert ScalarHandlerOfForm(113) == ScalarHandler_FloatingFused;
    assert InstructionContractOperation_FMADD() == ScalarOperation_FMADD;
    assert InstructionContractHandler_FMADD() == ScalarHandler_FloatingFused;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000100000001001011', 113, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000100000001001011', 113, ScalarField_SrcA) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000100000001001011', 113, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000100000001001011', 113, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000100000001001011', 113, ScalarField_SrcType) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
