// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FMADD-TYPE-001","source":"asl/scalar/fsu/FMADD.asl","requirements":["PTO-INST-SCALAR-FMADD"],"kind":"boundary","summary":"FMADD covers every assigned source and destination data-type encoding","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUTypesLegal_FMADD();
    return 0;
end;
