// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LDIP-FAULT-001","source":"asl/scalar/agu/HL.LDIP.asl","requirements":["PTO-INST-SCALAR-HL-LDIP"],"kind":"fault","summary":"HL.LDIP rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_HL_LDIP();
    return 0;
end;
