// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LDIP-BOUND-001","source":"asl/scalar/agu/HL.LDIP.asl","requirements":["PTO-INST-SCALAR-HL-LDIP"],"kind":"boundary","summary":"HL.LDIP covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_LDIP();
    return 0;
end;
