// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SH-PO-ALIAS-001","source":"asl/scalar/agu/HL.SH.PO.asl","requirements":["PTO-INST-SCALAR-HL-SH-PO"],"kind":"execution","summary":"HL.SH.PO covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_HL_SH_PO();
    return 0;
end;
