// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-DATA-TYPES-MEMORY-OPERATIONS-STATIC-001","source":"asl/arch/data-types/memory-operations.asl","requirements":[],"kind":"static-invariant","summary":"PTO-ARCH-DATA-TYPES-MEMORY-OPERATIONS compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
