// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-MSCATTER-XOR-STATIC-001","source":"asl/tile/memory-and-data-movement/irregular/MSCATTER_XOR.asl","requirements":["PTO-INST-TILE-MSCATTER-XOR"],"kind":"static-invariant","summary":"canonical MSCATTER_XOR catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory-and-data-movement/irregular
    // block: BSTART.MSCATTER.XOR DataType | B.IOT IndexTile, ValueTile, mask=PE_MASK, <last> | B.IOR BaseGPR, zero, zero, ->zero | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000011010') == 124;
    assert TileOperationOfIndex(124) == TileOperation_MSCATTER_XOR;
    assert TileHandlerOfIndex(124) == TileHandler_GM_RED_VALUE;
    assert TileClassOfIndex(124) == TileClass_MemoryAndDataMovement;
    assert TileEngineOfIndex(124) == TileEngine_TLSU;
    assert InstructionContractOperation_MSCATTER_XOR() == TileOperation_MSCATTER_XOR;
    assert InstructionContractHandler_MSCATTER_XOR() == TileHandler_GM_RED_VALUE;
    return 0;
end;
