// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-CMP-AND-EXEC-001","source":"asl/scalar/bru/CMP.AND.asl","requirements":["PTO-INST-SCALAR-CMP-AND"],"kind":"execution","summary":"CMP.AND executes the canonical comparison, branch, jump, or control effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUExecute_CMP_AND();
    return 0;
end;
