// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TTRANS-STATIC-001","source":"asl/tile/layout-and-rearrangement/layout/TTRANS.asl","requirements":["PTO-INST-TILE-TTRANS"],"kind":"static-invariant","summary":"canonical TTRANS catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: layout-and-rearrangement/layout
    // block: BSTART.SFU TTRANS, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001101110') == 80;
    assert TileOperationOfIndex(80) == TileOperation_TTRANS;
    assert TileHandlerOfIndex(80) == TileHandler_TTRANS;
    assert TileClassOfIndex(80) == TileClass_LayoutAndRearrangement;
    assert TileEngineOfIndex(80) == TileEngine_SFU;
    assert InstructionContractOperation_TTRANS() == TileOperation_TTRANS;
    assert InstructionContractHandler_TTRANS() == TileHandler_TTRANS;
    return 0;
end;
