// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-LWUI-DECODE-001","source":"asl/scalar/agu/LWUI.asl","requirements":["PTO-INST-SCALAR-LWUI"],"kind":"decode-positive","summary":"canonical LWUI catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000110000000011001', 32) == 362;
    assert ScalarOperationOfForm(362) == ScalarOperation_LWUI;
    assert ScalarHandlerOfForm(362) == ScalarHandler_ExecuteScalarLoad;
    assert InstructionContractOperation_LWUI() == ScalarOperation_LWUI;
    assert InstructionContractHandler_LWUI() == ScalarHandler_ExecuteScalarLoad;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000110000000011001', 362, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000110000000011001', 362, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000110000000011001', 362, ScalarField_simm12) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
