// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-PROFILE-LINX-RUNTIME-COMPAT-STATIC-001","source":"asl/arch/profile/linx-runtime-compat.asl","requirements":["PTO-PROFILE-LINX-RUNTIME-COMPAT-001","PTO-PROFILE-LINX-PEID-SSR-001","PTO-PROFILE-LINX-NON-SYS-SYSTEM-OPS-001","PTO-PROFILE-LINX-ACRC-EXIT-OBSERVATION-001","PTO-PROFILE-HOST-MEMORY-001"],"kind":"static-invariant","summary":"PTO-ARCH-PROFILE-LINX-RUNTIME-COMPAT compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
