// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TADD-STATIC-001","source":"asl/tile/elementwise-tile-tile/arithmetic/TADD.asl","requirements":["PTO-INST-TILE-TADD"],"kind":"static-invariant","summary":"canonical TADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: elementwise-tile-tile/arithmetic
    // block: BSTART.VEC TADD, DataType | B.DATR PadValue (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT SrcLeft, SrcRight, mask=PE_MASK, <last>, ->DstTile<TSize> | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000000000') == 0;
    assert TileOperationOfIndex(0) == TileOperation_TADD;
    assert TileHandlerOfIndex(0) == TileHandler_ExecuteTileBinary;
    assert TileClassOfIndex(0) == TileClass_ElementwiseTileTile;
    assert TileEngineOfIndex(0) == TileEngine_VEC;
    assert InstructionContractOperation_TADD() == TileOperation_TADD;
    assert InstructionContractHandler_TADD() == TileHandler_ExecuteTileBinary;
    return 0;
end;
