// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-ATOM-XOR-SEMANTIC-001","source":"asl/block/execution/BSTART.ATOM.XOR.asl","requirements":["PTO-INST-BLOCK-BSTART-ATOM-XOR"],"kind":"execution","summary":"BSTART.ATOM.XOR exercises its GM semantic primitive at the owner boundary","pass_condition":"the decoded owner mapping and representative GM effect assertions hold","related_sources":["asl/tile/model/memory/gm-atom-red.asl","asl/tile/model/memory/gm-atom-red-execution.asl"]}
func main() => integer
begin
    assert GMAtomicOperationFromFunction(18) == GMAtomic_XOR;
    assert GMAtomicOperationDataTypeLegal(GMAtomic_XOR, TileDataType_U32);
    let (result, performed) = GMAtomicResult(GMAtomic_XOR, TileDataType_U32,
        Zeros{PTO_XLEN} + 3, Zeros{PTO_XLEN} + 0xF0,
        Zeros{PTO_XLEN} + 0, Zeros{PTO_XLEN} + 0);
    assert result == Zeros{PTO_XLEN} + 0xFF;
    assert performed;
    return 0;
end;
