// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-CMP-LTI-EXEC-001","source":"asl/scalar/bru/CMP.LTI.asl","requirements":["PTO-INST-SCALAR-CMP-LTI"],"kind":"execution","summary":"CMP.LTI executes the canonical comparison, branch, jump, or control effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUExecute_CMP_LTI();
    return 0;
end;
