// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LBUP-EXEC-001","source":"asl/scalar/agu/HL.LBUP.asl","requirements":["PTO-INST-SCALAR-HL-LBUP"],"kind":"execution","summary":"HL.LBUP executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_LBUP();
    return 0;
end;
