// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LBUP-BOUND-001","source":"asl/scalar/agu/HL.LBUP.asl","requirements":["PTO-INST-SCALAR-HL-LBUP"],"kind":"boundary","summary":"HL.LBUP covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_LBUP();
    return 0;
end;
