// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-LW-DECODE-001","source":"asl/scalar/agu/LW.asl","requirements":["PTO-INST-SCALAR-LW"],"kind":"decode-positive","summary":"canonical LW catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000010000000001001', 32) == 348;
    assert ScalarOperationOfForm(348) == ScalarOperation_LW;
    assert ScalarHandlerOfForm(348) == ScalarHandler_ExecuteScalarLoad;
    assert InstructionContractOperation_LW() == ScalarOperation_LW;
    assert InstructionContractHandler_LW() == ScalarHandler_ExecuteScalarLoad;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000010000000001001', 348, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000010000000001001', 348, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000010000000001001', 348, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000010000000001001', 348, ScalarField_SrcRType) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000010000000001001', 348, ScalarField_shamt) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
