// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-C-SETC-EQ-BOUND-001","source":"asl/scalar/bru/C.SETC.EQ.asl","requirements":["PTO-INST-SCALAR-C-SETC-EQ"],"kind":"boundary","summary":"C.SETC.EQ covers operand selectors, immediates, conditions, targets, and faults","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUBounds_C_SETC_EQ();
    return 0;
end;
