// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FCVTP-SRC-001","source":"asl/scalar/fsu/FCVTP.asl","requirements":["PTO-INST-SCALAR-FCVTP"],"kind":"execution","summary":"FCVTP covers absolute and temporary-queue source selectors and aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUAliasSources_FCVTP();
    return 0;
end;
