// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LWUIP-FAULT-001","source":"asl/scalar/agu/HL.LWUIP.asl","requirements":["PTO-INST-SCALAR-HL-LWUIP"],"kind":"fault","summary":"HL.LWUIP rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_HL_LWUIP();
    return 0;
end;
