// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-LHI-U-DECODE-001","source":"asl/scalar/agu/HL.LHI.U.asl","requirements":["PTO-INST-SCALAR-HL-LHI-U"],"kind":"decode-positive","summary":"canonical HL.LHI.U catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000010000001010010000000000001110', 48) == 183;
    assert ScalarOperationOfForm(183) == ScalarOperation_HL_LHI_U;
    assert ScalarHandlerOfForm(183) == ScalarHandler_ExecuteScalarLoad;
    assert InstructionContractOperation_HL_LHI_U() == ScalarOperation_HL_LHI_U;
    assert InstructionContractHandler_HL_LHI_U() == ScalarHandler_ExecuteScalarLoad;
    assert DecodeScalarOperandRaw('000000000000000000010000001010010000000000001110', 183, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000001010010000000000001110', 183, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000001010010000000000001110', 183, ScalarField_simm22) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
