// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TCOLARGMIN-STATIC-001","source":"asl/tile/reduce-and-expand/column-reduction/TCOLARGMIN.asl","requirements":["PTO-INST-TILE-TCOLARGMIN"],"kind":"static-invariant","summary":"canonical TCOLARGMIN catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: reduce-and-expand/column-reduction
    // block: BSTART.SFU TCOLARGMIN, DataType | B.DATR Layout, PadValue (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT SrcTile, mask=PE_MASK, <last>, ->DstTile<TSize> | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001011101') == 67;
    assert TileOperationOfIndex(67) == TileOperation_TCOLARGMIN;
    assert TileHandlerOfIndex(67) == TileHandler_ExecuteTileReduction;
    assert TileClassOfIndex(67) == TileClass_ReduceAndExpand;
    assert TileEngineOfIndex(67) == TileEngine_SFU;
    assert InstructionContractOperation_TCOLARGMIN() == TileOperation_TCOLARGMIN;
    assert InstructionContractHandler_TCOLARGMIN() == TileHandler_ExecuteTileReduction;
    return 0;
end;
