// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-CMP-EQ-EXEC-001","source":"asl/scalar/bru/CMP.EQ.asl","requirements":["PTO-INST-SCALAR-CMP-EQ"],"kind":"execution","summary":"CMP.EQ executes the canonical comparison, branch, jump, or control effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUExecute_CMP_EQ();
    return 0;
end;
