// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FMIN-TYPE-001","source":"asl/scalar/fsu/FMIN.asl","requirements":["PTO-INST-SCALAR-FMIN"],"kind":"boundary","summary":"FMIN covers every assigned source and destination data-type encoding","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUTypesLegal_FMIN();
    return 0;
end;
