// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FMIN-EXEC-001","source":"asl/scalar/fsu/FMIN.asl","requirements":["PTO-INST-SCALAR-FMIN"],"kind":"execution","summary":"FMIN executes the canonical floating-point or conversion effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUExecute_FMIN();
    return 0;
end;
