// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FMIN-BOUND-001","source":"asl/scalar/fsu/FMIN.asl","requirements":["PTO-INST-SCALAR-FMIN"],"kind":"boundary","summary":"FMIN covers zeros, infinities, NaNs, extrema, and signed carriers","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUBounds_FMIN();
    return 0;
end;
