// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FSQRT-SNAP-001","source":"asl/scalar/fsu/FSQRT.asl","requirements":["PTO-INST-SCALAR-FSQRT"],"kind":"execution","summary":"FSQRT covers source snapshotting before overlapping destination publication","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUAliasSnapshot_FSQRT();
    return 0;
end;
