// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FSQRT-TYPE-001","source":"asl/scalar/fsu/FSQRT.asl","requirements":["PTO-INST-SCALAR-FSQRT"],"kind":"boundary","summary":"FSQRT covers every assigned source and destination data-type encoding","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUTypesLegal_FSQRT();
    return 0;
end;
