// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FSQRT-BOUND-001","source":"asl/scalar/fsu/FSQRT.asl","requirements":["PTO-INST-SCALAR-FSQRT"],"kind":"boundary","summary":"FSQRT covers zeros, infinities, NaNs, extrema, and signed carriers","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUBounds_FSQRT();
    return 0;
end;
