// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-CMP-OR-BOUND-001","source":"asl/scalar/bru/CMP.OR.asl","requirements":["PTO-INST-SCALAR-CMP-OR"],"kind":"boundary","summary":"CMP.OR covers operand selectors, immediates, conditions, targets, and faults","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUBounds_CMP_OR();
    return 0;
end;
