// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LD-PO-EXEC-001","source":"asl/scalar/agu/HL.LD.PO.asl","requirements":["PTO-INST-SCALAR-HL-LD-PO"],"kind":"execution","summary":"HL.LD.PO executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_LD_PO();
    return 0;
end;
