// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-OVERVIEW-ARCHITECTURE-STATIC-001","source":"asl/arch/overview/architecture.asl","requirements":["PTO-SOURCE-HIERARCHY","PTO-ARCH-COMMIT-EVENT-CONFORMANCE-001","PTO-ARCH-STATE-CLOSURE-001","PTO-TILE-CAPACITY-PER-PE","PTO-RELEASE-VERIFICATION"],"kind":"static-invariant","summary":"PTO-ARCH-OVERVIEW-ARCHITECTURE compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
