// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TMUL-STATIC-INVARIANT-001","source":"asl/tile/elementwise-tile-tile/arithmetic/TMUL.asl","requirements":["PTO-INST-TILE-TMUL"],"kind":"static-invariant","summary":"canonical TMUL catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: elementwise-tile-tile/arithmetic
    // block: BSTART.VEC TMUL, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000000010') == 2;
    assert TileOperationOfIndex(2) == TileOperation_TMUL;
    assert TileHandlerOfIndex(2) == TileHandler_ExecuteTileBinary;
    assert TileClassOfIndex(2) == TileClass_ElementwiseTileTile;
    assert TileEngineOfIndex(2) == TileEngine_VEC;
    assert InstructionContractOperation_TMUL() == TileOperation_TMUL;
    assert InstructionContractHandler_TMUL() == TileHandler_ExecuteTileBinary;
    return 0;
end;
