// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SYS-BC-IVA-TSRC-001","source":"asl/scalar/sys/BC.IVA.asl","requirements":["PTO-INST-SCALAR-BC-IVA"],"kind":"execution","summary":"BC.IVA proves its tsrc SYS contract","pass_condition":"the mnemonic-owned decoded assertions hold","related_sources":[]}
func main() => integer
begin
    ResetProfileState();
    SetCurrentACR(0);
    WriteTPC(Zeros{PTO_XLEN} + 0x100);
    BeginBundle(BundleKind_System, BundleTransfer_Fallthrough,
        Zeros{PTO_XLEN}, Zeros{PTO_XLEN} + 0x180,
        Zeros{PTO_XLEN}, FALSE);
    EnterBundleBody();
    _TQueue[[0]] = Zeros{PTO_XLEN} + 0x1000;
    _TQueueValid[[0]] = TRUE;
    let status = ExecuteScalarInstruction('000000000000000000000000000011000100000000101011', 32);
    assert status == ScalarExecution_Executed;
    assert _LastFault == Fault_None;
    assert _BundleCacheEpoch == 1;
    assert ReadTemporaryQueue(TRUE, 0) == Zeros{PTO_XLEN} + 0x1000;
    assert _LastMaintenanceOperation == Maintenance_BC_IVA;
    assert _LastMaintenanceOperand == Zeros{PTO_XLEN} + 0x1000;
    assert ReadTPC() == Zeros{PTO_XLEN} + 0x184;
    assert InstructionContractOperation_BC_IVA() == ScalarOperation_BC_IVA;
    return 0;
end;
