// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TDEQUANT-STATIC-INVARIANT-001","source":"asl/tile/irregular-and-complex/format-conversion/TDEQUANT.asl","requirements":["PTO-INST-TILE-TDEQUANT"],"kind":"static-invariant","summary":"canonical TDEQUANT catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: irregular-and-complex/format-conversion
    // block: BSTART.SFU TDEQUANT, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001101011') == 77;
    assert TileOperationOfIndex(77) == TileOperation_TDEQUANT;
    assert TileHandlerOfIndex(77) == TileHandler_TDEQUANT;
    assert TileClassOfIndex(77) == TileClass_IrregularAndComplex;
    assert TileEngineOfIndex(77) == TileEngine_SFU;
    assert InstructionContractOperation_TDEQUANT() == TileOperation_TDEQUANT;
    assert InstructionContractHandler_TDEQUANT() == TileHandler_TDEQUANT;
    return 0;
end;
