// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TDEQUANT-STATIC-001","source":"asl/tile/irregular-and-complex/format-conversion/TDEQUANT.asl","requirements":["PTO-INST-TILE-TDEQUANT"],"kind":"static-invariant","summary":"canonical TDEQUANT catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: irregular-and-complex/format-conversion
    // block: BSTART.SFU TDEQUANT, S8|U8 | B.DATR FP32, RMode | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional, default 1) | B.DIM LB2=Col (optional, default ValidCol) | B.IOR MultiplierFP32, ZeroPoint (optional; omission selects 1.0 and 0) | B.IOT SrcTile, mask=PE_MASK, <last>, ->DstTile<TSize> | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001101011') == 76;
    assert TileOperationOfIndex(76) == TileOperation_TDEQUANT;
    assert TileHandlerOfIndex(76) == TileHandler_TDEQUANT;
    assert TileClassOfIndex(76) == TileClass_IrregularAndComplex;
    assert TileEngineOfIndex(76) == TileEngine_SFU;
    assert InstructionContractOperation_TDEQUANT() == TileOperation_TDEQUANT;
    assert InstructionContractHandler_TDEQUANT() == TileHandler_TDEQUANT;
    return 0;
end;
