// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TCOLEXPAND-STATIC-INVARIANT-001","source":"asl/tile/vector-tile-expansion/column-expansion/TCOLEXPAND.asl","requirements":["PTO-INST-TILE-TCOLEXPAND"],"kind":"static-invariant","summary":"canonical TCOLEXPAND catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: vector-tile-expansion/column-expansion
    // block: BSTART.TEPL TCOLEXPAND, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001010100') == 58;
    assert TileOperationOfIndex(58) == TileOperation_TCOLEXPAND;
    assert TileHandlerOfIndex(58) == TileHandler_ExecuteTileExpand;
    assert InstructionContractOperation_TCOLEXPAND() == TileOperation_TCOLEXPAND;
    assert InstructionContractHandler_TCOLEXPAND() == TileHandler_ExecuteTileExpand;
    return 0;
end;
