// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TROWEXPANDMIN-STATIC-INVARIANT-001","source":"asl/tile/vector-tile-expansion/row-expansion/TROWEXPANDMIN.asl","requirements":["PTO-INST-TILE-TROWEXPANDMIN"],"kind":"static-invariant","summary":"canonical TROWEXPANDMIN catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: vector-tile-expansion/row-expansion
    // block: BSTART.TEPL TROWEXPANDMIN, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001001010') == 50;
    assert TileOperationOfIndex(50) == TileOperation_TROWEXPANDMIN;
    assert TileHandlerOfIndex(50) == TileHandler_ExecuteTileExpand;
    assert InstructionContractOperation_TROWEXPANDMIN() == TileOperation_TROWEXPANDMIN;
    assert InstructionContractHandler_TROWEXPANDMIN() == TileHandler_ExecuteTileExpand;
    return 0;
end;
