// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LD-PR-BOUND-001","source":"asl/scalar/agu/HL.LD.PR.asl","requirements":["PTO-INST-SCALAR-HL-LD-PR"],"kind":"boundary","summary":"HL.LD.PR covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_LD_PR();
    return 0;
end;
