// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-MGATHER-OR-SEMANTIC-001","source":"asl/block/execution/BSTART.MGATHER.OR.asl","requirements":["PTO-INST-BLOCK-BSTART-MGATHER-OR"],"kind":"execution","summary":"BSTART.MGATHER.OR exercises its GM semantic primitive at the owner boundary","pass_condition":"the decoded owner mapping and representative GM effect assertions hold","related_sources":["asl/tile/model/memory/gm-atom-red.asl","asl/tile/model/memory/gm-atom-red-execution.asl"]}
func main() => integer
begin
    assert GMAtomicOperationFromFunction(17) == GMAtomic_OR;
    assert GMAtomicOperationDataTypeLegal(GMAtomic_OR, TileDataType_U32);
    let (result, performed) = GMAtomicResult(GMAtomic_OR, TileDataType_U32,
        Zeros{PTO_XLEN} + 3, Zeros{PTO_XLEN} + 0xF0,
        Zeros{PTO_XLEN} + 0, Zeros{PTO_XLEN} + 0);
    assert result == Zeros{PTO_XLEN} + 0xF3;
    assert performed;
    return 0;
end;
