// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LH-ALIAS-001","source":"asl/scalar/agu/LH.asl","requirements":["PTO-INST-SCALAR-LH"],"kind":"execution","summary":"LH covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_LH();
    return 0;
end;
