// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-MSCATTER-DEC-DECODE-001","source":"asl/block/execution/BSTART.MSCATTER.DEC.asl","requirements":["PTO-INST-BLOCK-BSTART-MSCATTER-DEC"],"kind":"decode-positive","summary":"canonical BSTART.MSCATTER.DEC catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000001011100010001000110000001', 32) == 89;
    assert CommandOperationOfForm(89) == CommandOperation_bstart_mscatter_dec_32_gm23;
    assert CommandHandlerOfForm(89) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_BSTART_MSCATTER_DEC(CommandOperationOfForm(89));
    assert InstructionContractHandler_BSTART_MSCATTER_DEC() == CommandHandler_ExecuteBundleStart;
    return 0;
end;
