// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FGES-RSVD-001","source":"asl/scalar/fsu/FGES.asl","requirements":["PTO-INST-SCALAR-FGES"],"kind":"fault","summary":"FGES rejects reserved data-type encodings before architectural effects","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUTypesReserved_FGES();
    return 0;
end;
