// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FGES-SNAP-001","source":"asl/scalar/fsu/FGES.asl","requirements":["PTO-INST-SCALAR-FGES"],"kind":"execution","summary":"FGES covers source snapshotting before overlapping destination publication","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUAliasSnapshot_FGES();
    return 0;
end;
