// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LBU-PR-EXEC-001","source":"asl/scalar/agu/HL.LBU.PR.asl","requirements":["PTO-INST-SCALAR-HL-LBU-PR"],"kind":"execution","summary":"HL.LBU.PR executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_LBU_PR();
    return 0;
end;
