// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LBU-PR-FAULT-001","source":"asl/scalar/agu/HL.LBU.PR.asl","requirements":["PTO-INST-SCALAR-HL-LBU-PR"],"kind":"fault","summary":"HL.LBU.PR rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_HL_LBU_PR();
    return 0;
end;
