// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SYS-IC-IVA-EXEC-001","source":"asl/scalar/sys/IC.IVA.asl","requirements":["PTO-INST-SCALAR-IC-IVA"],"kind":"execution","summary":"IC.IVA proves its direct SYS contract","pass_condition":"the mnemonic-owned decoded assertions hold","related_sources":[]}
func main() => integer
begin
    ResetProfileState();
    SetCurrentACR(0);
    WriteTPC(Zeros{PTO_XLEN} + 0x100);
    BeginBundle(BundleKind_System, BundleTransfer_Fallthrough,
        Zeros{PTO_XLEN}, Zeros{PTO_XLEN} + 0x180,
        Zeros{PTO_XLEN}, FALSE);
    EnterBundleBody();
    WriteGPR(5, Zeros{PTO_XLEN} + 0x1000);
    let status = ExecuteScalarInstruction('000000000000000000000000000000101101000000101011', 32);
    assert status == ScalarExecution_Executed;
    assert _LastFault == Fault_None;
    assert _InstructionCacheEpoch == 1;
    assert _LastMaintenanceOperation == Maintenance_IC_IVA;
    assert _LastMaintenanceOperand == Zeros{PTO_XLEN} + 0x1000;
    assert ReadTPC() == Zeros{PTO_XLEN} + 0x184;
    assert InstructionContractOperation_IC_IVA() == ScalarOperation_IC_IVA;
    return 0;
end;
