// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TCOLEXPANDDIV-STATIC-INVARIANT-001","source":"asl/tile/reduce-and-expand/column-expansion/TCOLEXPANDDIV.asl","requirements":["PTO-INST-TILE-TCOLEXPANDDIV"],"kind":"static-invariant","summary":"canonical TCOLEXPANDDIV catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: reduce-and-expand/column-expansion
    // block: BSTART.SFU TCOLEXPANDDIV, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001011000') == 62;
    assert TileOperationOfIndex(62) == TileOperation_TCOLEXPANDDIV;
    assert TileHandlerOfIndex(62) == TileHandler_ExecuteTileExpand;
    assert TileClassOfIndex(62) == TileClass_ReduceAndExpand;
    assert TileEngineOfIndex(62) == TileEngine_SFU;
    assert InstructionContractOperation_TCOLEXPANDDIV() == TileOperation_TCOLEXPANDDIV;
    assert InstructionContractHandler_TCOLEXPANDDIV() == TileHandler_ExecuteTileExpand;
    return 0;
end;
