// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TCOLEXPANDSUB-STATIC-INVARIANT-001","source":"asl/tile/vector-tile-expansion/column-expansion/TCOLEXPANDSUB.asl","requirements":["PTO-INST-TILE-TCOLEXPANDSUB"],"kind":"static-invariant","summary":"canonical TCOLEXPANDSUB catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: vector-tile-expansion/column-expansion
    // block: BSTART.TEPL TCOLEXPANDSUB, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001010110') == 60;
    assert TileOperationOfIndex(60) == TileOperation_TCOLEXPANDSUB;
    assert TileHandlerOfIndex(60) == TileHandler_ExecuteTileExpand;
    assert InstructionContractOperation_TCOLEXPANDSUB() == TileOperation_TCOLEXPANDSUB;
    assert InstructionContractHandler_TCOLEXPANDSUB() == TileHandler_ExecuteTileExpand;
    return 0;
end;
