// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TROWEXPANDMUL-STATIC-001","source":"asl/tile/reduce-and-expand/row-expansion/TROWEXPANDMUL.asl","requirements":["PTO-INST-TILE-TROWEXPANDMUL"],"kind":"static-invariant","summary":"canonical TROWEXPANDMUL catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: reduce-and-expand/row-expansion
    // block: BSTART.SFU TROWEXPANDMUL, DataType | B.DATR Layout, PadValue (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT SrcTile, BroadcastTile, mask=PE_MASK, <last>, ->DstTile<TSize> | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001000111') == 47;
    assert TileOperationOfIndex(47) == TileOperation_TROWEXPANDMUL;
    assert TileHandlerOfIndex(47) == TileHandler_ExecuteTileExpand;
    assert TileClassOfIndex(47) == TileClass_ReduceAndExpand;
    assert TileEngineOfIndex(47) == TileEngine_SFU;
    assert InstructionContractOperation_TROWEXPANDMUL() == TileOperation_TROWEXPANDMUL;
    assert InstructionContractHandler_TROWEXPANDMUL() == TileHandler_ExecuteTileExpand;
    return 0;
end;
