// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SHP-BOUND-001","source":"asl/scalar/agu/HL.SHP.asl","requirements":["PTO-INST-SCALAR-HL-SHP"],"kind":"boundary","summary":"HL.SHP covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_SHP();
    return 0;
end;
