// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-LD-UMIN-DECODE-001","source":"asl/scalar/amo/LD.UMIN.asl","requirements":["PTO-INST-SCALAR-LD-UMIN"],"kind":"decode-positive","summary":"canonical LD.UMIN catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000001110000000000000100000000001011', 32) == 322;
    assert ScalarOperationOfForm(322) == ScalarOperation_LD_UMIN;
    assert ScalarHandlerOfForm(322) == ScalarHandler_AtomicReadModifyWrite;
    assert InstructionContractOperation_LD_UMIN() == ScalarOperation_LD_UMIN;
    assert InstructionContractHandler_LD_UMIN() == ScalarHandler_AtomicReadModifyWrite;
    assert DecodeScalarOperandRaw('000000000000000001110000000000000100000000001011', 322, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000000000000100000000001011', 322, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000000000000100000000001011', 322, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000000000000100000000001011', 322, ScalarField_aq) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000000000000100000000001011', 322, ScalarField_far) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000000000000100000000001011', 322, ScalarField_rl) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
