// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-ACRC-DECODE-001","source":"asl/scalar/sys/ACRC.asl","requirements":["PTO-INST-SCALAR-ACRC"],"kind":"decode-positive","summary":"canonical ACRC catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000011000000101011', 32) == 0;
    assert ScalarOperationOfForm(0) == ScalarOperation_ACRC;
    assert ScalarHandlerOfForm(0) == ScalarHandler_ArchitectureCloseRequest;
    assert InstructionContractOperation_ACRC() == ScalarOperation_ACRC;
    assert InstructionContractHandler_ACRC() == ScalarHandler_ArchitectureCloseRequest;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000011000000101011', 0, ScalarField_RST_Type) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
