// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-DISPATCH-FUNCTIONAL-STEP-STATIC-001","source":"asl/arch/dispatch/functional-step.asl","requirements":[],"kind":"static-invariant","summary":"PTO-ARCH-DISPATCH-FUNCTIONAL-STEP compiles as a non-architectural model harness unit","pass_condition":"the complete PTO model and this model-harness static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
