// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-ATOM-EXCH-STATIC-001","source":"asl/tile/memory-and-data-movement/irregular/ATOM_EXCH.asl","requirements":["PTO-INST-TILE-ATOM-EXCH"],"kind":"static-invariant","summary":"canonical ATOM_EXCH catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory-and-data-movement/irregular
    // block: BSTART.ATOM.EXCH DataType | B.IOT IndexTile, ValueTile, mask=PE_MASK, <last>, ->DstTile<TSize> | B.IOR BaseGPR, zero, zero, ->zero | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000001001') == 107;
    assert TileOperationOfIndex(107) == TileOperation_ATOM_EXCH;
    assert TileHandlerOfIndex(107) == TileHandler_GM_ATOM_VALUE;
    assert TileClassOfIndex(107) == TileClass_MemoryAndDataMovement;
    assert TileEngineOfIndex(107) == TileEngine_TLSU;
    assert InstructionContractOperation_ATOM_EXCH() == TileOperation_ATOM_EXCH;
    assert InstructionContractHandler_ATOM_EXCH() == TileHandler_GM_ATOM_VALUE;
    return 0;
end;
