// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-CMP-GEI-EXEC-001","source":"asl/scalar/bru/CMP.GEI.asl","requirements":["PTO-INST-SCALAR-CMP-GEI"],"kind":"execution","summary":"CMP.GEI executes the canonical comparison, branch, jump, or control effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUExecute_CMP_GEI();
    return 0;
end;
