// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TSUB-STATIC-INVARIANT-001","source":"asl/tile/elementwise-tile-tile/arithmetic/TSUB.asl","requirements":["PTO-INST-TILE-TSUB"],"kind":"static-invariant","summary":"canonical TSUB catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: elementwise-tile-tile/arithmetic
    // block: BSTART.VEC TSUB, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000000001') == 1;
    assert TileOperationOfIndex(1) == TileOperation_TSUB;
    assert TileHandlerOfIndex(1) == TileHandler_ExecuteTileBinary;
    assert TileClassOfIndex(1) == TileClass_ElementwiseTileTile;
    assert TileEngineOfIndex(1) == TileEngine_VEC;
    assert InstructionContractOperation_TSUB() == TileOperation_TSUB;
    assert InstructionContractHandler_TSUB() == TileHandler_ExecuteTileBinary;
    return 0;
end;
