// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-SDI-PO-DECODE-001","source":"asl/scalar/agu/HL.SDI.PO.asl","requirements":["PTO-INST-SCALAR-HL-SDI-PO"],"kind":"decode-positive","summary":"canonical HL.SDI.PO catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000110000010110010000000000111110', 48) == 258;
    assert ScalarOperationOfForm(258) == ScalarOperation_HL_SDI_PO;
    assert ScalarHandlerOfForm(258) == ScalarHandler_ExecuteScalarStore;
    assert InstructionContractOperation_HL_SDI_PO() == ScalarOperation_HL_SDI_PO;
    assert InstructionContractHandler_HL_SDI_PO() == ScalarHandler_ExecuteScalarStore;
    assert DecodeScalarOperandRaw('000000000000000000110000010110010000000000111110', 258, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000110000010110010000000000111110', 258, ScalarField_SrcD) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000110000010110010000000000111110', 258, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000110000010110010000000000111110', 258, ScalarField_simm17) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
