// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SDI-PO-EXEC-001","source":"asl/scalar/agu/HL.SDI.PO.asl","requirements":["PTO-INST-SCALAR-HL-SDI-PO"],"kind":"execution","summary":"HL.SDI.PO executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_SDI_PO();
    return 0;
end;
