// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LHU-ALIAS-001","source":"asl/scalar/agu/LHU.asl","requirements":["PTO-INST-SCALAR-LHU"],"kind":"execution","summary":"LHU covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_LHU();
    return 0;
end;
