// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-HL-SETC-LTI-EXEC-001","source":"asl/scalar/bru/HL.SETC.LTI.asl","requirements":["PTO-INST-SCALAR-HL-SETC-LTI"],"kind":"execution","summary":"HL.SETC.LTI executes the canonical comparison, branch, jump, or control effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUExecute_HL_SETC_LTI();
    return 0;
end;
