// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LDI-ALIAS-001","source":"asl/scalar/agu/HL.LDI.asl","requirements":["PTO-INST-SCALAR-HL-LDI"],"kind":"execution","summary":"HL.LDI covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_HL_LDI();
    return 0;
end;
