// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-HL-BSTART-FP-DECODE-001","source":"asl/block/encoding/HL.BSTART.FP.asl","requirements":["PTO-INST-BLOCK-HL-BSTART-FP"],"kind":"decode-positive","summary":"canonical HL.BSTART.FP catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000110001000000010000000000001110', 48) == 75;
    assert CommandOperationOfForm(75) == CommandOperation_hl_bstart_fp_48_038e2e96cf64;
    assert CommandHandlerOfForm(75) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_HL_BSTART_FP(CommandOperationOfForm(75));
    assert InstructionContractHandler_HL_BSTART_FP() == CommandHandler_ExecuteBundleStart;
    assert DecodeCommandForm('0000000000000000000000000000000000010001000000010000000000001110', 48) == 76;
    assert CommandOperationOfForm(76) == CommandOperation_hl_bstart_fp_48_43530d2ebfae;
    assert CommandHandlerOfForm(76) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_HL_BSTART_FP(CommandOperationOfForm(76));
    assert InstructionContractHandler_HL_BSTART_FP() == CommandHandler_ExecuteBundleStart;
    assert DecodeCommandForm('0000000000000000000000000000000001000001000000010000000000001110', 48) == 77;
    assert CommandOperationOfForm(77) == CommandOperation_hl_bstart_fp_48_81b457553844;
    assert CommandHandlerOfForm(77) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_HL_BSTART_FP(CommandOperationOfForm(77));
    assert InstructionContractHandler_HL_BSTART_FP() == CommandHandler_ExecuteBundleStart;
    assert DecodeCommandForm('0000000000000000000000000000000000100001000000010000000000001110', 48) == 78;
    assert CommandOperationOfForm(78) == CommandOperation_hl_bstart_fp_48_eb938e9200eb;
    assert CommandHandlerOfForm(78) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_HL_BSTART_FP(CommandOperationOfForm(78));
    assert InstructionContractHandler_HL_BSTART_FP() == CommandHandler_ExecuteBundleStart;
    return 0;
end;
