// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-MSET-DECODE-001","source":"asl/block/lifecycle/MSET.asl","requirements":["PTO-INST-BLOCK-MSET"],"kind":"decode-positive","summary":"canonical MSET catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000000000000000001000000110001', 32) == 97;
    assert CommandOperationOfForm(97) == CommandOperation_mset_32_0b932f291932;
    assert CommandHandlerOfForm(97) == CommandHandler_ExecuteMemorySet;
    assert InstructionContractMatches_MSET(CommandOperationOfForm(97));
    assert InstructionContractHandler_MSET() == CommandHandler_ExecuteMemorySet;
    return 0;
end;
