// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-CASW-DECODE-001","source":"asl/scalar/amo/HL.CASW.asl","requirements":["PTO-INST-SCALAR-HL-CASW"],"kind":"decode-positive","summary":"canonical HL.CASW catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('001000000000000001100000000010110000000000001110', 48) == 134;
    assert ScalarOperationOfForm(134) == ScalarOperation_HL_CASW;
    assert ScalarHandlerOfForm(134) == ScalarHandler_CompareAndSwap;
    assert InstructionContractOperation_HL_CASW() == ScalarOperation_HL_CASW;
    assert InstructionContractHandler_HL_CASW() == ScalarHandler_CompareAndSwap;
    assert DecodeScalarOperandRaw('001000000000000001100000000010110000000000001110', 134, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001000000000000001100000000010110000000000001110', 134, ScalarField_SrcD) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001000000000000001100000000010110000000000001110', 134, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001000000000000001100000000010110000000000001110', 134, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001000000000000001100000000010110000000000001110', 134, ScalarField_aq) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001000000000000001100000000010110000000000001110', 134, ScalarField_far) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001000000000000001100000000010110000000000001110', 134, ScalarField_rl) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
