// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-MSCATTER-ADD-STATIC-001","source":"asl/tile/memory-and-data-movement/irregular/MSCATTER_ADD.asl","requirements":["PTO-INST-TILE-MSCATTER-ADD"],"kind":"static-invariant","summary":"canonical MSCATTER_ADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory-and-data-movement/irregular
    // block: BSTART.MSCATTER.ADD DataType | B.IOT IndexTile, ValueTile, mask=PE_MASK, <last> | B.IOR BaseGPR, zero, zero, ->zero | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000010101') == 111;
    assert TileOperationOfIndex(111) == TileOperation_MSCATTER_ADD;
    assert TileHandlerOfIndex(111) == TileHandler_GM_RED_VALUE;
    assert TileClassOfIndex(111) == TileClass_MemoryAndDataMovement;
    assert TileEngineOfIndex(111) == TileEngine_TLSU;
    assert InstructionContractOperation_MSCATTER_ADD() == TileOperation_MSCATTER_ADD;
    assert InstructionContractHandler_MSCATTER_ADD() == TileHandler_GM_RED_VALUE;
    return 0;
end;
