// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LBP-FAULT-001","source":"asl/scalar/agu/HL.LBP.asl","requirements":["PTO-INST-SCALAR-HL-LBP"],"kind":"fault","summary":"HL.LBP rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_HL_LBP();
    return 0;
end;
