// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LBP-ALIAS-001","source":"asl/scalar/agu/HL.LBP.asl","requirements":["PTO-INST-SCALAR-HL-LBP"],"kind":"execution","summary":"HL.LBP covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_HL_LBP();
    return 0;
end;
