// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-PRF-A-EXEC-001","source":"asl/scalar/agu/HL.PRF.A.asl","requirements":["PTO-INST-SCALAR-HL-PRF-A"],"kind":"execution","summary":"HL.PRF.A executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_PRF_A();
    return 0;
end;
