// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LHI-U-FAULT-001","source":"asl/scalar/agu/LHI.U.asl","requirements":["PTO-INST-SCALAR-LHI-U"],"kind":"fault","summary":"LHI.U rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_LHI_U();
    return 0;
end;
