// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-SC-H-DECODE-001","source":"asl/scalar/amo/SC.H.asl","requirements":["PTO-INST-SCALAR-SC-H"],"kind":"decode-positive","summary":"canonical SC.H catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000010000000000000001000000001011', 32) == 382;
    assert ScalarOperationOfForm(382) == ScalarOperation_SC_H;
    assert ScalarHandlerOfForm(382) == ScalarHandler_StoreConditional;
    assert InstructionContractOperation_SC_H() == ScalarOperation_SC_H;
    assert InstructionContractHandler_SC_H() == ScalarHandler_StoreConditional;
    assert DecodeScalarOperandRaw('000000000000000000010000000000000001000000001011', 382, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000000000001000000001011', 382, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000000000001000000001011', 382, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000000000001000000001011', 382, ScalarField_aq) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000000000001000000001011', 382, ScalarField_far) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000010000000000000001000000001011', 382, ScalarField_rl) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
