// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FCVTA-FLAGS-001","source":"asl/scalar/fsu/FCVTA.asl","requirements":["PTO-INST-SCALAR-FCVTA"],"kind":"state-transition","summary":"FCVTA covers sticky floating-point exception-flag accumulation","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUFlags_FCVTA();
    return 0;
end;
