// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FCVTA-ROUND-001","source":"asl/scalar/fsu/FCVTA.asl","requirements":["PTO-INST-SCALAR-FCVTA"],"kind":"boundary","summary":"FCVTA covers all encoded active or fixed rounding-mode selections","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSURounding_FCVTA();
    return 0;
end;
