// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-LHUI-UPR-DECODE-001","source":"asl/scalar/agu/HL.LHUI.UPR.asl","requirements":["PTO-INST-SCALAR-HL-LHUI-UPR"],"kind":"decode-positive","summary":"canonical HL.LHUI.UPR catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000001010000001010010000000000101110', 48) == 197;
    assert ScalarOperationOfForm(197) == ScalarOperation_HL_LHUI_UPR;
    assert ScalarHandlerOfForm(197) == ScalarHandler_ExecuteScalarLoad;
    assert InstructionContractOperation_HL_LHUI_UPR() == ScalarOperation_HL_LHUI_UPR;
    assert InstructionContractHandler_HL_LHUI_UPR() == ScalarHandler_ExecuteScalarLoad;
    assert DecodeScalarOperandRaw('000000000000000001010000001010010000000000101110', 197, ScalarField_RegDst0) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001010000001010010000000000101110', 197, ScalarField_RegDst1) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001010000001010010000000000101110', 197, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001010000001010010000000000101110', 197, ScalarField_simm17) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
