// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TMULS-STATIC-INVARIANT-001","source":"asl/tile/tile-scalar-and-immediate/arithmetic/TMULS.asl","requirements":["PTO-INST-TILE-TMULS"],"kind":"static-invariant","summary":"canonical TMULS catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: tile-scalar-and-immediate/arithmetic
    // block: BSTART.VEC TMULS, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | B.IOR | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000100010') == 27;
    assert TileOperationOfIndex(27) == TileOperation_TMULS;
    assert TileHandlerOfIndex(27) == TileHandler_ExecuteTileScalar;
    assert TileClassOfIndex(27) == TileClass_TileScalarAndImmediate;
    assert TileEngineOfIndex(27) == TileEngine_VEC;
    assert InstructionContractOperation_TMULS() == TileOperation_TMULS;
    assert InstructionContractHandler_TMULS() == TileHandler_ExecuteTileScalar;
    return 0;
end;
