// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SDIP-U-BOUND-001","source":"asl/scalar/agu/HL.SDIP.U.asl","requirements":["PTO-INST-SCALAR-HL-SDIP-U"],"kind":"boundary","summary":"HL.SDIP.U covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_SDIP_U();
    return 0;
end;
