// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SDI-BOUND-001","source":"asl/scalar/agu/HL.SDI.asl","requirements":["PTO-INST-SCALAR-HL-SDI"],"kind":"boundary","summary":"HL.SDI covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_SDI();
    return 0;
end;
