// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SDI-ALIAS-001","source":"asl/scalar/agu/HL.SDI.asl","requirements":["PTO-INST-SCALAR-HL-SDI"],"kind":"execution","summary":"HL.SDI covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_HL_SDI();
    return 0;
end;
