// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-LB-PO-DECODE-001","source":"asl/scalar/agu/HL.LB.PO.asl","requirements":["PTO-INST-SCALAR-HL-LB-PO"],"kind":"decode-positive","summary":"canonical HL.LB.PO catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000010010000000000111110', 48) == 142;
    assert ScalarOperationOfForm(142) == ScalarOperation_HL_LB_PO;
    assert ScalarHandlerOfForm(142) == ScalarHandler_ExecuteScalarLoad;
    assert InstructionContractOperation_HL_LB_PO() == ScalarOperation_HL_LB_PO;
    assert InstructionContractHandler_HL_LB_PO() == ScalarHandler_ExecuteScalarLoad;
    assert InstructionContractAGUAction_HL_LB_PO() == ScalarAGU_Load;
    assert InstructionContractAGUAddressKind_HL_LB_PO() == ScalarAGU_Register;
    assert InstructionContractAGUSizeBytes_HL_LB_PO() == 1;
    assert InstructionContractAGUOffsetScale_HL_LB_PO() == 0;
    assert InstructionContractAGUUpdateMode_HL_LB_PO() == AddressUpdate_PostIndex;
    assert InstructionContractAGUSignedLoad_HL_LB_PO() == TRUE;
    assert InstructionContractAGUPrefetchReturnsAddress_HL_LB_PO() == FALSE;
    assert DecodeScalarOperandRaw('000000000000000000000000000010010000000000111110', 142, ScalarField_RegDst0) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000010010000000000111110', 142, ScalarField_RegDst1) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000010010000000000111110', 142, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000010010000000000111110', 142, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000010010000000000111110', 142, ScalarField_SrcRType) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000010010000000000111110', 142, ScalarField_shamt) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
