// PTO-TEST: {"id":"PTO-AVS-BLOCK-RANGE-OPERATION-MATRIX-033","source":"asl/block/model/operands/subview-descriptor.asl","requirements":["PTO-B-SUBVIEW-DESCRIPTOR-001","PTO-BLOCK-TILE-OPERATION-APPLICABILITY-001","PTO-B-ASSEMBLE-PRODUCER-EFFECT-ELIGIBILITY-001"],"kind":"execution","summary":"Generated decoded operation-role cases exercise every required source and destination role through normal dispatch.","pass_condition":"Every case binds its authoritative fixture recipe and catalog-required operands/attributes, reaches normal modifier and applicability preflight, then asserts either its exact normal observable or its exact pre-effect fault.","related_sources":["asl/block/model/operands/subview-descriptor.asl","asl/block/model/operands/range-modifiers.asl","asl/block/model/operands/portable-carriers.asl"]}
// Generated by scripts/generate-bundle-operation-matrix.py; cases: RANGE-MATRIX-CASE-0129, RANGE-MATRIX-CASE-0130, RANGE-MATRIX-CASE-0131, RANGE-MATRIX-CASE-0132
// RANGE-MATRIX-CASE-0129 TROWARGMAX source0 -> case_0129_normal_commit
func RunCase_0129() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 1 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x24c19181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0018de13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(52);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(52);
    assert SelectedBundleClosedUnarySchemaLegal(52);
    assert SelectedBundleClosedTFMASchemaLegal(52);
    assert SelectedBundleClosedQuantizationSchemaLegal(52);
    assert SelectedBundleClosedGenerationSchemaLegal(52);
    assert SelectedBundleClosedHistogramSchemaLegal(52);
    assert SelectedBundleClosedReductionSchemaLegal(52);
    assert SelectedBundleClosedSortingSchemaLegal(52);
    assert SelectedBundleClosedPartialSchemaLegal(52);
    assert SelectedBundleClosedExpansionSchemaLegal(52);
    assert SelectedBundleClosedTCVTSchemaLegal(52);
    assert SelectedBundleClosedTCMPSchemaLegal(52);
    assert SelectedBundleClosedTSELSchemaLegal(52);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(52);
    assert SelectedBundleClosedTCMPSSchemaLegal(52);
    assert SelectedBundleClosedTSELSSchemaLegal(52);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(52);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0130 TROWARGMAX destination0 -> case_0130_normal_commit
func RunCase_0130() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 0 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x24c19181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0018de13, 32);
    assert bind_0 == CommandExecution_Executed;
    let assemble_0 = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(52);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(52);
    assert SelectedBundleClosedUnarySchemaLegal(52);
    assert SelectedBundleClosedTFMASchemaLegal(52);
    assert SelectedBundleClosedQuantizationSchemaLegal(52);
    assert SelectedBundleClosedGenerationSchemaLegal(52);
    assert SelectedBundleClosedHistogramSchemaLegal(52);
    assert SelectedBundleClosedReductionSchemaLegal(52);
    assert SelectedBundleClosedSortingSchemaLegal(52);
    assert SelectedBundleClosedPartialSchemaLegal(52);
    assert SelectedBundleClosedExpansionSchemaLegal(52);
    assert SelectedBundleClosedTCVTSchemaLegal(52);
    assert SelectedBundleClosedTCMPSchemaLegal(52);
    assert SelectedBundleClosedTSELSchemaLegal(52);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(52);
    assert SelectedBundleClosedTCMPSSchemaLegal(52);
    assert SelectedBundleClosedTSELSSchemaLegal(52);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(52);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    let completed_writer_0 = CompleteBundleLocalGenerationWriterEvent(
        BundleLocalGenerationSlot(0, '1111'), _BundleExecutionDomainToken,
        0, BundleLocalGenerationCellCount(1));
    assert completed_writer_0;
    assert _LocalGenerations[[BundleLocalGenerationSlot(0, '1111')]].published;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0131 TROWARGMIN source0 -> case_0131_normal_commit
func RunCase_0131() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 1 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x24d19181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0018de13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(53);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(53);
    assert SelectedBundleClosedUnarySchemaLegal(53);
    assert SelectedBundleClosedTFMASchemaLegal(53);
    assert SelectedBundleClosedQuantizationSchemaLegal(53);
    assert SelectedBundleClosedGenerationSchemaLegal(53);
    assert SelectedBundleClosedHistogramSchemaLegal(53);
    assert SelectedBundleClosedReductionSchemaLegal(53);
    assert SelectedBundleClosedSortingSchemaLegal(53);
    assert SelectedBundleClosedPartialSchemaLegal(53);
    assert SelectedBundleClosedExpansionSchemaLegal(53);
    assert SelectedBundleClosedTCVTSchemaLegal(53);
    assert SelectedBundleClosedTCMPSchemaLegal(53);
    assert SelectedBundleClosedTSELSchemaLegal(53);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(53);
    assert SelectedBundleClosedTCMPSSchemaLegal(53);
    assert SelectedBundleClosedTSELSSchemaLegal(53);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(53);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0132 TROWARGMIN destination0 -> case_0132_normal_commit
func RunCase_0132() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 0 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x24d19181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0018de13, 32);
    assert bind_0 == CommandExecution_Executed;
    let assemble_0 = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(53);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(53);
    assert SelectedBundleClosedUnarySchemaLegal(53);
    assert SelectedBundleClosedTFMASchemaLegal(53);
    assert SelectedBundleClosedQuantizationSchemaLegal(53);
    assert SelectedBundleClosedGenerationSchemaLegal(53);
    assert SelectedBundleClosedHistogramSchemaLegal(53);
    assert SelectedBundleClosedReductionSchemaLegal(53);
    assert SelectedBundleClosedSortingSchemaLegal(53);
    assert SelectedBundleClosedPartialSchemaLegal(53);
    assert SelectedBundleClosedExpansionSchemaLegal(53);
    assert SelectedBundleClosedTCVTSchemaLegal(53);
    assert SelectedBundleClosedTCMPSchemaLegal(53);
    assert SelectedBundleClosedTSELSchemaLegal(53);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(53);
    assert SelectedBundleClosedTCMPSSchemaLegal(53);
    assert SelectedBundleClosedTSELSSchemaLegal(53);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(53);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    let completed_writer_0 = CompleteBundleLocalGenerationWriterEvent(
        BundleLocalGenerationSlot(0, '1111'), _BundleExecutionDomainToken,
        0, BundleLocalGenerationCellCount(1));
    assert completed_writer_0;
    assert _LocalGenerations[[BundleLocalGenerationSlot(0, '1111')]].published;
    return TRUE;
end;

func main() => integer
begin
    let result_0129 = RunCase_0129();
    assert result_0129;
    let result_0130 = RunCase_0130();
    assert result_0130;
    let result_0131 = RunCase_0131();
    assert result_0131;
    let result_0132 = RunCase_0132();
    assert result_0132;
    return 0;
end;
