// PTO-TEST: {"id":"PTO-AVS-BLOCK-RANGE-OPERATION-MATRIX-042","source":"asl/block/model/operands/subview-descriptor.asl","requirements":["PTO-B-SUBVIEW-DESCRIPTOR-001","PTO-BLOCK-TILE-OPERATION-APPLICABILITY-001","PTO-B-ASSEMBLE-PRODUCER-EFFECT-ELIGIBILITY-001"],"kind":"execution","summary":"Generated decoded operation-role cases exercise every required source and destination role through normal dispatch.","pass_condition":"Every case binds its authoritative fixture recipe and catalog-required operands/attributes, reaches normal modifier and applicability preflight, then asserts either its exact normal observable or its exact pre-effect fault.","related_sources":["asl/block/model/operands/subview-descriptor.asl","asl/block/model/operands/range-modifiers.asl","asl/block/model/operands/portable-carriers.asl"]}
// Generated by scripts/generate-bundle-operation-matrix.py; cases: RANGE-MATRIX-CASE-0165, RANGE-MATRIX-CASE-0166, RANGE-MATRIX-CASE-0167, RANGE-MATRIX-CASE-0168
// RANGE-MATRIX-CASE-0165 TCOLARGMAX destination0 -> case_0165_normal_commit
func RunCase_0165() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 0 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x25c19181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0018de13, 32);
    assert bind_0 == CommandExecution_Executed;
    let assemble_0 = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(66);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedSchemasLegal(66);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    let completed_writer_0 = CompleteBundleLocalGenerationWriterEvent(
        BundleLocalGenerationSlot(0, '1111'), _BundleExecutionDomainToken,
        0, BundleLocalGenerationCellCount(1));
    assert completed_writer_0;
    assert _LocalGenerations[[BundleLocalGenerationSlot(0, '1111')]].published;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0166 TCOLARGMIN source0 -> case_0166_normal_commit
func RunCase_0166() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 1 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x25d19181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0018de13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(67);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedSchemasLegal(67);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0167 TCOLARGMIN destination0 -> case_0167_normal_commit
func RunCase_0167() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 0 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x25d19181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0018de13, 32);
    assert bind_0 == CommandExecution_Executed;
    let assemble_0 = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(67);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedSchemasLegal(67);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    let completed_writer_0 = CompleteBundleLocalGenerationWriterEvent(
        BundleLocalGenerationSlot(0, '1111'), _BundleExecutionDomainToken,
        0, BundleLocalGenerationCellCount(1));
    assert completed_writer_0;
    assert _LocalGenerations[[BundleLocalGenerationSlot(0, '1111')]].published;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0168 TCONCAT source0 -> case_0168_normal_commit
func RunCase_0168() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 1 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                2, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x26019181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0818ce13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(68);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedSchemasLegal(68);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

func main() => integer
begin
    let result_0165 = RunCase_0165();
    assert result_0165;
    let result_0166 = RunCase_0166();
    assert result_0166;
    let result_0167 = RunCase_0167();
    assert result_0167;
    let result_0168 = RunCase_0168();
    assert result_0168;
    return 0;
end;
