// PTO-TEST: {"id":"PTO-AVS-BLOCK-RANGE-OPERATION-MATRIX-012","source":"asl/block/model/operands/subview-descriptor.asl","requirements":["PTO-B-SUBVIEW-DESCRIPTOR-001","PTO-BLOCK-TILE-OPERATION-APPLICABILITY-001","PTO-B-ASSEMBLE-PRODUCER-EFFECT-ELIGIBILITY-001"],"kind":"execution","summary":"Generated decoded operation-role cases exercise every required source and destination role through normal dispatch.","pass_condition":"Every case binds its authoritative fixture recipe and catalog-required operands/attributes, reaches normal modifier and applicability preflight, then asserts either its exact normal observable or its exact pre-effect fault.","related_sources":["asl/block/model/operands/subview-descriptor.asl","asl/block/model/operands/range-modifiers.asl","asl/block/model/operands/portable-carriers.asl"]}
// Generated by scripts/generate-bundle-operation-matrix.py; cases: RANGE-MATRIX-CASE-0045, RANGE-MATRIX-CASE-0046, RANGE-MATRIX-CASE-0047, RANGE-MATRIX-CASE-0048
// RANGE-MATRIX-CASE-0045 TNEG destination0 -> case_0045_normal_commit
func RunCase_0045() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 0 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x21119181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0018de13, 32);
    assert bind_0 == CommandExecution_Executed;
    let assemble_0 = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(15);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    let completed_writer_0 = CompleteBundleLocalGenerationWriterEvent(
        BundleLocalGenerationSlot(0, '1111'), _BundleExecutionDomainToken,
        0, BundleLocalGenerationCellCount(1));
    assert completed_writer_0;
    assert _LocalGenerations[[BundleLocalGenerationSlot(0, '1111')]].published;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0046 TEXP source0 -> case_0046_normal_commit
func RunCase_0046() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 1 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x21219181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0018de13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(16);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0047 TEXP destination0 -> case_0047_normal_commit
func RunCase_0047() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 0 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x21219181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0018de13, 32);
    assert bind_0 == CommandExecution_Executed;
    let assemble_0 = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(16);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    let completed_writer_0 = CompleteBundleLocalGenerationWriterEvent(
        BundleLocalGenerationSlot(0, '1111'), _BundleExecutionDomainToken,
        0, BundleLocalGenerationCellCount(1));
    assert completed_writer_0;
    assert _LocalGenerations[[BundleLocalGenerationSlot(0, '1111')]].published;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0048 TLOG source0 -> case_0048_normal_commit
func RunCase_0048() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 1 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x21319181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0018de13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(17);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

func main() => integer
begin
    let result_0045 = RunCase_0045();
    assert result_0045;
    let result_0046 = RunCase_0046();
    assert result_0046;
    let result_0047 = RunCase_0047();
    assert result_0047;
    let result_0048 = RunCase_0048();
    assert result_0048;
    return 0;
end;
