// PTO-TEST: {"id":"PTO-AVS-BLOCK-RANGE-OPERATION-MATRIX-176","source":"asl/block/model/operands/subview-descriptor.asl","requirements":["PTO-B-SUBVIEW-DESCRIPTOR-001","PTO-BLOCK-TILE-OPERATION-APPLICABILITY-001","PTO-B-ASSEMBLE-PRODUCER-EFFECT-ELIGIBILITY-001"],"kind":"execution","summary":"One decoded operation-role case exercises its required source or destination role through normal dispatch.","pass_condition":"The case binds its authoritative fixture recipe and catalog-required operands/attributes, reaches normal modifier and applicability preflight, then asserts its exact normal observable or pre-effect fault.","related_sources":["asl/block/model/operands/subview-descriptor.asl","asl/block/model/operands/range-modifiers.asl","asl/block/model/operands/portable-carriers.asl"]}
// Generated by scripts/generate-bundle-operation-matrix.py; case: RANGE-MATRIX-CASE-0176
// RANGE-MATRIX-CASE-0176 TLOAD destination0 -> case_0176_normal_commit
func RunCase_0176() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN});
    WriteGPR(3, Zeros{PTO_XLEN} + 8);
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    _Memory[[0]] = Zeros{8} + 0x2a;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x20011181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let ior = ExecuteCommandInstruction(Zeros{64} + 0x00310013, 32);
    assert ior == CommandExecution_Executed;
    let shared = ExecuteCommandInstruction(Zeros{64} + 0x01009e13, 32);
    assert shared == CommandExecution_Executed;
    let assemble = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble == CommandExecution_Executed;
    let completed = ExecuteBundleTileOperation();
    assert completed && _LastFault == Fault_None;
    assert SharedTileFullyInitialized((Zeros{6} + 16) as SharedTileID);
    assert ReadSharedTileWord((Zeros{6} + 16) as SharedTileID, 0) == Zeros{PTO_XLEN} + 0x2a;
    return TRUE;
end;

func main() => integer
begin
    let result_0176 = RunCase_0176();
    assert result_0176;
    return 0;
end;
