// PTO-TEST: {"id":"PTO-AVS-BLOCK-RANGE-OPERATION-MATRIX-063","source":"asl/block/model/operands/subview-descriptor.asl","requirements":["PTO-B-SUBVIEW-DESCRIPTOR-001","PTO-BLOCK-TILE-OPERATION-APPLICABILITY-001","PTO-B-ASSEMBLE-PRODUCER-EFFECT-ELIGIBILITY-001"],"kind":"execution","summary":"Generated decoded operation-role cases exercise every required source and destination role through normal dispatch.","pass_condition":"Every case binds its authoritative fixture recipe and catalog-required operands/attributes, reaches normal modifier and applicability preflight, then asserts either its exact normal observable or its exact pre-effect fault.","related_sources":["asl/block/model/operands/subview-descriptor.asl","asl/block/model/operands/range-modifiers.asl","asl/block/model/operands/portable-carriers.asl"]}
// Generated by scripts/generate-bundle-operation-matrix.py; cases: RANGE-MATRIX-CASE-0249, RANGE-MATRIX-CASE-0250, RANGE-MATRIX-CASE-0251, RANGE-MATRIX-CASE-0252
// RANGE-MATRIX-CASE-0249 TMATMUL_MX source2 -> case_0249_normal_commit
func RunCase_0249() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        let configured = if tile MOD 2 == 1 then
            ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else TileDataType_E4M3)), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111')
            else ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else TileDataType_E4M3)), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111');
        assert configured;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x38431181, 32);
    assert started == CommandExecution_Executed;
    let fpatr = ExecuteCommandInstruction(Zeros{64} + 0x00002023, 32);
    assert fpatr == CommandExecution_Executed;
    let datr = ExecuteCommandInstruction(Zeros{64} + 0x00701023, 32);
    assert datr == CommandExecution_Executed;
    let dim_100043 = ExecuteCommandInstruction(Zeros{64} + 0x00100043, 32);
    assert dim_100043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_102043 = ExecuteCommandInstruction(Zeros{64} + 0x00102043, 32);
    assert dim_102043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x08104e13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    let modifier_0_1 = ExecuteCommandInstruction(Zeros{64} + 0x800000d3, 32);
    assert modifier_0_1 == CommandExecution_Executed;
    let bind_1 = ExecuteCommandInstruction(Zeros{64} + 0x1038ce13, 32);
    assert bind_1 == CommandExecution_Executed;
    let modifier_1_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_1_0 == CommandExecution_Executed;
    let modifier_1_1 = ExecuteCommandInstruction(Zeros{64} + 0x800000d3, 32);
    assert modifier_1_1 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(100);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0250 TMATMUL_MX source3 -> case_0250_normal_commit
func RunCase_0250() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        let configured = if tile MOD 2 == 1 then
            ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else TileDataType_E4M3)), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111')
            else ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else TileDataType_E4M3)), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111');
        assert configured;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x38431181, 32);
    assert started == CommandExecution_Executed;
    let fpatr = ExecuteCommandInstruction(Zeros{64} + 0x00002023, 32);
    assert fpatr == CommandExecution_Executed;
    let datr = ExecuteCommandInstruction(Zeros{64} + 0x00701023, 32);
    assert datr == CommandExecution_Executed;
    let dim_100043 = ExecuteCommandInstruction(Zeros{64} + 0x00100043, 32);
    assert dim_100043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_102043 = ExecuteCommandInstruction(Zeros{64} + 0x00102043, 32);
    assert dim_102043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x08104e13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    let modifier_0_1 = ExecuteCommandInstruction(Zeros{64} + 0x800000d3, 32);
    assert modifier_0_1 == CommandExecution_Executed;
    let bind_1 = ExecuteCommandInstruction(Zeros{64} + 0x1038ce13, 32);
    assert bind_1 == CommandExecution_Executed;
    let modifier_1_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_1_0 == CommandExecution_Executed;
    let modifier_1_1 = ExecuteCommandInstruction(Zeros{64} + 0x800000d3, 32);
    assert modifier_1_1 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(100);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0251 TMATMUL_MX destination0 -> case_0251_normal_commit
func RunCase_0251() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        let configured = if tile MOD 2 == 1 then
            ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else TileDataType_E4M3)), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111')
            else ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else TileDataType_E4M3)), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111');
        assert configured;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x38431181, 32);
    assert started == CommandExecution_Executed;
    let fpatr = ExecuteCommandInstruction(Zeros{64} + 0x00002023, 32);
    assert fpatr == CommandExecution_Executed;
    let datr = ExecuteCommandInstruction(Zeros{64} + 0x00701023, 32);
    assert datr == CommandExecution_Executed;
    let dim_100043 = ExecuteCommandInstruction(Zeros{64} + 0x00100043, 32);
    assert dim_100043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_102043 = ExecuteCommandInstruction(Zeros{64} + 0x00102043, 32);
    assert dim_102043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x08104e13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    let modifier_0_1 = ExecuteCommandInstruction(Zeros{64} + 0x800000d3, 32);
    assert modifier_0_1 == CommandExecution_Executed;
    let bind_1 = ExecuteCommandInstruction(Zeros{64} + 0x1038ce13, 32);
    assert bind_1 == CommandExecution_Executed;
    let modifier_1_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_1_0 == CommandExecution_Executed;
    let modifier_1_1 = ExecuteCommandInstruction(Zeros{64} + 0x800000d3, 32);
    assert modifier_1_1 == CommandExecution_Executed;
    let assemble_1 = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble_1 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(100);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    let completed_writer = CompleteBundleLocalGenerationWriterEvent(
        BundleLocalGenerationSlot(0, '1111'), _BundleExecutionDomainToken,
        0, BundleLocalGenerationCellCount(1));
    assert completed_writer;
    assert _LocalGenerations[[BundleLocalGenerationSlot(0, '1111')]].published;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0252 TMATMUL_MX_BIAS source0 -> case_0252_normal_commit
func RunCase_0252() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        let configured = if tile MOD 2 == 1 then
            ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else (if tile == 5 then TileDataType_FP32 else TileDataType_E4M3))), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111')
            else ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else (if tile == 5 then TileDataType_FP32 else TileDataType_E4M3))), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111');
        assert configured;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x38531181, 32);
    assert started == CommandExecution_Executed;
    let fpatr = ExecuteCommandInstruction(Zeros{64} + 0x00002023, 32);
    assert fpatr == CommandExecution_Executed;
    let datr = ExecuteCommandInstruction(Zeros{64} + 0x00701023, 32);
    assert datr == CommandExecution_Executed;
    let dim_100043 = ExecuteCommandInstruction(Zeros{64} + 0x00100043, 32);
    assert dim_100043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_102043 = ExecuteCommandInstruction(Zeros{64} + 0x00102043, 32);
    assert dim_102043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x08104e13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    let modifier_0_1 = ExecuteCommandInstruction(Zeros{64} + 0x800000d3, 32);
    assert modifier_0_1 == CommandExecution_Executed;
    let bind_1 = ExecuteCommandInstruction(Zeros{64} + 0x10304e13, 32);
    assert bind_1 == CommandExecution_Executed;
    let modifier_1_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_1_0 == CommandExecution_Executed;
    let modifier_1_1 = ExecuteCommandInstruction(Zeros{64} + 0x800000d3, 32);
    assert modifier_1_1 == CommandExecution_Executed;
    let bind_2 = ExecuteCommandInstruction(Zeros{64} + 0x0058de13, 32);
    assert bind_2 == CommandExecution_Executed;
    let modifier_2_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_2_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(101);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

func main() => integer
begin
    let result_0249 = RunCase_0249();
    assert result_0249;
    let result_0250 = RunCase_0250();
    assert result_0250;
    let result_0251 = RunCase_0251();
    assert result_0251;
    let result_0252 = RunCase_0252();
    assert result_0252;
    return 0;
end;
