// PTO-TEST: {"id":"PTO-AVS-BLOCK-RANGE-OPERATION-MATRIX-004","source":"asl/block/model/operands/subview-descriptor.asl","requirements":["PTO-B-SUBVIEW-DESCRIPTOR-001","PTO-BLOCK-TILE-OPERATION-APPLICABILITY-001","PTO-B-ASSEMBLE-PRODUCER-EFFECT-ELIGIBILITY-001"],"kind":"execution","summary":"Generated decoded operation-role cases exercise every required source and destination role through normal dispatch.","pass_condition":"Every case binds its authoritative fixture recipe and catalog-required operands/attributes, reaches normal modifier and applicability preflight, then asserts either its exact normal observable or its exact pre-effect fault.","related_sources":["asl/block/model/operands/subview-descriptor.asl","asl/block/model/operands/range-modifiers.asl","asl/block/model/operands/portable-carriers.asl"]}
// Generated by scripts/generate-bundle-operation-matrix.py; cases: RANGE-MATRIX-CASE-0013, RANGE-MATRIX-CASE-0014, RANGE-MATRIX-CASE-0015, RANGE-MATRIX-CASE-0016
// RANGE-MATRIX-CASE-0013 TREM source0 -> case_0013_normal_commit
func RunCase_0013() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 1 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x20419181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0818ce13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(4);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(4);
    assert SelectedBundleClosedUnarySchemaLegal(4);
    assert SelectedBundleClosedTFMASchemaLegal(4);
    assert SelectedBundleClosedQuantizationSchemaLegal(4);
    assert SelectedBundleClosedGenerationSchemaLegal(4);
    assert SelectedBundleClosedHistogramSchemaLegal(4);
    assert SelectedBundleClosedReductionSchemaLegal(4);
    assert SelectedBundleClosedSortingSchemaLegal(4);
    assert SelectedBundleClosedPartialSchemaLegal(4);
    assert SelectedBundleClosedExpansionSchemaLegal(4);
    assert SelectedBundleClosedTCVTSchemaLegal(4);
    assert SelectedBundleClosedTCMPSchemaLegal(4);
    assert SelectedBundleClosedTSELSchemaLegal(4);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(4);
    assert SelectedBundleClosedTCMPSSchemaLegal(4);
    assert SelectedBundleClosedTSELSSchemaLegal(4);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(4);
    assert SelectedBundleTileMasksLegal();
    assert SelectedBundleClosedBinarySchemaLegal(4);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0014 TREM source1 -> case_0014_normal_commit
func RunCase_0014() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 2 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x20419181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0818ce13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_1 = ExecuteCommandInstruction(Zeros{64} + 0x800000d3, 32);
    assert modifier_0_1 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(4);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(4);
    assert SelectedBundleClosedUnarySchemaLegal(4);
    assert SelectedBundleClosedTFMASchemaLegal(4);
    assert SelectedBundleClosedQuantizationSchemaLegal(4);
    assert SelectedBundleClosedGenerationSchemaLegal(4);
    assert SelectedBundleClosedHistogramSchemaLegal(4);
    assert SelectedBundleClosedReductionSchemaLegal(4);
    assert SelectedBundleClosedSortingSchemaLegal(4);
    assert SelectedBundleClosedPartialSchemaLegal(4);
    assert SelectedBundleClosedExpansionSchemaLegal(4);
    assert SelectedBundleClosedTCVTSchemaLegal(4);
    assert SelectedBundleClosedTCMPSchemaLegal(4);
    assert SelectedBundleClosedTSELSchemaLegal(4);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(4);
    assert SelectedBundleClosedTCMPSSchemaLegal(4);
    assert SelectedBundleClosedTSELSSchemaLegal(4);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(4);
    assert SelectedBundleTileMasksLegal();
    assert SelectedBundleClosedBinarySchemaLegal(4);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0015 TREM destination0 -> case_0015_normal_commit
func RunCase_0015() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 0 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x20419181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0818ce13, 32);
    assert bind_0 == CommandExecution_Executed;
    let assemble_0 = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(4);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(4);
    assert SelectedBundleClosedUnarySchemaLegal(4);
    assert SelectedBundleClosedTFMASchemaLegal(4);
    assert SelectedBundleClosedQuantizationSchemaLegal(4);
    assert SelectedBundleClosedGenerationSchemaLegal(4);
    assert SelectedBundleClosedHistogramSchemaLegal(4);
    assert SelectedBundleClosedReductionSchemaLegal(4);
    assert SelectedBundleClosedSortingSchemaLegal(4);
    assert SelectedBundleClosedPartialSchemaLegal(4);
    assert SelectedBundleClosedExpansionSchemaLegal(4);
    assert SelectedBundleClosedTCVTSchemaLegal(4);
    assert SelectedBundleClosedTCMPSchemaLegal(4);
    assert SelectedBundleClosedTSELSchemaLegal(4);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(4);
    assert SelectedBundleClosedTCMPSSchemaLegal(4);
    assert SelectedBundleClosedTSELSSchemaLegal(4);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(4);
    assert SelectedBundleTileMasksLegal();
    assert SelectedBundleClosedBinarySchemaLegal(4);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    let completed_writer_0 = CompleteBundleLocalGenerationWriterEvent(
        BundleLocalGenerationSlot(0, '1111'), _BundleExecutionDomainToken,
        0, BundleLocalGenerationCellCount(1));
    assert completed_writer_0;
    assert _LocalGenerations[[BundleLocalGenerationSlot(0, '1111')]].published;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0016 TAND source0 -> case_0016_normal_commit
func RunCase_0016() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 1 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_U8, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                32, 4, 1,
                4, TileDataType_U8,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0xd8619181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0818ce13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(5);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(5);
    assert SelectedBundleClosedUnarySchemaLegal(5);
    assert SelectedBundleClosedTFMASchemaLegal(5);
    assert SelectedBundleClosedQuantizationSchemaLegal(5);
    assert SelectedBundleClosedGenerationSchemaLegal(5);
    assert SelectedBundleClosedHistogramSchemaLegal(5);
    assert SelectedBundleClosedReductionSchemaLegal(5);
    assert SelectedBundleClosedSortingSchemaLegal(5);
    assert SelectedBundleClosedPartialSchemaLegal(5);
    assert SelectedBundleClosedExpansionSchemaLegal(5);
    assert SelectedBundleClosedTCVTSchemaLegal(5);
    assert SelectedBundleClosedTCMPSchemaLegal(5);
    assert SelectedBundleClosedTSELSchemaLegal(5);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(5);
    assert SelectedBundleClosedTCMPSSchemaLegal(5);
    assert SelectedBundleClosedTSELSSchemaLegal(5);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(5);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

func main() => integer
begin
    let result_0013 = RunCase_0013();
    assert result_0013;
    let result_0014 = RunCase_0014();
    assert result_0014;
    let result_0015 = RunCase_0015();
    assert result_0015;
    let result_0016 = RunCase_0016();
    assert result_0016;
    return 0;
end;
