// PTO-TEST: {"id":"PTO-AVS-BLOCK-RANGE-OPERATION-MATRIX-069","source":"asl/block/model/operands/subview-descriptor.asl","requirements":["PTO-B-SUBVIEW-DESCRIPTOR-001","PTO-BLOCK-TILE-OPERATION-APPLICABILITY-001","PTO-B-ASSEMBLE-PRODUCER-EFFECT-ELIGIBILITY-001"],"kind":"execution","summary":"Generated decoded operation-role cases exercise every required source and destination role through normal dispatch.","pass_condition":"Every case binds its authoritative fixture recipe and catalog-required operands/attributes, reaches normal modifier and applicability preflight, then asserts either its exact normal observable or its exact pre-effect fault.","related_sources":["asl/block/model/operands/subview-descriptor.asl","asl/block/model/operands/range-modifiers.asl","asl/block/model/operands/portable-carriers.asl"]}
// Generated by scripts/generate-bundle-operation-matrix.py; cases: RANGE-MATRIX-CASE-0273, RANGE-MATRIX-CASE-0274, RANGE-MATRIX-CASE-0275, RANGE-MATRIX-CASE-0276
// RANGE-MATRIX-CASE-0273 TGEMV_ACC source2 -> case_0273_normal_commit
func RunCase_0273() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 0 to 8 looplimit 9 do
        let configured = if tile MOD 2 == 1 then
            ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 1 then TileDataType_FP32 else TileDataType_FP16), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111')
            else ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 1 then TileDataType_FP32 else TileDataType_FP16), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111');
        assert configured;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x21231181, 32);
    assert started == CommandExecution_Executed;
    let fpatr = ExecuteCommandInstruction(Zeros{64} + 0x00002023, 32);
    assert fpatr == CommandExecution_Executed;
    let datr = ExecuteCommandInstruction(Zeros{64} + 0x00401023, 32);
    assert datr == CommandExecution_Executed;
    let dim_100043 = ExecuteCommandInstruction(Zeros{64} + 0x00100043, 32);
    assert dim_100043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_102043 = ExecuteCommandInstruction(Zeros{64} + 0x00102043, 32);
    assert dim_102043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x08104e13, 32);
    assert bind_0 == CommandExecution_Executed;
    let bind_1 = ExecuteCommandInstruction(Zeros{64} + 0x0038de13, 32);
    assert bind_1 == CommandExecution_Executed;
    let modifier_1_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_1_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(105);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(105);
    assert SelectedBundleClosedUnarySchemaLegal(105);
    assert SelectedBundleClosedTFMASchemaLegal(105);
    assert SelectedBundleClosedQuantizationSchemaLegal(105);
    assert SelectedBundleClosedGenerationSchemaLegal(105);
    assert SelectedBundleClosedHistogramSchemaLegal(105);
    assert SelectedBundleClosedReductionSchemaLegal(105);
    assert SelectedBundleClosedSortingSchemaLegal(105);
    assert SelectedBundleClosedPartialSchemaLegal(105);
    assert SelectedBundleClosedExpansionSchemaLegal(105);
    assert SelectedBundleClosedTCVTSchemaLegal(105);
    assert SelectedBundleClosedTCMPSchemaLegal(105);
    assert SelectedBundleClosedTSELSchemaLegal(105);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(105);
    assert SelectedBundleClosedTCMPSSchemaLegal(105);
    assert SelectedBundleClosedTSELSSchemaLegal(105);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(105);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0274 TGEMV_ACC destination0 -> case_0274_normal_commit
func RunCase_0274() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 0 to 8 looplimit 9 do
        let configured = if tile MOD 2 == 1 then
            ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 1 then TileDataType_FP32 else TileDataType_FP16), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111')
            else ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 1 then TileDataType_FP32 else TileDataType_FP16), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111');
        assert configured;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x21231181, 32);
    assert started == CommandExecution_Executed;
    let fpatr = ExecuteCommandInstruction(Zeros{64} + 0x00002023, 32);
    assert fpatr == CommandExecution_Executed;
    let datr = ExecuteCommandInstruction(Zeros{64} + 0x00401023, 32);
    assert datr == CommandExecution_Executed;
    let dim_100043 = ExecuteCommandInstruction(Zeros{64} + 0x00100043, 32);
    assert dim_100043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_102043 = ExecuteCommandInstruction(Zeros{64} + 0x00102043, 32);
    assert dim_102043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x08104e13, 32);
    assert bind_0 == CommandExecution_Executed;
    let bind_1 = ExecuteCommandInstruction(Zeros{64} + 0x0038de13, 32);
    assert bind_1 == CommandExecution_Executed;
    let assemble_1 = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble_1 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(105);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(105);
    assert SelectedBundleClosedUnarySchemaLegal(105);
    assert SelectedBundleClosedTFMASchemaLegal(105);
    assert SelectedBundleClosedQuantizationSchemaLegal(105);
    assert SelectedBundleClosedGenerationSchemaLegal(105);
    assert SelectedBundleClosedHistogramSchemaLegal(105);
    assert SelectedBundleClosedReductionSchemaLegal(105);
    assert SelectedBundleClosedSortingSchemaLegal(105);
    assert SelectedBundleClosedPartialSchemaLegal(105);
    assert SelectedBundleClosedExpansionSchemaLegal(105);
    assert SelectedBundleClosedTCVTSchemaLegal(105);
    assert SelectedBundleClosedTCMPSchemaLegal(105);
    assert SelectedBundleClosedTSELSchemaLegal(105);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(105);
    assert SelectedBundleClosedTCMPSSchemaLegal(105);
    assert SelectedBundleClosedTSELSSchemaLegal(105);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(105);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    let completed_writer_0 = CompleteBundleLocalGenerationWriterEvent(
        BundleLocalGenerationSlot(0, '1111'), _BundleExecutionDomainToken,
        0, BundleLocalGenerationCellCount(1));
    assert completed_writer_0;
    assert _LocalGenerations[[BundleLocalGenerationSlot(0, '1111')]].published;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0275 TGEMV_MX source0 -> case_0275_normal_commit
func RunCase_0275() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        let configured = if tile MOD 2 == 1 then
            ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else TileDataType_E4M3)), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111')
            else ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else TileDataType_E4M3)), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111');
        assert configured;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x39431181, 32);
    assert started == CommandExecution_Executed;
    let fpatr = ExecuteCommandInstruction(Zeros{64} + 0x00002023, 32);
    assert fpatr == CommandExecution_Executed;
    let datr = ExecuteCommandInstruction(Zeros{64} + 0x00701023, 32);
    assert datr == CommandExecution_Executed;
    let dim_100043 = ExecuteCommandInstruction(Zeros{64} + 0x00100043, 32);
    assert dim_100043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_102043 = ExecuteCommandInstruction(Zeros{64} + 0x00102043, 32);
    assert dim_102043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x08104e13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    let bind_1 = ExecuteCommandInstruction(Zeros{64} + 0x1038ce13, 32);
    assert bind_1 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(106);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(106);
    assert SelectedBundleClosedUnarySchemaLegal(106);
    assert SelectedBundleClosedTFMASchemaLegal(106);
    assert SelectedBundleClosedQuantizationSchemaLegal(106);
    assert SelectedBundleClosedGenerationSchemaLegal(106);
    assert SelectedBundleClosedHistogramSchemaLegal(106);
    assert SelectedBundleClosedReductionSchemaLegal(106);
    assert SelectedBundleClosedSortingSchemaLegal(106);
    assert SelectedBundleClosedPartialSchemaLegal(106);
    assert SelectedBundleClosedExpansionSchemaLegal(106);
    assert SelectedBundleClosedTCVTSchemaLegal(106);
    assert SelectedBundleClosedTCMPSchemaLegal(106);
    assert SelectedBundleClosedTSELSchemaLegal(106);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(106);
    assert SelectedBundleClosedTCMPSSchemaLegal(106);
    assert SelectedBundleClosedTSELSSchemaLegal(106);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(106);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0276 TGEMV_MX source1 -> case_0276_normal_commit
func RunCase_0276() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        let configured = if tile MOD 2 == 1 then
            ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else TileDataType_E4M3)), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111')
            else ConfigureCubeTileForMask(tile, 128, 1, 1,
                (if tile == 2 then TileDataType_E8M0 else (if tile == 4 then TileDataType_E8M0 else TileDataType_E4M3)), (if tile == 3 then TileLayout_CUBE_N8 else TileLayout_CUBE_M16), TileLocation_Matrix, '1111');
        assert configured;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x39431181, 32);
    assert started == CommandExecution_Executed;
    let fpatr = ExecuteCommandInstruction(Zeros{64} + 0x00002023, 32);
    assert fpatr == CommandExecution_Executed;
    let datr = ExecuteCommandInstruction(Zeros{64} + 0x00701023, 32);
    assert datr == CommandExecution_Executed;
    let dim_100043 = ExecuteCommandInstruction(Zeros{64} + 0x00100043, 32);
    assert dim_100043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_102043 = ExecuteCommandInstruction(Zeros{64} + 0x00102043, 32);
    assert dim_102043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x08104e13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_1 = ExecuteCommandInstruction(Zeros{64} + 0x800000d3, 32);
    assert modifier_0_1 == CommandExecution_Executed;
    let bind_1 = ExecuteCommandInstruction(Zeros{64} + 0x1038ce13, 32);
    assert bind_1 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(106);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedBinarySchemaLegal(106);
    assert SelectedBundleClosedUnarySchemaLegal(106);
    assert SelectedBundleClosedTFMASchemaLegal(106);
    assert SelectedBundleClosedQuantizationSchemaLegal(106);
    assert SelectedBundleClosedGenerationSchemaLegal(106);
    assert SelectedBundleClosedHistogramSchemaLegal(106);
    assert SelectedBundleClosedReductionSchemaLegal(106);
    assert SelectedBundleClosedSortingSchemaLegal(106);
    assert SelectedBundleClosedPartialSchemaLegal(106);
    assert SelectedBundleClosedExpansionSchemaLegal(106);
    assert SelectedBundleClosedTCVTSchemaLegal(106);
    assert SelectedBundleClosedTCMPSchemaLegal(106);
    assert SelectedBundleClosedTSELSchemaLegal(106);
    assert SelectedBundleClosedTileScalarBinarySchemaLegal(106);
    assert SelectedBundleClosedTCMPSSchemaLegal(106);
    assert SelectedBundleClosedTSELSSchemaLegal(106);
    assert SelectedBundleClosedTEXPANDSSchemaLegal(106);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

func main() => integer
begin
    let result_0273 = RunCase_0273();
    assert result_0273;
    let result_0274 = RunCase_0274();
    assert result_0274;
    let result_0275 = RunCase_0275();
    assert result_0275;
    let result_0276 = RunCase_0276();
    assert result_0276;
    return 0;
end;
