// PTO-TEST: {"id":"PTO-AVS-BLOCK-RANGE-OPERATION-MATRIX-003","source":"asl/block/model/operands/subview-descriptor.asl","requirements":["PTO-B-SUBVIEW-DESCRIPTOR-001","PTO-BLOCK-TILE-OPERATION-APPLICABILITY-001","PTO-B-ASSEMBLE-PRODUCER-EFFECT-ELIGIBILITY-001"],"kind":"execution","summary":"Generated decoded operation-role cases exercise every required source and destination role through normal dispatch.","pass_condition":"Every case binds its authoritative fixture recipe and catalog-required operands/attributes, reaches normal modifier and applicability preflight, then asserts either its exact normal observable or its exact pre-effect fault.","related_sources":["asl/block/model/operands/subview-descriptor.asl","asl/block/model/operands/range-modifiers.asl","asl/block/model/operands/portable-carriers.asl"]}
// Generated by scripts/generate-bundle-operation-matrix.py; cases: RANGE-MATRIX-CASE-0009, RANGE-MATRIX-CASE-0010, RANGE-MATRIX-CASE-0011, RANGE-MATRIX-CASE-0012
// RANGE-MATRIX-CASE-0009 TMUL destination0 -> case_0009_normal_commit
func RunCase_0009() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 0 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x20219181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0818ce13, 32);
    assert bind_0 == CommandExecution_Executed;
    let assemble_0 = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(2);
    assert SelectedBundleClosedBinarySchemaLegal(2);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    let completed_writer_0 = CompleteBundleLocalGenerationWriterEvent(
        BundleLocalGenerationSlot(0, '1111'), _BundleExecutionDomainToken,
        0, BundleLocalGenerationCellCount(1));
    assert completed_writer_0;
    assert _LocalGenerations[[BundleLocalGenerationSlot(0, '1111')]].published;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0010 TDIV source0 -> case_0010_normal_commit
func RunCase_0010() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 1 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x20319181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0818ce13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_0 = ExecuteCommandInstruction(Zeros{64} + 0x000000d3, 32);
    assert modifier_0_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(3);
    assert SelectedBundleClosedBinarySchemaLegal(3);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0011 TDIV source1 -> case_0011_normal_commit
func RunCase_0011() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 2 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x20319181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0818ce13, 32);
    assert bind_0 == CommandExecution_Executed;
    let modifier_0_1 = ExecuteCommandInstruction(Zeros{64} + 0x800000d3, 32);
    assert modifier_0_1 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(3);
    assert SelectedBundleClosedBinarySchemaLegal(3);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

// RANGE-MATRIX-CASE-0012 TDIV destination0 -> case_0012_normal_commit
func RunCase_0012() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 0 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_FP16, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                16, 4, 1,
                4, TileDataType_FP16,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0x20319181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_101043 = ExecuteCommandInstruction(Zeros{64} + 0x00101043, 32);
    assert dim_101043 == CommandExecution_Executed;
    let dim_402043 = ExecuteCommandInstruction(Zeros{64} + 0x00402043, 32);
    assert dim_402043 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0818ce13, 32);
    assert bind_0 == CommandExecution_Executed;
    let assemble_0 = ExecuteCommandInstruction(Zeros{64} + 0x800018d3, 32);
    assert assemble_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(3);
    assert SelectedBundleClosedBinarySchemaLegal(3);
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    let completed_writer_0 = CompleteBundleLocalGenerationWriterEvent(
        BundleLocalGenerationSlot(0, '1111'), _BundleExecutionDomainToken,
        0, BundleLocalGenerationCellCount(1));
    assert completed_writer_0;
    assert _LocalGenerations[[BundleLocalGenerationSlot(0, '1111')]].published;
    return TRUE;
end;

func main() => integer
begin
    let result_0009 = RunCase_0009();
    assert result_0009;
    let result_0010 = RunCase_0010();
    assert result_0010;
    let result_0011 = RunCase_0011();
    assert result_0011;
    let result_0012 = RunCase_0012();
    assert result_0012;
    return 0;
end;
