// PTO-TEST: {"id":"PTO-AVS-BLOCK-RANGE-OPERATION-MATRIX-265","source":"asl/block/model/operands/subview-descriptor.asl","requirements":["PTO-B-SUBVIEW-DESCRIPTOR-001","PTO-BLOCK-TILE-OPERATION-APPLICABILITY-001","PTO-B-ASSEMBLE-PRODUCER-EFFECT-ELIGIBILITY-001"],"kind":"execution","summary":"One decoded operation-role case exercises its required source or destination role through normal dispatch.","pass_condition":"The case binds its authoritative fixture recipe and catalog-required operands/attributes, reaches normal modifier and applicability preflight, then asserts its exact normal observable or pre-effect fault.","related_sources":["asl/block/model/operands/subview-descriptor.asl","asl/block/model/operands/range-modifiers.asl","asl/block/model/operands/portable-carriers.asl"]}
// Generated by scripts/generate-bundle-operation-matrix.py; case: RANGE-MATRIX-CASE-0265
// RANGE-MATRIX-CASE-0265 TGPR2T source0 -> case_0265_normal_commit
func RunCase_0265() => boolean
begin
    ResetProfileState();
    WriteGPR(0, Zeros{PTO_XLEN});
    WriteGPR(2, Zeros{PTO_XLEN} + 1);
    WriteGPR(3, Zeros{PTO_XLEN});
    WriteGPR(4, Zeros{PTO_XLEN} + 1);
    for tile = 1 to 8 looplimit 8 do
        if tile == 1 then
            let configured =
            ConfigureCubeTileForMask(tile, 128, 1,
                4, TileDataType_U8, TileLayout_CUBE_M16,
                TileLocation_Matrix, '1111');
            assert configured;
        else
            ConfigureTileForMask(tile, 128,
                32, 4, 1,
                4, TileDataType_U8,
                TileLayout_RowMajor, TileLocation_Any, '1111');
        end;
        InstallRelativeTileFixture(tile, tile);
        MarkTileValidRegionDefined(tile);
    end;
    let started = ExecuteCommandInstruction(Zeros{64} + 0xdfe19181, 32);
    assert started == CommandExecution_Executed;
    let dim_400043 = ExecuteCommandInstruction(Zeros{64} + 0x00400043, 32);
    assert dim_400043 == CommandExecution_Executed;
    let dim_2001043 = ExecuteCommandInstruction(Zeros{64} + 0x02001043, 32);
    assert dim_2001043 == CommandExecution_Executed;
    WriteGPR(5, Zeros{PTO_XLEN} + 1);
    let tgpr_sources_0 = ExecuteCommandInstruction(Zeros{64} + 0x20310013, 32);
    let tgpr_sources_1 = ExecuteCommandInstruction(Zeros{64} + 0x00028013, 32);
    assert tgpr_sources_0 == CommandExecution_Executed;
    assert tgpr_sources_1 == CommandExecution_Executed;
    let bind_0 = ExecuteCommandInstruction(Zeros{64} + 0x0008ee13, 32);
    assert bind_0 == CommandExecution_Executed;
    assert BundleOperationBindingsComplete(98);
    let prepared_stage2 = PrepareSelectedBundleStage2();
    assert prepared_stage2;
    assert SelectedBundleClosedSchemasLegal(98);
    assert SelectedBundleTileMasksLegal();
    let completed = ExecuteBundleTileOperation();
    assert completed;
    if !completed then assert _LastFault == Fault_TileLegality; end;
    assert _LastFault == Fault_None;
    var observed_destination: TileIndex = 0;
    for binding = 0 to PTO_BUNDLE_TILE_BINDING_COUNT - 1 do
        if _BundleTileBindings[[binding]].valid &&
           _BundleTileBindings[[binding]].destination_valid then
            observed_destination = _BundleTileBindings[[binding]].destination;
        end;
    end;
    assert _Tiles[[observed_destination]].allocated &&
           _Tiles[[observed_destination]].contents_defined;
    return TRUE;
end;

func main() => integer
begin
    let result_0265 = RunCase_0265();
    assert result_0265;
    return 0;
end;
