// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FCVTN-BOUND-001","source":"asl/scalar/fsu/FCVTN.asl","requirements":["PTO-INST-SCALAR-FCVTN"],"kind":"boundary","summary":"FCVTN covers zeros, infinities, NaNs, extrema, and signed carriers","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUBounds_FCVTN();
    return 0;
end;
