// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FCVTN-SRC-001","source":"asl/scalar/fsu/FCVTN.asl","requirements":["PTO-INST-SCALAR-FCVTN"],"kind":"execution","summary":"FCVTN covers absolute and temporary-queue source selectors and aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUAliasSources_FCVTN();
    return 0;
end;
