// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SD-PCR-EXEC-001","source":"asl/scalar/agu/HL.SD.PCR.asl","requirements":["PTO-INST-SCALAR-HL-SD-PCR"],"kind":"execution","summary":"HL.SD.PCR executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_SD_PCR();
    return 0;
end;
