// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-CASD-DECODE-001","source":"asl/scalar/amo/HL.CASD.asl","requirements":["PTO-INST-SCALAR-HL-CASD"],"kind":"decode-positive","summary":"canonical HL.CASD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('001100000000000001100000000010110000000000001110', 48) == 132;
    assert ScalarOperationOfForm(132) == ScalarOperation_HL_CASD;
    assert ScalarHandlerOfForm(132) == ScalarHandler_CompareAndSwap;
    assert InstructionContractOperation_HL_CASD() == ScalarOperation_HL_CASD;
    assert InstructionContractHandler_HL_CASD() == ScalarHandler_CompareAndSwap;
    assert DecodeScalarOperandRaw('001100000000000001100000000010110000000000001110', 132, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001100000000000001100000000010110000000000001110', 132, ScalarField_SrcD) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001100000000000001100000000010110000000000001110', 132, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001100000000000001100000000010110000000000001110', 132, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001100000000000001100000000010110000000000001110', 132, ScalarField_aq) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001100000000000001100000000010110000000000001110', 132, ScalarField_far) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('001100000000000001100000000010110000000000001110', 132, ScalarField_rl) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
