// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SWIP-EXEC-001","source":"asl/scalar/agu/HL.SWIP.asl","requirements":["PTO-INST-SCALAR-HL-SWIP"],"kind":"execution","summary":"HL.SWIP executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_SWIP();
    return 0;
end;
