// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-C-ADD-DECODE-001","source":"asl/scalar/alu/C.ADD.asl","requirements":["PTO-INST-SCALAR-C-ADD"],"kind":"decode-positive","summary":"canonical C.ADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000000000000001000', 16) == 31;
    assert ScalarOperationOfForm(31) == ScalarOperation_C_ADD;
    assert ScalarHandlerOfForm(31) == ScalarHandler_ScalarBinary;
    assert InstructionContractOperation_C_ADD() == ScalarOperation_C_ADD;
    assert InstructionContractHandler_C_ADD() == ScalarHandler_ScalarBinary;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000001000', 31, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000001000', 31, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
