// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SH-UPR-FAULT-001","source":"asl/scalar/agu/HL.SH.UPR.asl","requirements":["PTO-INST-SCALAR-HL-SH-UPR"],"kind":"fault","summary":"HL.SH.UPR rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_HL_SH_UPR();
    return 0;
end;
