// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-RED-MAX-SEMANTIC-001","source":"asl/tile/memory-and-data-movement/irregular/RED_MAX.asl","requirements":["PTO-INST-TILE-RED-MAX"],"kind":"execution","summary":"RED_MAX exercises its GM semantic primitive at the owner boundary","pass_condition":"the decoded owner mapping and representative GM effect assertions hold","related_sources":["asl/tile/model/memory/gm-atom-red.asl","asl/tile/model/memory/gm-atom-red-execution.asl"]}
func main() => integer
begin
    assert GMReductionOperationFromFunction(19) == GMReduction_MAX;
    assert GMReductionOperationDataTypeLegal(GMReduction_MAX, TileDataType_U32);
    assert GMReductionResult(GMReduction_MAX, TileDataType_U32,
        Zeros{PTO_XLEN} + 3, Zeros{PTO_XLEN} + 5) ==
        Zeros{PTO_XLEN} + 5;
    return 0;
end;
