// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SB-PCR-EXEC-001","source":"asl/scalar/agu/SB.PCR.asl","requirements":["PTO-INST-SCALAR-SB-PCR"],"kind":"execution","summary":"SB.PCR executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_SB_PCR();
    return 0;
end;
