// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SW-PCR-FAULT-001","source":"asl/scalar/agu/SW.PCR.asl","requirements":["PTO-INST-SCALAR-SW-PCR"],"kind":"fault","summary":"SW.PCR rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_SW_PCR();
    return 0;
end;
