// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LWU-PCR-EXEC-001","source":"asl/scalar/agu/LWU.PCR.asl","requirements":["PTO-INST-SCALAR-LWU-PCR"],"kind":"execution","summary":"LWU.PCR executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_LWU_PCR();
    return 0;
end;
