// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LWUI-PO-ALIAS-001","source":"asl/scalar/agu/HL.LWUI.PO.asl","requirements":["PTO-INST-SCALAR-HL-LWUI-PO"],"kind":"execution","summary":"HL.LWUI.PO covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_HL_LWUI_PO();
    return 0;
end;
