// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TCOLEXPAND-STATIC-001","source":"asl/tile/reduce-and-expand/column-expansion/TCOLEXPAND.asl","requirements":["PTO-INST-TILE-TCOLEXPAND"],"kind":"static-invariant","summary":"canonical TCOLEXPAND catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: reduce-and-expand/column-expansion
    // block: BSTART.SFU TCOLEXPAND, DataType | B.DATR Layout, PadValue (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT BroadcastTile, mask=PE_MASK, <last>, ->DstTile<TSize> | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001010100') == 58;
    assert TileOperationOfIndex(58) == TileOperation_TCOLEXPAND;
    assert TileHandlerOfIndex(58) == TileHandler_ExecuteTileExpand;
    assert TileClassOfIndex(58) == TileClass_ReduceAndExpand;
    assert TileEngineOfIndex(58) == TileEngine_SFU;
    assert InstructionContractOperation_TCOLEXPAND() == TileOperation_TCOLEXPAND;
    assert InstructionContractHandler_TCOLEXPAND() == TileHandler_ExecuteTileExpand;
    return 0;
end;
