// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TLOG-STATIC-INVARIANT-001","source":"asl/tile/elementwise-tile-tile/transcendental/TLOG.asl","requirements":["PTO-INST-TILE-TLOG"],"kind":"static-invariant","summary":"canonical TLOG catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: elementwise-tile-tile/transcendental
    // block: BSTART.SFU TLOG, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000010011') == 17;
    assert TileOperationOfIndex(17) == TileOperation_TLOG;
    assert TileHandlerOfIndex(17) == TileHandler_ExecuteTileUnary;
    assert TileClassOfIndex(17) == TileClass_ElementwiseTileTile;
    assert TileEngineOfIndex(17) == TileEngine_SFU;
    assert InstructionContractOperation_TLOG() == TileOperation_TLOG;
    assert InstructionContractHandler_TLOG() == TileHandler_ExecuteTileUnary;
    return 0;
end;
