// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FMAX-EXEC-001","source":"asl/scalar/fsu/FMAX.asl","requirements":["PTO-INST-SCALAR-FMAX"],"kind":"execution","summary":"FMAX executes the canonical floating-point or conversion effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUExecute_FMAX();
    return 0;
end;
