// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FMAX-RSVD-001","source":"asl/scalar/fsu/FMAX.asl","requirements":["PTO-INST-SCALAR-FMAX"],"kind":"fault","summary":"FMAX rejects reserved data-type encodings before architectural effects","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUTypesReserved_FMAX();
    return 0;
end;
