// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-MSCATTER-MIN-SEMANTIC-001","source":"asl/tile/memory-and-data-movement/irregular/MSCATTER_MIN.asl","requirements":["PTO-INST-TILE-MSCATTER-MIN"],"kind":"execution","summary":"MSCATTER_MIN exercises its GM semantic primitive at the owner boundary","pass_condition":"the decoded owner mapping and representative GM effect assertions hold","related_sources":["asl/tile/model/memory/gm-atom-red.asl","asl/tile/model/memory/gm-atom-red-execution.asl"]}
func main() => integer
begin
    assert GMReductionOperationFromFunction(20) == GMReduction_MIN;
    assert GMReductionOperationDataTypeLegal(GMReduction_MIN, TileDataType_U32);
    assert GMReductionResult(GMReduction_MIN, TileDataType_U32,
        Zeros{PTO_XLEN} + 3, Zeros{PTO_XLEN} + 5) ==
        Zeros{PTO_XLEN} + 3;
    return 0;
end;
