// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-TCVT-CONVERSION-STATIC-001","source":"asl/tile/model/numeric/tcvt-conversion.asl","requirements":[],"kind":"static-invariant","summary":"PTO-TILE-MODEL-NUMERIC-TCVT-CONVERSION compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
