// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-CMP-NE-BOUND-001","source":"asl/scalar/bru/CMP.NE.asl","requirements":["PTO-INST-SCALAR-CMP-NE"],"kind":"boundary","summary":"CMP.NE covers operand selectors, immediates, conditions, targets, and faults","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUBounds_CMP_NE();
    return 0;
end;
