// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SW-PO-EXEC-001","source":"asl/scalar/agu/HL.SW.PO.asl","requirements":["PTO-INST-SCALAR-HL-SW-PO"],"kind":"execution","summary":"HL.SW.PO executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_SW_PO();
    return 0;
end;
