// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-MGATHER-INC-STATIC-001","source":"asl/tile/memory-and-data-movement/irregular/MGATHER_INC.asl","requirements":["PTO-INST-TILE-MGATHER-INC"],"kind":"static-invariant","summary":"canonical MGATHER_INC catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory-and-data-movement/irregular
    // block: BSTART.MGATHER.INC DataType | B.IOT IndexTile, ValueTile, mask=PE_MASK, <last>, ->DstTile<TSize> | B.IOR BaseGPR, zero, zero, ->zero | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000001110') == 104;
    assert TileOperationOfIndex(104) == TileOperation_MGATHER_INC;
    assert TileHandlerOfIndex(104) == TileHandler_GM_ATOM_VALUE;
    assert TileClassOfIndex(104) == TileClass_MemoryAndDataMovement;
    assert TileEngineOfIndex(104) == TileEngine_TLSU;
    assert InstructionContractOperation_MGATHER_INC() == TileOperation_MGATHER_INC;
    assert InstructionContractHandler_MGATHER_INC() == TileHandler_GM_ATOM_VALUE;
    return 0;
end;
