// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-FMSUB-DECODE-001","source":"asl/scalar/fsu/FMSUB.asl","requirements":["PTO-INST-SCALAR-FMSUB"],"kind":"decode-positive","summary":"canonical FMSUB catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000101000001001011', 32) == 116;
    assert ScalarOperationOfForm(116) == ScalarOperation_FMSUB;
    assert ScalarHandlerOfForm(116) == ScalarHandler_FloatingFused;
    assert InstructionContractOperation_FMSUB() == ScalarOperation_FMSUB;
    assert InstructionContractHandler_FMSUB() == ScalarHandler_FloatingFused;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000001001011', 116, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000001001011', 116, ScalarField_SrcA) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000001001011', 116, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000001001011', 116, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000101000001001011', 116, ScalarField_SrcType) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
