// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FMSUB-DST-001","source":"asl/scalar/fsu/FMSUB.asl","requirements":["PTO-INST-SCALAR-FMSUB"],"kind":"execution","summary":"FMSUB covers discard, reserved-discard, GPR, and temporary-queue destinations","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUAliasDestination_FMSUB();
    return 0;
end;
