// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FMSUB-ROUND-001","source":"asl/scalar/fsu/FMSUB.asl","requirements":["PTO-INST-SCALAR-FMSUB"],"kind":"boundary","summary":"FMSUB covers all encoded active or fixed rounding-mode selections","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSURounding_FMSUB();
    return 0;
end;
