// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FMSUB-TYPE-001","source":"asl/scalar/fsu/FMSUB.asl","requirements":["PTO-INST-SCALAR-FMSUB"],"kind":"boundary","summary":"FMSUB covers every assigned source and destination data-type encoding","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUTypesLegal_FMSUB();
    return 0;
end;
