// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TCMPS-STATIC-INVARIANT-001","source":"asl/tile/tile-scalar-and-immediate/logical/TCMPS.asl","requirements":["PTO-INST-TILE-TCMPS"],"kind":"static-invariant","summary":"canonical TCMPS catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: tile-scalar-and-immediate/logical
    // block: BSTART.VEC TCMPS, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | B.IOR | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000101101') == 37;
    assert TileOperationOfIndex(37) == TileOperation_TCMPS;
    assert TileHandlerOfIndex(37) == TileHandler_ExecuteTileCompareScalar;
    assert TileClassOfIndex(37) == TileClass_TileScalarAndImmediate;
    assert TileEngineOfIndex(37) == TileEngine_VEC;
    assert InstructionContractOperation_TCMPS() == TileOperation_TCMPS;
    assert InstructionContractHandler_TCMPS() == TileHandler_ExecuteTileCompareScalar;
    return 0;
end;
