// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-C-AND-DECODE-001","source":"asl/scalar/alu/C.AND.asl","requirements":["PTO-INST-SCALAR-C-AND"],"kind":"decode-positive","summary":"canonical C.AND catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000000000000101000', 16) == 25;
    assert ScalarOperationOfForm(25) == ScalarOperation_C_AND;
    assert ScalarHandlerOfForm(25) == ScalarHandler_ScalarBinary;
    assert InstructionContractOperation_C_AND() == ScalarOperation_C_AND;
    assert InstructionContractHandler_C_AND() == ScalarHandler_ScalarBinary;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000101000', 25, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000101000', 25, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
