// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LBI-PO-BOUND-001","source":"asl/scalar/agu/HL.LBI.PO.asl","requirements":["PTO-INST-SCALAR-HL-LBI-PO"],"kind":"boundary","summary":"HL.LBI.PO covers address fields, modifiers, limits, and wrap behavior","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUBounds_HL_LBI_PO();
    return 0;
end;
