// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SYS-SSRGET-EXEC-001","source":"asl/scalar/sys/SSRGET.asl","requirements":["PTO-INST-SCALAR-SSRGET"],"kind":"execution","summary":"SSRGET proves its direct SYS contract","pass_condition":"the mnemonic-owned decoded assertions hold","related_sources":[]}
func main() => integer
begin
    ResetProfileState();
    SetCurrentACR(0);
    WriteTPC(Zeros{PTO_XLEN} + 0x100);
    BeginBundle(BundleKind_System, BundleTransfer_Fallthrough,
        Zeros{PTO_XLEN}, Zeros{PTO_XLEN} + 0x180,
        Zeros{PTO_XLEN}, FALSE);
    EnterBundleBody();
    _SystemRegisters.thread_ptr = Zeros{PTO_XLEN} + 0x111;
    let status = ExecuteScalarInstruction('000000000000000000000000000000000000000110111011', 32);
    assert status == ScalarExecution_Executed;
    assert _LastFault == Fault_None;
    assert ReadGPR(3) == Zeros{PTO_XLEN} + 0x111;
    assert ReadTPC() == Zeros{PTO_XLEN} + 0x184;
    assert InstructionContractOperation_SSRGET() == ScalarOperation_SSRGET;
    return 0;
end;
