// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TMOV-STATIC-001","source":"asl/tile/layout-and-rearrangement/layout/TMOV.asl","requirements":["PTO-INST-TILE-TMOV"],"kind":"static-invariant","summary":"canonical TMOV catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: layout-and-rearrangement/layout
    // block: BSTART.TLSU TMOV, DataType | B.DIM LB0 | B.DIM LB1 (optional) | B.DIM LB2 (optional) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000000010') == 83;
    assert TileOperationOfIndex(83) == TileOperation_TMOV;
    assert TileHandlerOfIndex(83) == TileHandler_TMOV;
    assert TileClassOfIndex(83) == TileClass_LayoutAndRearrangement;
    assert TileEngineOfIndex(83) == TileEngine_TLSU;
    assert InstructionContractOperation_TMOV() == TileOperation_TMOV;
    assert InstructionContractHandler_TMOV() == TileHandler_TMOV;
    return 0;
end;
