// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-RED-ADD-SEMANTIC-001","source":"asl/block/execution/BSTART.RED.ADD.asl","requirements":["PTO-INST-BLOCK-BSTART-RED-ADD"],"kind":"execution","summary":"BSTART.RED.ADD exercises its GM semantic primitive at the owner boundary","pass_condition":"the decoded owner mapping and representative GM effect assertions hold","related_sources":["asl/tile/model/memory/gm-atom-red.asl","asl/tile/model/memory/gm-atom-red-execution.asl"]}
func main() => integer
begin
    assert GMReductionOperationFromFunction(21) == GMReduction_ADD;
    assert GMReductionOperationDataTypeLegal(GMReduction_ADD, TileDataType_U32);
    assert GMReductionResult(GMReduction_ADD, TileDataType_U32,
        Zeros{PTO_XLEN} + 3, Zeros{PTO_XLEN} + 5) ==
        Zeros{PTO_XLEN} + 12;
    return 0;
end;
