// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-LW-UMIN-DECODE-001","source":"asl/scalar/amo/LW.UMIN.asl","requirements":["PTO-INST-SCALAR-LW-UMIN"],"kind":"decode-positive","summary":"canonical LW.UMIN catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000001110000000000000010000000001011', 32) == 348;
    assert ScalarOperationOfForm(348) == ScalarOperation_LW_UMIN;
    assert ScalarHandlerOfForm(348) == ScalarHandler_AtomicReadModifyWrite;
    assert InstructionContractOperation_LW_UMIN() == ScalarOperation_LW_UMIN;
    assert InstructionContractHandler_LW_UMIN() == ScalarHandler_AtomicReadModifyWrite;
    assert DecodeScalarOperandRaw('000000000000000001110000000000000010000000001011', 348, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000000000000010000000001011', 348, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000000000000010000000001011', 348, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000000000000010000000001011', 348, ScalarField_aq) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000000000000010000000001011', 348, ScalarField_far) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000000000000010000000001011', 348, ScalarField_rl) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
