// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SH-U-ALIAS-001","source":"asl/scalar/agu/SH.U.asl","requirements":["PTO-INST-SCALAR-SH-U"],"kind":"execution","summary":"SH.U covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_SH_U();
    return 0;
end;
