// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-BSTART-RED-MIN-DECODE-001","source":"asl/block/execution/BSTART.RED.MIN.asl","requirements":["PTO-INST-BLOCK-BSTART-RED-MIN"],"kind":"decode-positive","summary":"canonical BSTART.RED.MIN catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000000001010000010001000110000001', 32) == 86;
    assert CommandOperationOfForm(86) == CommandOperation_bstart_red_min_32_gm20;
    assert CommandHandlerOfForm(86) == CommandHandler_ExecuteBundleStart;
    assert InstructionContractMatches_BSTART_RED_MIN(CommandOperationOfForm(86));
    assert InstructionContractHandler_BSTART_RED_MIN() == CommandHandler_ExecuteBundleStart;
    return 0;
end;
