// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LBU-FAULT-001","source":"asl/scalar/agu/LBU.asl","requirements":["PTO-INST-SCALAR-LBU"],"kind":"fault","summary":"LBU rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_LBU();
    return 0;
end;
