// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LBU-ALIAS-001","source":"asl/scalar/agu/LBU.asl","requirements":["PTO-INST-SCALAR-LBU"],"kind":"execution","summary":"LBU covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_LBU();
    return 0;
end;
