// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-HL-SETRET-EXEC-001","source":"asl/scalar/bru/HL.SETRET.asl","requirements":["PTO-INST-SCALAR-HL-SETRET"],"kind":"execution","summary":"HL.SETRET executes the canonical comparison, branch, jump, or control effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUExecute_HL_SETRET();
    return 0;
end;
