// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-SW-OR-DECODE-001","source":"asl/scalar/amo/SW.OR.asl","requirements":["PTO-INST-SCALAR-SW-OR"],"kind":"decode-positive","summary":"canonical SW.OR catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000100000000000000011000000001011', 32) == 451;
    assert ScalarOperationOfForm(451) == ScalarOperation_SW_OR;
    assert ScalarHandlerOfForm(451) == ScalarHandler_AtomicReadModifyWrite;
    assert InstructionContractOperation_SW_OR() == ScalarOperation_SW_OR;
    assert InstructionContractHandler_SW_OR() == ScalarHandler_AtomicReadModifyWrite;
    assert DecodeScalarOperandRaw('000000000000000000100000000000000011000000001011', 451, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000100000000000000011000000001011', 451, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000100000000000000011000000001011', 451, ScalarField_far) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000100000000000000011000000001011', 451, ScalarField_rl) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
