// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-MGATHER-CAS-STATIC-001","source":"asl/tile/memory-and-data-movement/irregular/MGATHER_CAS.asl","requirements":["PTO-INST-TILE-MGATHER-CAS"],"kind":"static-invariant","summary":"canonical MGATHER_CAS catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory-and-data-movement/irregular
    // block: BSTART.MGATHER.CAS DataType | B.DATR PadValue, Layout (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT IndexTile, ExpectedTile, mask=PE_MASK | B.IOT ReplacementTile, mask=PE_MASK, <last>, ->DstTile<TSize> | B.IOR BaseGPR, zero, zero, ->zero | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000001000') == 95;
    assert TileOperationOfIndex(95) == TileOperation_MGATHER_CAS;
    assert TileHandlerOfIndex(95) == TileHandler_MGATHER_CAS;
    assert TileClassOfIndex(95) == TileClass_MemoryAndDataMovement;
    assert TileEngineOfIndex(95) == TileEngine_TLSU;
    assert InstructionContractOperation_MGATHER_CAS() == TileOperation_MGATHER_CAS;
    assert InstructionContractHandler_MGATHER_CAS() == TileHandler_MGATHER_CAS;
    return 0;
end;
