// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-HL-SETC-ANDI-EXEC-001","source":"asl/scalar/bru/HL.SETC.ANDI.asl","requirements":["PTO-INST-SCALAR-HL-SETC-ANDI"],"kind":"execution","summary":"HL.SETC.ANDI executes the canonical comparison, branch, jump, or control effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUExecute_HL_SETC_ANDI();
    return 0;
end;
