// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BLOCK-HL-QPUSH-DECODE-001","source":"asl/block/lifecycle/HL.QPUSH.asl","requirements":["PTO-INST-BLOCK-HL-QPUSH"],"kind":"decode-positive","summary":"canonical HL.QPUSH catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeCommandForm('0000000000000000000000000000000000010000011111010000000000001110', 48) == 68;
    assert CommandOperationOfForm(68) == CommandOperation_hl_qpush_48_3eab8e05d61a;
    assert CommandHandlerOfForm(68) == CommandHandler_ExecuteQueuePush;
    assert InstructionContractMatches_HL_QPUSH(CommandOperationOfForm(68));
    assert InstructionContractHandler_HL_QPUSH() == CommandHandler_ExecuteQueuePush;
    return 0;
end;
