// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LB-EXEC-001","source":"asl/scalar/agu/LB.asl","requirements":["PTO-INST-SCALAR-LB"],"kind":"execution","summary":"LB executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_LB();
    return 0;
end;
