// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TROWEXPANDADD-STATIC-001","source":"asl/tile/reduce-and-expand/row-expansion/TROWEXPANDADD.asl","requirements":["PTO-INST-TILE-TROWEXPANDADD"],"kind":"static-invariant","summary":"canonical TROWEXPANDADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: reduce-and-expand/row-expansion
    // block: BSTART.SFU TROWEXPANDADD, DataType | B.DATR Layout, PadValue (optional) | B.DIM LB0=ValidCol | B.DIM LB1=ValidRow (optional) | B.DIM LB2=Col (optional) | B.IOT SrcTile, BroadcastTile, mask=PE_MASK, <last>, ->DstTile<TSize> | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001000101') == 45;
    assert TileOperationOfIndex(45) == TileOperation_TROWEXPANDADD;
    assert TileHandlerOfIndex(45) == TileHandler_ExecuteTileExpand;
    assert TileClassOfIndex(45) == TileClass_ReduceAndExpand;
    assert TileEngineOfIndex(45) == TileEngine_SFU;
    assert InstructionContractOperation_TROWEXPANDADD() == TileOperation_TROWEXPANDADD;
    assert InstructionContractHandler_TROWEXPANDADD() == TileHandler_ExecuteTileExpand;
    return 0;
end;
