// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-SHI-UPO-ALIAS-001","source":"asl/scalar/agu/HL.SHI.UPO.asl","requirements":["PTO-INST-SCALAR-HL-SHI-UPO"],"kind":"execution","summary":"HL.SHI.UPO covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_HL_SHI_UPO();
    return 0;
end;
