// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-BRU-SETC-ORI-BOUND-001","source":"asl/scalar/bru/SETC.ORI.asl","requirements":["PTO-INST-SCALAR-SETC-ORI"],"kind":"boundary","summary":"SETC.ORI covers operand selectors, immediates, conditions, targets, and faults","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarBRUBounds_SETC_ORI();
    return 0;
end;
