// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TADD-STATIC-INVARIANT-001","source":"asl/tile/tile-tile-elementwise/arithmetic/TADD.asl","requirements":["PTO-INST-TILE-TADD"],"kind":"static-invariant","summary":"canonical TADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: tile-tile-elementwise/arithmetic
    // block: BSTART.TEPL TADD, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000000000000') == 0;
    assert TileOperationOfIndex(0) == TileOperation_TADD;
    assert TileHandlerOfIndex(0) == TileHandler_ExecuteTileBinary;
    assert InstructionContractOperation_TADD() == TileOperation_TADD;
    assert InstructionContractHandler_TADD() == TileHandler_ExecuteTileBinary;
    return 0;
end;
