// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TCOLEXPANDADD-STATIC-INVARIANT-001","source":"asl/tile/vector-tile-expansion/column-expansion/TCOLEXPANDADD.asl","requirements":["PTO-INST-TILE-TCOLEXPANDADD"],"kind":"static-invariant","summary":"canonical TCOLEXPANDADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: vector-tile-expansion/column-expansion
    // block: BSTART.TEPL TCOLEXPANDADD, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001010101') == 59;
    assert TileOperationOfIndex(59) == TileOperation_TCOLEXPANDADD;
    assert TileHandlerOfIndex(59) == TileHandler_ExecuteTileExpand;
    assert InstructionContractOperation_TCOLEXPANDADD() == TileOperation_TCOLEXPANDADD;
    assert InstructionContractHandler_TCOLEXPANDADD() == TileHandler_ExecuteTileExpand;
    return 0;
end;
