// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LH-PCR-EXEC-001","source":"asl/scalar/agu/LH.PCR.asl","requirements":["PTO-INST-SCALAR-LH-PCR"],"kind":"execution","summary":"LH.PCR executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_LH_PCR();
    return 0;
end;
