// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-LH-PCR-FAULT-001","source":"asl/scalar/agu/LH.PCR.asl","requirements":["PTO-INST-SCALAR-LH-PCR"],"kind":"fault","summary":"LH.PCR rejects faults before partial register or memory effects and reissues precisely","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUFault_LH_PCR();
    return 0;
end;
