// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-ARCH-PROFILE-EXTENSION-FIRST-USE-STATIC-001","source":"asl/arch/profile/extension-first-use.asl","requirements":["PTO-ARCH-EXTENSION-FIRST-USE-PROFILE-001"],"kind":"static-invariant","summary":"PTO-ARCH-PROFILE-EXTENSION-FIRST-USE compiles as an independent normative unit","pass_condition":"the complete model and this unit's static invariant compile","related_sources":[]}
func main() => integer
begin
    assert TRUE;
    return 0;
end;
