// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SD-PCR-EXEC-001","source":"asl/scalar/agu/SD.PCR.asl","requirements":["PTO-INST-SCALAR-SD-PCR"],"kind":"execution","summary":"SD.PCR executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_SD_PCR();
    return 0;
end;
