// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SD-PCR-ALIAS-001","source":"asl/scalar/agu/SD.PCR.asl","requirements":["PTO-INST-SCALAR-SD-PCR"],"kind":"execution","summary":"SD.PCR covers absolute and temporary register selector aliases","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUAlias_SD_PCR();
    return 0;
end;
