// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-FSU-FNMSUB-TYPE-001","source":"asl/scalar/fsu/FNMSUB.asl","requirements":["PTO-INST-SCALAR-FNMSUB"],"kind":"boundary","summary":"FNMSUB covers every assigned source and destination data-type encoding","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarFSUTypesLegal_FNMSUB();
    return 0;
end;
