// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-MGATHER-OR-STATIC-001","source":"asl/tile/memory-and-data-movement/irregular/MGATHER_OR.asl","requirements":["PTO-INST-TILE-MGATHER-OR"],"kind":"static-invariant","summary":"canonical MGATHER_OR catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: memory-and-data-movement/irregular
    // block: BSTART.MGATHER.OR DataType | B.IOT IndexTile, ValueTile, mask=PE_MASK, <last>, ->DstTile<TSize> | B.IOR BaseGPR, zero, zero, ->zero | BSTOP
    assert DecodeTileOperation(TileDecode_TLSU, '000000010001') == 107;
    assert TileOperationOfIndex(107) == TileOperation_MGATHER_OR;
    assert TileHandlerOfIndex(107) == TileHandler_GM_ATOM_VALUE;
    assert TileClassOfIndex(107) == TileClass_MemoryAndDataMovement;
    assert TileEngineOfIndex(107) == TileEngine_TLSU;
    assert InstructionContractOperation_MGATHER_OR() == TileOperation_MGATHER_OR;
    assert InstructionContractHandler_MGATHER_OR() == TileHandler_GM_ATOM_VALUE;
    return 0;
end;
