// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-HL-LWU-PCR-EXEC-001","source":"asl/scalar/agu/HL.LWU.PCR.asl","requirements":["PTO-INST-SCALAR-HL-LWU-PCR"],"kind":"execution","summary":"HL.LWU.PCR executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_HL_LWU_PCR();
    return 0;
end;
