// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-ACRE-DECODE-001","source":"asl/scalar/sys/ACRE.asl","requirements":["PTO-INST-SCALAR-ACRE"],"kind":"decode-positive","summary":"canonical ACRE catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000001000000000011000000101011', 32) == 1;
    assert ScalarOperationOfForm(1) == ScalarOperation_ACRE;
    assert ScalarHandlerOfForm(1) == ScalarHandler_ArchitectureEnterRequest;
    assert InstructionContractOperation_ACRE() == ScalarOperation_ACRE;
    assert InstructionContractHandler_ACRE() == ScalarHandler_ArchitectureEnterRequest;
    assert DecodeScalarOperandRaw('000000000000000000000001000000000011000000101011', 1, ScalarField_RRA_Type) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
