// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-ADD-DECODE-001","source":"asl/scalar/alu/ADD.asl","requirements":["PTO-INST-SCALAR-ADD"],"kind":"decode-positive","summary":"canonical ADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000000000000000000000000000000000101', 32) == 2;
    assert ScalarOperationOfForm(2) == ScalarOperation_ADD;
    assert ScalarHandlerOfForm(2) == ScalarHandler_ScalarBinary;
    assert InstructionContractOperation_ADD() == ScalarOperation_ADD;
    assert InstructionContractHandler_ADD() == ScalarHandler_ScalarBinary;
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000000101', 2, ScalarField_RegDst) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000000101', 2, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000000101', 2, ScalarField_SrcR) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000000101', 2, ScalarField_SrcRType) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000000000000000000000000000000000101', 2, ScalarField_shamt) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
