// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-SCALAR-HL-PRFI-U-DECODE-001","source":"asl/scalar/agu/HL.PRFI.U.asl","requirements":["PTO-INST-SCALAR-HL-PRFI-U"],"kind":"decode-positive","summary":"canonical HL.PRFI.U catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    assert DecodeScalarForm('000000000000000001110000001010010000000000001110', 48) == 238;
    assert ScalarOperationOfForm(238) == ScalarOperation_HL_PRFI_U;
    assert ScalarHandlerOfForm(238) == ScalarHandler_ScalarPrefetch;
    assert InstructionContractOperation_HL_PRFI_U() == ScalarOperation_HL_PRFI_U;
    assert InstructionContractHandler_HL_PRFI_U() == ScalarHandler_ScalarPrefetch;
    assert DecodeScalarOperandRaw('000000000000000001110000001010010000000000001110', 238, ScalarField_SrcL) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000001010010000000000001110', 238, ScalarField_model) == '000000000000000000000000000000000000000000000000';
    assert DecodeScalarOperandRaw('000000000000000001110000001010010000000000001110', 238, ScalarField_simm17) == '000000000000000000000000000000000000000000000000';
    return 0;
end;
