// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-AGU-SH-EXEC-001","source":"asl/scalar/agu/SH.asl","requirements":["PTO-INST-SCALAR-SH"],"kind":"execution","summary":"SH executes the canonical address calculation and architectural effect","pass_condition":"the mnemonic-owned semantic assertions hold","related_sources":[]}
func main() => integer
begin
    ValidateScalarAGUExecute_SH();
    return 0;
end;
