// Generated by scripts/generate-mnemonic-avs.py. Do not edit.
// PTO-TEST: {"id":"PTO-AVS-TILE-TPARTADD-STATIC-INVARIANT-001","source":"asl/tile/complex-layout/union/TPARTADD.asl","requirements":["PTO-INST-TILE-TPARTADD"],"kind":"static-invariant","summary":"canonical TPARTADD catalog and ASL contract remain aligned","pass_condition":"all canonical decode and contract assertions hold","related_sources":[]}
func main() => integer
begin
    // classification: complex-layout/union
    // block: BSTART.TEPL TPARTADD, DataType | B.DATR (optional) | B.DIM LB0 | B.DIM (LB1/LB2 for 2D) | B.IOT | BSTOP
    assert DecodeTileOperation(TileDecode_TEPL, '000001110001') == 83;
    assert TileOperationOfIndex(83) == TileOperation_TPARTADD;
    assert TileHandlerOfIndex(83) == TileHandler_ExecuteTilePartial;
    assert InstructionContractOperation_TPARTADD() == TileOperation_TPARTADD;
    assert InstructionContractHandler_TPARTADD() == TileHandler_ExecuteTilePartial;
    return 0;
end;
